### ISSUE TITLE
When running aio functions brython prematurely completes

### ISSUE THREAD

**Issue by desean1625** [brython-dev/brython#1043]
When running aio functions brython should return a promise that resolves after the script terminates/completes

script
---
```py
from browser import aio

async def main():
    print('Do some actions 1') # Expecting this to print but it doesn't
    await aio.sleep(10)
    print('Do some actions 2')# Expecting this to print but it doesn't
    await aio.sleep(1)
    print('Do some actions 3')# Expecting this to print but it doesn't

print("test")
aio.run(main())
```
output
---
```
test
Do some actions 1
<completed in   8.00 ms>
Do some actions 2
Do some actions 3
```

My usecase is I am running brython in a webworker and after the script completes I terminate the webworker. (it allows me to process thousands of rows off the main thread)

However, with the aio fuctions the <completed in 8.00ms> comes before all the async functions resolve.

@PierreQuentel Love the AIO async/await you added BTW

**Comment by PierreQuentel** [comment]
Thanks @desean1625 for reporting this. I realize that the __`webworker`__ module is broken because it uses __`asyncio`__, and I have removed it in version 3.7.1. I will try to fix this shortly.

I am not too sure about what your script does : the comment in line 4 says that the string is not printed, but in the output it is printed.

Anyway, since `aio.run()` is a _non-blocking_ function, the last instruction executed in the worker is  not the line after `aio.run()`, but the last line of `main()` ; and it should be a `post_reply()` to the main script, handled by a callback function that will run the code you want to run after the worker completes.
