### ISSUE TITLE
Brython dict() can't handle nested JS Object Literals (dict's)

### ISSUE THREAD

**Issue by cforger** [brython-dev/brython#109]
Hello,

 I've attempted correcting this in the source, but I'm too new to Brython to make sure I'm doing a good job - I see the creation of a dict requires issues with future updates to the JSObj, etc.

 The problem is simple to replicate. Assuming an Object Literal from a function like this:

    do_list = function(){
        return {1:'one', 2:'two', 3:'three', 4:{ 'big_bad_wolf':1 }}
    }

in Brython:

  js_dict = window.do_list()
  print(js_dict)

I see in line 304 of py_dict.js looping across the object, assigning the value to the new dict. 
Everything is fine until it hits item 4, where I see it assigns an Object to the value, so it's packing an un-wrapped JS Object into the brython dict.

The error is expressed as:

Uncaught Error: TypeError: Cannot read property '__mro__' of undefined

.. depending on how I'm accessing the dict, because it can't find what it for that object. 

If someone with more skill with Brython could fix this for me, I'd appreciate it.  

Thanks.

**Comment by earney** [comment]
I get the following when I replicate your code:

<JSObject wraps [object Object]>

in the developer console output  I see:
Error: object has no attribute __repr__
default to toString [object Object]

In other words, brython doesn't know how to create a string to represent:
return {1:'one', 2:'two', 3:'three', 4:{ 'big_bad_wolf':1 }}

so I took some code from our json library to help out with this.   You can fix the code like so:

<script type="text/javascript">
  function do_list() {
    return __BRYTHON__.jsobject2pyobject({1:'one', 2:'two', 3:'three', 4:{'big_bad_wolf': 1}})
  }

Then do your regular stuff.   The above line translates the jsobject to its python equivalent, and adds in the __repr__ functions, etc, that brython needs.

Note:  You will need to pull the most recent code from the repo, since I had to make some adjustments for this to work.

Billy

**Comment by JamesHutchison** [comment]
It works but not in the way you are expecting:

```
<script>
do_list = function(){
    return {1:'one', 2:'two', 3:'three', 4:{ 'big_bad_wolf':1 }}
}
</script>
<script type="text/python">
from browser import window
from javascript import JSObject
dl = JSObject(window.do_list())
print(dl[1])
print(dl[4]['big_bad_wolf'])
</script>
```

This issue really is that JSObject(some object) becomes a wrapper for an object instead of a dict object. This is because there aren't actually dictionaries in javascript and the JSObject wrapper lets you interface with the javascript object but it doesn't actually convert the object.

How would you go about converting this to a dict anyways?

**Comment by cforger** [comment]
Let me pull and have a look..

**Comment by cforger** [comment]
Ah, I think I see John's problem. When I pull the latest repo, use Billy's prefix on the return, and look at the dict, I get this:

{'1': 'one', '2': 'two', '3': 'three', '4': {'big_bad_wolf': 1}}

Notice my ints were converted to strings. I know JS does this from time to time as you filter. This means I can't access dict[1] as it doesn't exist.  dict['1'] exists tho.

If we back up for a moment - I wonder if this isn't just a simple matter of a recursive function at line 304 of py_dict.js? It's working fine for a single layer dict - It just needs to check each element in the array it processes, and if it's another Object Literal, call itself again to process it into a proper python dict.  I'd give this a try myself, but I'm still unsure of 90% of Brython's JS internals, so I'm not even sure where to start.

If I disassembled this JS Object Literal and fed it to Brython individually as single dicts, I feel it could recreate it into a proper dict (I should check that). I may have to do that in JavaScript to preprocess it into what I want. (Question: Creating a Brython dict fron scratch inside of JS - Is there an example someplace? I could browse the code for a while until I find it) 

Or am I missing a bigger picture here where the object needs to be accessible from JS and/or Brython? For instance, what happens if that object is modified in JS? Will it process on the fly the object for Brython so it stays updated? I still have a fuzzy notion of how things work on both sides of the fence. 

In my current case, this object will never go back into Javascript - I will extract it into bits, and feed those bits of the dict back to various JS routines for screen draws. 

Ultimately - I'd like to see a JS Object Literal become a Brython dictionary automatically. I shouldn't have to call dict() on the JSObject to get the dict, but that may be a wish-list item.

**Comment by JamesHutchison** [comment]
`JSObject` is used to interface with the javascript object. It's not to be confused with an actual dict. Converting it to a Brython dictionary automatically would either be destructive to the original object (which might break things) or it would force you to always interact with a copy, meaning you couldn't do anything meaningful with in a 3rd party library. You can also emulate the interface of a dict without actually becoming a dict, which is what it should already be doing, but I wouldn't be surprised if there are some bugs to iron out. Check out `$JSObjectDict`.

Converting from Javascript -> Python, this _should_ be fairly standardized without the datastructure checking for a special case. I'd rather not add additional logic to the init function. If a JSObject wants to become a Python object, then that really should be a function of the JSObject (i.e. `to_dict()`). Unfortunately, if I remember right, having a dict modify the underlying javascript object is entrenched behavior that can't be easily removed without breaking Brython.

**Comment by cforger** [comment]
Ah, interesting.

As we know, the dict is the powerhouse of Python, basically controlling object access. 

Tell em this - When Brython uses a Dict internally for class structure, etc. is it a special case "Brython Only" dict, or is it $JSObjectDict and thus compatible/limited ? Is that choice in case JS needs to call something in Brython?

 I understand that JS doesn't have a dict, so ultimately it's a new structure, but that's the same with CPython, as C doesn't have a dict either.

**Comment by earney** [comment]
I believe Brython uses $JSObjectDict for class structure. It is used for speed/performance improvements.   I wonder if the new dict implementation is fast enough (and implemented correctly enough) to replace this?

**Comment by cforger** [comment]
Ah,

 Well as I try and code a fix for this, I keep running into one JavaScript fun bit : 
 
{ 1: "one" } is indistinguishable from { '1': "one" }

they are the same thing in JavaScript. In an array, if I access via a for loop (list[0], list[1] , etc) I can keep the list true and outputting numbers. 

Otherwise I can't seem to find a way to keep an integer an integer in the object literal.

I'm low on time for this type of fun, so I'm just going to have to adjust my code to not care either. 

I'll post the Brython code to recurse through a Object Literal shortly - In the end it generates the same code I expect as return __BRYTHON__.jsobject2pyobject() does, but it allows you to make the change in Brython instead of JavaScript.

**Comment by cforger** [comment]
This is what I'm doing to cleanse my dict without modifying the output of JavaScript. It's using a slightly more complex output from do_list:
{1:"one", 2:'two', 3:'three', 4:{ 'big_bad_wolf':1, 2:{'waybill_for_bricks': 2}}}


from browser import window
from javascript import JSObject

console = window.console

def recursive_dict_copy(dict_to_copy):
  new_dict = {}

  # We can't do dict_to_copy.items(), because we don't have items() for a JSObject.
  # We also can't just pull the type(dict_to_copy[key]) as it won't return into a variable for
  # "<JSObject wraps [object Object]>", it only will print it to screen. You can't even load it into a var


  for key in dir(dict_to_copy):

    # This dosen't work. It's blank for <JSObject wraps [object Object]> types.
    #txt = "key: {} value: {}".format(key, dict_to_copy[key])
    #print("txt is ", txt)

    value = dict_to_copy[key]

    # Messy, but I don't know how to check for native python types in Brython
    if isinstance(value, str) or isinstance(value, int) or isinstance(value, float) or isinstance(value, list) or isinstance(value, dict) or isinstance(value, tuple) or isinstance(value, set):
      #print("Python Obj")
      new_dict[key] = value
    else:
      #print("JS Obj")
      new_dict[key] = recursive_dict_copy(value)

  return new_dict

js_dict = window.do_list()

new_dict = recursive_dict_copy(js_dict)
print("new_dict is ", new_dict)


Running a JSObject that I know is a dict through this gives me what I want. 

Notice that when the value is an integer, it stays an integer. That's due to the 'dir' function returning ints as strings. 

If dir didn't do that, or if I could iter over a JSObject somehow in Python, we may not have that problem - However, I couldn't iter over the Object Literal in JavaScript without it converting the keys to strings. 

The last trick would be for me to pass a msgpck or json encoded string to Brython, allowing this to happen inside of Brython to avoid the conversion.

**Comment by earney** [comment]
instead of

if isinstance(value, str) or isinstance(value, int) or
isinstance(value, float) or isinstance(value, list) or
isinstance(value, dict) or isinstance(value, tuple) or
isinstance(value, set):

you could do if isinstance(value, [str, int, float, list, dict, tuple, set]):

you also state:

"Messy, but I don't know how to check for native python types in Brython"

doesn't isinstance do this for you?

**Comment by cforger** [comment]
I was thinking of a nice:

isinstance(value, PyObject) 

sort of the reverse of a JSObject. then again I could just test if it's not a JSObject

And yes, I should throw the types in list, thanks.

**Comment by earney** [comment]
most "Brython" objects have a $native attribute (or a __class__ attribute).
But checking to see if it is a JSObject is probably the best procedure, the
more I think of it.

**Comment by cforger** [comment]
Is there a way to access the $native property in Brython? If I could get to the raw JSObject's data in Brython I may be able to do what I want. I couldn't access via OBJ.js

**Comment by earney** [comment]
There probably is a way,  Pierre would know..   I forgot you were trying to
do this via python and not javascript..

**Comment by cforger** [comment]
This is messier than I thought - I do have my code recursing through and rebuilding the dict for me, but when I try and print a complex (say 5 nests) dict, it bombs the print function, and starts showing JavaScript code in the print.. when I print the same dict using console.log, it displays it properly.

**Comment by cforger** [comment]
..where is this new dict implementation you speak of? I'm interested in trying anything different.

**Comment by cforger** [comment]
..and last update for a bit - I can't do it from the Brython side (and side note, bytes is missing a lot of it's Python attributes like .join, etc).

Billy, I'm using your __BRYTHON__.jsobject2pyobject() wrapper, and have hacked up my JS libs to only return data wrapped like that.

Is it difficult to make that call available in the standard repo?

**Comment by earney** [comment]
The jsobject2pyobject is already available in the standard brython repo (on
github).  I pushed it there last night, as can be seen here
https://github.com/brython-dev/brython/commit/817c64c4da71ff5980dc23c84c92eb2b0c82c8a2

**Comment by JamesHutchison** [comment]
The new dict implementation was already merged a couple weeks ago. The old implementation had a dict interface but it was really two lists (keys, values). When you wanted to look up a key it would do linear search. There might still be code that is dependent on the old implementation.

**Comment by earney** [comment]
There shouldn't be any code dependent on the old dict implementation.
Pierre and I removed all references to $keys and $values,etc.

I did make some adjustments to Jame's implementation to get it working with
Brython, and I  also added some objects for quick lookups with the key is a
integer or a string.

**Comment by cforger** [comment]
Great, I'll be back to revisit this once I have more time in Feb - I see it's not a simple answer, and perhaps we can all muse on it then and see if a course of action appears. 

Thanks for the help.

**Comment by earney** [comment]
I'd like to see what Pierre thinks about this discussion.   I personally
believe the simplest implementation is the one we should strive for.
Pierre has gained quite a bit of knowledge putting together the current
implementation, so he might have some reasons why he did it like he did.

Billy

**Comment by PierreQuentel** [comment]
Javascript "associative arrays" look superficially like Python dictionaries, but they don't work the same at all. __All keys are strings__, but Javascript won't complain if you set a value to a key that is __not__ a string : it will silently convert it to a string. If you define an object with a literal such as 

```javascript
x = {a:1}
```

it will create an object with the key "a" (the string "a"), and not (as Python would do) associate the object `a` (if it is hashable) to the value `1`

For instance, in the Javascript console :

```javascript
a = 1
x = {a:6}
x[1]
>>> undefined
x[a]
>>> undefined
x['a']
>>> 6
```

or :

```javascript
y = {1: 'a', '1': 'b'}
y[1]
>>> 'b'
y['1']
>>> 'b'
```

If you add a key/value pair with `x[key]=value`, `key` can be of any type, but it will first be transformed into its string reprensentation by calling its method `toString()`, an it is this string that will be associated to the value

```javascript
a = {1:2}
b = {3:4}
y = {}
y[a]=5
y[b]=6
y[a]
>>> 6
```

This is because the string reprentation of objects `a` and `b` is the same : the string `"[object Object]"`

Because they are so different, it was not possible to implement Python dictionaries as "simple" Javascript objects.

Now, what can you do with objects defined in a Javascript program in a Brython program ? First, the Brython program doesn't know the source code of this Javascript program, it can only access the objects that this JS program adds to the global JS namespace (attributes of `window`). So if the Javascript program defines the object

```javascript
x = { 1: "one" }
```

Brython accesses it with `window.x`, which is an instance of JSObject wrapping the Javascript object `{1:"one"}`, which actually has one key, the string `"1"`, __not__ the integer `1`

Even if it was possible to get access to the Javascript source code, Brython would have to parse it, find where "x" is defined, and realise that the key is written without quotes... That's too much to ask. And it wouldn't solve the problem when key/value pairs are defined with `obj[key]=value`

So we are limited to building a Python dictionary with only string keys. Currently this is done with 

```python
python_x = dict(js_x)
```

As Christopher reports in the first post, there is bug when a value is itself a JS object. It can be fixed, but seeing this discussion I wonder if using the built-in `dict` is the best solution : it gives the impression that `python_x` and `js_x` are more or less the same object. 

It would probably be better to raise an exception when passing an instance of JSObject to `dict()`, and to add a method `to_dict()` to instances of JSObject to produce a "dict representation" of the object

With this method, when we get a reference to a Javascript object by `window.x` :
- if `x` is a Javascript string, number, boolean or array, `window.x` is a Python string, int or float, boolean or list
- if `x` is another Javascript object than an array, `window.x` is an instance of JSObject, and `window.x.to_dict()` is a Python dictionary "looking like" the Javascript object `x`, with all the restrictions above

I have pushed an implementation of `JSObject.to_dict()` that works for all the examples of nested Javascript "associative arrays" in this thread

Is this solution ok for you guys, or do you have other ideas ?

**Comment by earney** [comment]
This is quite complicated!  I believe it is best to have someone explicitly
call a function (to_dict) than to just convert an javascript object
automatically.

**Comment by JamesHutchison** [comment]
maybe `to_dict` isn't a good name because only some objects make sense as a dict. `to_python` might be more appropriate.

Is this the desired flow to convert from javascript and back?

```
from javascript import JSObject

my_dict = window.x.to_python()
my_dict['foo'] = ['bar', 'shoe']
window.x = JSObject(my_dict)
```

I'm not sure if the assignment is working correctly. When I try it I see an exception in the console

**Comment by cforger** [comment]
I appreciate the thought put into this - I agree about the difficulty with the JS Object Literal / Associative Array being close, but not quite, a Python dict. The whole ints are strings thing in JS makes me sad, but it was a simple scripting language built in 10 days, so it's got some serious problems - It's why I like working in Brython, and will choose it any time i can over JavaScript.

For me, my dict issue was due to datacom work, where my msgpack library was in JavaScript, not Python (as Brython is missing a lot of low-level stuff in Bytes, float, etc for handling all the types that come through).  That issue can be approached from a few angles: Create a special msgpack in JS for Brython, create a msgpack in Brython for Brython, etc. I may do either, both, or none in the near future, depending on time.
 
What is more interesting is the general concept of the Brython dictionary. How close to a real Py dict can we make it without clobbering speed in the browser? The "every key is a string" current status is not the end of the world, but it will cause issues for larger codebases where "1" != 1, or you want to store things in the dict that don't like being a string.

**Comment by PierreQuentel** [comment]
Christopher,

My post was probably too long... Dictionaries in Brython are Python dictionaries, they supports all hashable types as keys. In a Brython script :

```python
a = {1:'int', '1':'str'}
a[1]
>>> 'int'
a['1']
>>> 'str'
```

It is Javascript that only supports strings as keys ; when you convert a JS associative array with `to_dict()`, you get a Python dictionary with the same keys as the JS object, ie strings

(Javascript program)

```javascript
a = {1: 'int', '1': 'str'}
```

(Brython program)

```python
py_a = window.a.to_dict()
py_a
>>> {'1': 'int'}
```

**Comment by cforger** [comment]
Ah yes, it's clear now.  It makes me think that I need to bypass JS as much as I can in MsgPack to get a dict through without the int to string issue.

**Comment by earney** [comment]
I think we want to get as close to cpython dict as possible.  Even passing
All (or most) unittests for dicts.   I believe this is possible, speed
might suffer a bit on special cases, but we can cross that bridge later.. :)

**Comment by PierreQuentel** [comment]
James,

The section "Objects in Javascript programs" of the page "Using Javascript objects and libraries" in the documentation explains in which Python type a Javascript is converted when you get a reference to it as an attribute of `window`

The only type for which a conversion to a Python dictionary makes sense is `JSObject`. This is why I propose to add a method `to_dict()` to this type, instead of using the built-in `dict()` as is currently stated in the documentation.

Can you explain the error you get when you set an attribute to `window` ? This works for me :

Javascript
```javascript
x = {}

function show(obj){
    console.log(obj['foo'])
}
```

Brython

```python
from browser import window

my_dict = window.x.to_dict()
my_dict['foo'] = ['bar', 'shoe']
window.x = my_dict
window.show(window.x)
```

**Comment by earney** [comment]
As of the current code in the repo,  brython passes 25 of 41 of the
test_dict unittests   (11 fail, and 5 contain errors). Even though only 25
out of 41 pass with flying colors, that doesn't mean 40% really fail.  It
just means that 40% of the unit tests have one or more failures or errors,
where a test could be made up of dozens of sub tests.

 Most of the ones that contain errors or fail are special use cases, and
some of these are special exceptions that are not being raised properly.
My goal is to have Brython pass all (or most) of standard Cpython's unit
tests.  I'm not  sure how realistic that is, but I think it is a decent
goal to strive for.

On a brighter note,  is that brython is using python's unittest module to
do the unittests, so there could be some features in unittests we have not
implemented yet (maybe this is why certain custom exceptions are not being
raise or caught properly), so the number of failures may have nothing to do
with our dictionary implementation at all!  So in reality, our dict
implementation may only be failing in 5 tests, and 10 tests could be
failing because of some implementation issues dealing with the unittest
module (of course, this is just a guess).

Billy

**Comment by JamesHutchison** [comment]
Using the brython.info console, for window.x = "foo", in Chrome, I see this if I open the developer console:

```
 $B.exception  Error: eval() argument must be an expression {info: "Traceback (most recent call last):↵  module exec-121 line 1↵    window.x = "foo"", message: "eval() argument must be an expression", args: "eval() argument must be an expression", __name__: "SyntaxError", __class__: Object…}
py_builtin_functions.js:2096 info Traceback (most recent call last):
  module exec-121 line 1
    window.x = "foo"
py_builtin_functions.js:2096 message eval() argument must be an expression
py_builtin_functions.js:2096 args eval() argument must be an expression
py_builtin_functions.js:2096 __name__ SyntaxError
py_builtin_functions.js:2096 __class__ Object {__class__: Object, __name__: "SyntaxError", __mro__: Array[4], $factory: function}
py_builtin_functions.js:2096 py_error true
py_builtin_functions.js:2096 type SyntaxError
py_builtin_functions.js:2096 value eval() argument must be an expression
py_builtin_functions.js:2096 traceback Object {__class__: Object, tb_frame: Object, tb_lineno: 1, tb_lasti: "window.x = "foo"", tb_next: Object}
py_builtin_functions.js:2097 line info 1,exec-121
py_builtin_functions.js:2098 Traceback (most recent call last):
  module exec-121 line 1
    window.x = "foo"
```



One thing that I must stress is that we really do have to worry about performance for the basic datastructures, because they are used liberally in Python. Dicts in particular are the staple of Python so it's important that we have elegant, high-performance solutions.

> Most of the ones that contain errors or fail are special use cases, and
> some of these are special exceptions that are not being raised properly.

Can you give an example? The dict logic needs to be very trim.

**Comment by earney** [comment]
Here's an example that functions properly, but doesn't raise a CustomException in the unittest module like it should:

```
class CustomException(Exception):
            pass

class BadDictKey:
            def __hash__(self):
                return hash(self.__class__)

            def __eq__(self, other):
                if isinstance(other, self.__class__):
                    raise CustomException
                return other
if 1:
        d = {}
        x1 = BadDictKey()
        x2 = BadDictKey()
        d[x1] = 1
        print('set d[x2] = 2')
        
        d[x2] = 2
        print('got here')
```

and produces this output:
```
set d[x2] = 2
Traceback (most recent call last):
  module lambda99 line 2
    return run(False)
  module exec-178 line 10
    raise CustomException
CustomException: BaseException
```


This example is from test_dict.py,  test_bad_key function/test. and produces the following error in brython when ran as part of a unittest.:

```
ft1.1: <class 'AssertionError'>
CustomException not raised
```

As you can see the code when ran outside of the unittest module produces the correct result, but doesn't  produce the correct result (raise CustomException) when it is part of the unittest module.

**Comment by earney** [comment]
I think the current dict implementation is pretty good.  Improvements are
possible and probably could be done on the this implementation unless some
radical new approach is conceived

**Comment by PierreQuentel** [comment]
James,

I have the same error message in the browser console, but no exception is raised in Brython interactive interpreter (console.html). 

It's the interactive interpreter that tries to evaluate the code `a = 5` ; if the code is an expression, the name `_` is set to the value of this expression, as in CPython console. 

To test if the code is an expression, the interactive interpreter tries an `eval()` on the code ; if it fails, an error is printed on the interactive console, but this exception is caught and the interpreter runs the code with `exec()`

Maybe caught exceptions could be handled in a way that they don't print anything in the browser console. But what really counts is the exceptions reported in the interpreter

**Comment by PierreQuentel** [comment]
With the method `to_dict()` implemented for JSObjects I think we can close the issue ; if the other problems raised in this discussion deserve it, feel free to open a new issue

**Comment by baccrog** [comment]
I think this issue is affecting me when trying to interact with a third-party library (Highcharts) -- see issue #175.

**Comment by roger-** [comment]
I think this issue is affecting me when trying to interact with a third-party library (Highcharts) -- see issue #175.
