### ISSUE TITLE
Module.__package__ returns incorrect value

### ISSUE THREAD

**Issue by lordmauve** [brython-dev/brython#1095]
Brython doesn't assign the correct name of the package to ``module.__package__`` for packages themselves. Only modules and submodules of packages are correct.

CPython 3.7.2:

```
$ python3.7
Python 3.7.2 (default, Mar  7 2019, 20:11:07) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import unittest.mock
>>> unittest.__package__       
'unittest'
>>> unittest.mock.__package__
'unittest'
```

Brython 3.7.1:
```
Brython 3.7.1 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
>>> import unittest.mock
>>> unittest.__package__
''
>>> unittest.mock.__package__
'unittest'
```

**Comment by PierreQuentel** [comment]
@lordmauve  Thanks for the report !

This was probably a bug in the console program in version 3.7.1, because the result is correct in the [editor](https://brython.info/tests/editor.html) at brython.info.

The changes made to this program seem to have fixed the bug, the console now prints `'unittest'` in the current development version ; can you confirm ?
