### ISSUE TITLE
3.7.0 to 3.7.1 Javascript Error

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#1096]
I have just attempted upgrading from 3.7.0 to 3.7.1 (to fix some incorrect behavior with comparing floats and None) and I am seeing the following exception in the browser:

Uncaught TypeError: Cannot read property 'push' of undefined   (py2js.js:9696)
    at Object.$B.run_script 
    at $B.parser._run_scripts (py2js.js:9844)
    at $B.parser.brython (py2js.js:9632)
    at Object.initBrython [as init] (bs.js:386)
    at window.onload (node22.codenvy.io/:163)

The error occurs at:

`    $B.tasks.push(["execute", script])
`

I have made no changes to the way I use Brython on my website and the method of loading Brython scripts still seems to be identical to the method used on the Brython editor demo. 

I apologize for not spending more time trying to understand what has changed in going from 3.7.0 to 3.7.1, so I am hoping that someone will instantly recognize the issue and point me in the right direction. Thank you!

**Comment by PierreQuentel** [comment]
Bonjour Eric,

Your page probably loads the individual scripts (__brython_builtins.js__ etc.) instead of __brython.js__. Since version 3.7.0 I have remove some parts of __py2js.js__ and put them in another script, __loaders.js__, where the object `$B.tasks` is defined. If you load this script just after __py2js.js__ it should fix the issue.

**Comment by tiggerntatie** [comment]
Thank you so much: that was it. I failed to find the addition of loaders.js in Brython editor demo. All is well again.
