### ISSUE TITLE
Suggestion: Brython should default to SessionStorage instead of LocalStorage

### ISSUE THREAD

**Issue by serge-stroobandt** [brython-dev/brython#111]
NB: This enhancement request refers to the following http://brython.info unavailability report: https://bitbucket.org/olemis/brython/issue/309/wwwbrythoninfo-inaccessable-due-to

I would like to make a few suggestions:

1. The website http://brython.info should fall back to showing a plain HTML message for unsuspecting visitors who are blocking LocalStorage. Right now they are confronted with a blank page.
2. Would it not be more friendly (or should I say ethical?) to have Brython using SessionStorage by default instead of LocalStorage? SessionStorage does not persist after the browser is closed, whereas LocalStorage does. LocalStorage could be made optional for those of us who really need it. See also: https://en.wikipedia.org/wiki/Web_storage#Local_and_session_storage
3. With brython.js using LocalStorage by default, one could argue that a site owner is not complying with the *EU Directive on Privacy and Electronic Communications* if he or she does not post a warning message about Localstorage usage. See: https://en.wikipedia.org/wiki/Directive_on_Privacy_and_Electronic_Communications#Cookies
I admit, the directive is vaguely written in typical EU-style, but nevertheless it should be of concern to us. SessionStorage would definitely free us of any such obligations.

**Comment by serge-stroobandt** [comment]
Here is the notice I am currently using on [my website](http://hamwaves.com/lpda/en/index.html):
> [Brython](http://www.brython.info)-based calculators require [`LocalStorage`](https://en.wikipedia.org/wiki/Web_storage#Local_and_session_storage)-access to work.
> Please, make sure nor your browser nor any browser add-on is blocking [`LocalStorage`](https://en.wikipedia.org/wiki/Web_storage#Local_and_session_storage) for this page.
> Sorry for the inconvenience.
> An [enhancement request](https://github.com/brython-dev/brython/issues/111) suggesting a preference for [`SessionStorage`](https://en.wikipedia.org/wiki/Web_storage#Local_and_session_storage) was [filed with the Brython developers](https://github.com/brython-dev/brython/issues/111).

**Comment by JamesHutchison** [comment]
Brython has tools for accessing both LocalStorage and SessionStorage

The error you are seeing is Brython simply making a reference to LocalStorage so that it can be accessed in the local_storage.py script. It's not actually storing or reading anything unless you make a script that does so.

I consider this a flaw in your browser plugin. Nothing is being altered in LocalStorage, although the site does use LocalStorage for testing.

**Comment by serge-stroobandt** [comment]
@JamesHutchison With all due respect, but I consider it a serious flaw in Brython if you are telling me that Brython does not essentially require LocalStorage, but nevertheless blanks out so spectacularly.
In Firefox alone, 148634 users are using [Self-Destructing Cookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/); being just one of the many cookie blocking add-ons out there.
LocalStorage blocking is a common reality and Brython should fail more graciously, or even better, not fail at all. Privacy-conscious web users are now faced with a clueless, white, empty page when visiting <http://brython.info>.
Using SessionStorage or not testing for storage when not needed, are feasible, graceful solutions that would benefit the accessibility of the Brython home page and other Brython-based pages.
The strictly European legal aspect is also something which should not be taken halfheartedly. In case of any doubt, ask Microsoft about their fine.

**Comment by JamesHutchison** [comment]
We could try sticking that local storage reference into a try block and swap out the reference to throw an exception if it's not available. We could then have the editor catch that exception and fall bakc to SessionStorage. That's the most that can be done though. You can't simply replace LocalStorage with SessionStorage; that would break things in an unpredictable manner. Blocking LocalStorage is probably going to break things too, unless the only thing that use it are AJAX call-backs from advertisers.

Thing is, I don't think it's good policy to chase issues people have because of poorly written plugins. Your plugin could have replaced LocalStorage with an object that has the same interface and nothing would break, but instead it appears to replace LocalStorage with a function that just raises an exception. That is the plugin's fault. Browsers that do not support LocalStorage fail silently until it cannot proceed any further.

As an example, open up firefox without your plugin, go to `about:config`, and change `dom.storage.enabled` to False. Visit brython.info and note that it functions. Go to the console and note that it also functions. Then click the Editor tab and note that it fails. This is because that is the first tab to use LocalStorage (it uses LocalStorage to save the contents of text editor).

**Comment by serge-stroobandt** [comment]
Dear James,
I understand your frustration.
However, I do I like both of your suggestions; the fallback to `SessionStorage` as well as the object interface improvement for the Self-Destructing Cookies add-on.
I will [write the add-on developer](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/) immediately, with a reference to this conversation.
In the mean time, getting a `SessionStorage` fallback will certainly contribute to the accessibility and broader adoption of Brython. Thanks!

**Comment by serge-stroobandt** [comment]
Here is the e-mail that I wrote:
> Dear Ove,
> 
> A Brython (http://brython.info/) developer made an interesting improvement suggestion for the `LocalStorage` blocking function of Self-Destructing Cookies.
> 
> Instead of raising an exception, it would be better to replace `LocalStorage` with an object that has the same interface, but does nothing (or perhaps that uses `SessionStorage` instead?). Doing so, many web pages would fail less spectacularly and still maintain some basic functionality.
> 
> Moreover, this behaviour would also closely resemble the behaviour of setting `dom.storage.enabled` to `False` in `about:config`.
> 
> More details about what led up to this conclusion can be found here:
> `https://github.com/brython-dev/brython/issues/111`
> 
> Thank you in advance for sharing your opinion about this suggestion.
> 
> Kind regards,
> 
> Serge

**Comment by PierreQuentel** [comment]
I think we can close this issue. Please open it again if you think it necessary.
