### ISSUE TITLE
Two input() with substituted sys.stdin throws an error

### ISSUE THREAD

**Issue by maximseshuk** [brython-dev/brython#1127]
Hey! I create an online tutorial, and I get an error when I try to execute this code:

```python
import io
import sys

sys.stdin = io.StringIO("test\ntest2");

print(input())
print(input())
```

Error:
```
test
Traceback (most recent call last):
  File https://brython.info/tests/editor.py, line 112, in run
    exec(src, ns)
  File <string>, line 7, in <module>
  File https://brython.info/src/Lib/_io, line 1952, in readline
    raise ValueError("read from closed file")
ValueError: read from closed file
<completed in  74.00 ms>
```

Thx for us help!

**Comment by PierreQuentel** [comment]
Здравствуйте Максим !

Thanks for reporting this. The bug in Brython was to allow redirecting `sys.stdin` to replace the default implementation of `input()` : this won't work, because `input()` has to be a blocking function (the script must hang until the user has finished entering the value), and such functions can't be defined in Javascript.

To make this explicit, setting `sys.stdin` now raises an exception saying that it's read-only, and the documentation page "Syntax, keywords and built-in functions" explains why, with a mention of the example of a customized `input()` function in the gallery.
