### ISSUE TITLE
'using indexedDB for stdlib modules cache' message always appears in the Python console

### ISSUE THREAD

**Issue by ryanpcmcquen** [brython-dev/brython#1128]
Is there a way to get rid of it?

**Comment by ryanpcmcquen** [comment]
Specifically, I run a Python REPL using Brython, and having that message always displaying is confusing:

![Screen Shot 2019-06-03 at 2 53 40 PM](https://user-images.githubusercontent.com/772937/58837141-7bbb1380-860f-11e9-8905-551a03438b9e.png)

https://ryanpcmcquen.org/PyPlay/

**Comment by PierreQuentel** [comment]
I think it's important to have the information that indexedDB cache is used. The cache improves module loading time a lot but can also be a cause of bugs, and in case of a strange bug it's better to know that it happened in the context of a cache.

Looking at your code in PyPlay.js I see that you redefine `window.console.log()` to print to the element outputNode. I suppose that it's because you want `print()` statements to write to this element. If you put the line `brython()` _before_ the block

```javascript
window.console.log = message => {
    outputNode.innerHTML += message + "<br>"
}
```

instead of _after_ it, I think the message will still show in the browser console, but not in the output zone.

**Comment by ryanpcmcquen** [comment]
@PierreQuentel, thank you for the quick response, unfortunately, that did not seem to help ... is there any other way to filter this out?

![indexeddb_message](https://user-images.githubusercontent.com/772937/58910774-4116b100-86cb-11e9-8ac9-c48073c18fe3.gif)

Maybe just a config option to suppress the warning?

**Comment by ryanpcmcquen** [comment]
Conversely, you could use `console.info` for that tidbit ...

**Comment by cool-RR** [comment]
I would also like a way to filter this message. Every library wants to put a message in the console, and eventually you end up blind to messages you actually want to see.

**Comment by PierreQuentel** [comment]
In the commit above, the message is printed only if debug level is >=2. Is this ok ?

**Comment by cool-RR** [comment]
What's the default debug level? And how do I find it and change it?

**Comment by PierreQuentel** [comment]
The default value is 0. You can change it by passing the argument to `brython()`, as explained in this [documentation page](https://www.brython.info/static_doc/en/options.html).

**Comment by cool-RR** [comment]
Sounds good. I'd close the issue, this is the ideal solution.

**Comment by PierreQuentel** [comment]
Cool, thanks !
