### ISSUE TITLE
`with` statement exits every generator iteration

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#1143]
Given the following test:

```
class A(object):
    def __enter__(self):
        print('enter')
    def __exit__(self, *pa, **ka):
        print('exit')

def test_gen():
    print('test starts')
    with A():
        print(1)
        yield
        print(2)
        yield
    return

gen = test_gen()
next(gen)
next(gen)
```

The output should be:
```
test starts
enter
1
2
exit
```

But it seems to be:
```
test starts
enter
1
exit
enter
2
exit
```

**Comment by PierreQuentel** [comment]
@mircea3 
I have been working on this issue and can't find a solution for the moment. The problem is, when is the `__exit__` method executed ? It must be some time _after_ `yield`, but it's not _just after_, as this code in CPython shows: 
```python
class A(object):

    counter = 0

    def __enter__(self):
        print('enter')
    def __exit__(self, *pa, **ka):
        A.counter += 1
        print('exit', A.counter)

def test_gen():
    print('test starts')
    with A():
        yield 1

gen = test_gen()
y = next(gen)
print("no exit !")
print("end of program")
```

The output is
```
test starts
enter
no exit !
end of program
exit 1
```

With a second call to this generator inside a function: 
```python
class A(object):

    counter = 0

    def __enter__(self):
        print('enter')
    def __exit__(self, *pa, **ka):
        A.counter += 1
        print('exit', A.counter)

def test_gen():
    print('test starts')
    with A():
        yield 1

gen = test_gen()
y = next(gen)
print("no exit !")
print("end of program")

def g():
    gen2 = test_gen()
    next(gen2)
    print("end of function g")

g()
```
the output is
```
test starts
enter
no exit !
end of program
test starts
enter
end of function g
exit 1
exit 2
```

It looks as if the interpreter manages a stack of unclosed context managers, and closes them at the end of the program, but I haven't found documentation for this specific case.

**Comment by andy31lewis** [comment]
> The problem is, when is the __exit__ method executed ?
Because the generator saves state, surely the `__exit__` will only be called when the generator is exhausted (ie `StopIteration` is raised) or destroyed (eg using `del`, or at the end of the program).

These can be seen, in your first example, by making the last part

```python
gen = test_gen()
y = next(gen)
print("no exit !")
y = next(gen)
print("end of program")
```
or
```python
gen = test_gen()
y = next(gen)
print("no exit !")
del gen
print("end of program")
```
In either case, `exit 1` appears in the output.
Hope that helps,
Andy

**Comment by PierreQuentel** [comment]
Thank you Andy, that helps a lot ! The only thing left to do is to implement it in Brython...

**Comment by mircea3** [comment]
Also, to be more complete, it might be a good idea to add an extra test *in the middle*, besides at the end. For example:

```
class A(object):
    def __enter__(self):
        print('enter')
    def __exit__(self, *pa, **ka):
        print('exit')

def test_gen():
    print('test starts')
    with A():
        print(1)
        yield
        print(2)
        yield
    print(4)
    yield
    with A():
        print(5)
        yield
        print(6)
        yield

list(test_gen())
```

CPython output:
```
test starts
enter
1
2
exit
4
enter
5
6
exit
```

**Comment by PierreQuentel** [comment]
Closed at last ! It was not an easy one...

The difficult part is that `yield x` is translated to something like `return [x, 0]` ; when the `yield` is inside a context manager, the translation has the form

```javascript
<enter context manager>
try{
    ...
    return [x, 0]
}finally{
    <exit context manager>
}
```

which exits the context manager _before_ returning the value.

I had to set a flag before `return [x, 0]` to avoid running the `finally` section:

```javascript
<enter context manager>
try{
    ...
    _yield = true
    return [x, 0]
}finally{
    if(! yield){
        <exit context manager>
    }
}
```

I also changed what happens when exiting an execution frame (from a function or the main program for instance). In function `$leave_frame()` in __py_utils.js__, all the generators in the current namespace are inspected; if they have context managers whose method `__exit__()` has not been called, then it is called.

The same check is also done with `del name` if the object referenced by `name` is a generator.

The positive side of this difficult fix is that is was possible; it shows that the management of execution frames and generators in Brython is good enough to handle such an advanced use case.

**Comment by mircea3** [comment]
Thank you, it is a big help. These combinations might not be very common in normal desktop programs, but it seems that generators are especially useful in the browser and it is a real advantage for them
to work nicely together with context managers. Your explanation helped *a lot* to decipher what was going on in the code, thank you!

There seems to be a minor problem. In the previous example I posted, if you replace the `yield` statements with an equivalent loop, `__exit__` and the last `yield` are called in the wrong order. In the following, try changing the variable `AS_LOOP` to `True`:

```
AS_LOOP = False

class A(object):
    def __enter__(self):
        print('enter')
    def __exit__(self, *pa, **ka):
        print('exit')

def test_gen():
    print('test starts')
    with A():
        if AS_LOOP:
            for i in range(1, 3):
                print(i)
                yield
        else:
            print(1)
            yield
            print(2)
            yield
    print(3)
    yield
    with A():
        if AS_LOOP:
            for i in range(4, 6):
                print(i)
                yield
        else:
            print(4)
            yield
            print(5)
            yield

list(test_gen())
```

**Comment by PierreQuentel** [comment]
The commit referenced above should give the correct result for this example. Thanks !

**Comment by mircea3** [comment]
This is a nice improvement, thank you. There is still another case which fails, but a single line seems to fix it.

In `test_generators.py`, introduce some yield return values:

```
def test_gen3():
    with A():
        if AS_LOOP:
            for i in range(1, 3):
                val = yield i # <= return value
        else:
            val = yield 1     # <= return value
            val = yield 2     # <= return value
    yield 3
    with A():
        if AS_LOOP:
            for i in range(4, 6):
                yield i
        else:
            yield 4
            yield 5
```

(The rest can remain the same, to test both with and without return values).

Now the test currently fails. But the following line seems to fix it:

```
py2js.js around line 483:

                 // value sent to the generator, if any
                 var set_yield = new $Node()
                 set_yield.is_set_yield_value = true
+                set_yield.after_yield = true
 
                 // the JS code will be set in py_utils.$B.make_node
                 js = $loop_num
```

The following version of `test_gen3()` would be even more exhaustive:

```
def test_gen3():
    with A():
        if AS_LOOP:
            for i in range(1, 3):
                val = yield i
                assert val == i+1
        else:
            val = yield 1
            assert val == 2
            val = yield 2
            assert val == 3
    yield 3
    with A():
        if AS_LOOP:
            for i in range(4, 6):
                yield i
        else:
            yield 4
            yield 5

def run_test_gen3():
    gen = test_gen3()
    value = next(gen)
    for ii in range(2):
        trace.append(value)
        value = gen.send(value+1)
    trace.append(value)
    for value in gen:
        trace.append(value)
    assert trace == ['enter A', 1, 2, 'exit A', 3, 'enter A', 4, 5, 'exit A']

AS_LOOP = False
trace = []
run_test_gen3()

AS_LOOP = True
trace = []
run_test_gen3()
```

**Comment by PierreQuentel** [comment]
Once again, many thanks for the report, and for the fix !
