### ISSUE TITLE
The re module

### ISSUE THREAD

**Issue by JamesHutchison** [brython-dev/brython#116]
The re module is a real pain. It takes over a second to load on a local machine and most of the utility of having a Python RegEx engine over a javascript RegEx engine is usually non-existent besides familiarity. I've tried making a JSON object after the file is processed and the file is just enormous.

We could add a RegExp class to the javascript module. This could be a nice wrapper for the javascript regex engine that automatically converts to python lists and such. As a short term solution, I don't see any reason not to do this. We could also have a second class that matches the python regex interface, although I can't decide what it would be named or what module it would live in.

We could also replace the existing python implementation with an asm.js compiled version from the original python C code. I have no idea if this could work, or how you would go about it, but the site regex101.com appears to be using an asm.js compiled pcre library for their python matching and it's blazing fast.

**Comment by PierreQuentel** [comment]
James,

We need the complete `re` module, because many modules of the standard distribution rely on it with the Python flavour of reg exp syntax, and because Python developers want a module that doesn't break their habits

The Brython distribution includes a module _jsre.js that was used in the early days, when the `re` module was not supported. You can still use it, it loads without delay and its interface is somewhere in between Python and Javascript

```javascript
import _jsre
x = _jsre.match('a(.*)b','askdhflqb')
print(x.groups())
>>> ('skdhflq',)
```

It is not documented and has not been edited for a very long time. 

Anyway, I am not sure it would be a good idea to provide an alternative module with a different re syntax, just because the standard module takes too long to load ; I'd rather look at ways to improve its loading time (it was already reduced recently)

Of course the best would be if the whole module was written in Javascript, with support of the full Python re syntax, but that's a very hard work. I'm not sure that pre-compiling the Python module is the solution, because most of the loading time is taken by the import of other modules, but it's worth a try. Another option would be to take an existing library (xregexp for instance) and edit it to support the Python syntax

**Comment by jsbueno** [comment]
On 25 January 2015 at 18:14, Pierre Quentel <notifications@github.com>
wrote:

> Anyway, I am not sure it would be a good idea to provide an alternative
> module with a different re syntax, just because the standard module takes
> too long to load ; I'd rather look at ways to improve its loading time (it
> was already reduced recently)


Actually - I thinnk on the long term, this will be true for a large class
of objects. As Brython approaches full Python compatibility more and more
wrapping is needed, and harder are the hits on performance  -

I think one thing that should come quite naturally on the long term is to
have a way to access "native" or very thinly wrapped javascript objects -
and maybe the namespace could be "javascript" module itself, or some other.

For example, besides the "re" module, we have the dictionaries. Even though
it has been enhanced, if all I want from a dict are key/values and none
other of Python's mapping ABCs, I could use a simple javascript object
which would be a lot faster.

In the same direction, at some point Brython will have to implement
Python's integers, with their unlimited precision - since that type will
have to feature emulation for all numeric features, the impact on
performance should be huge. But then, there could be a "javascript.int"
class that would expose plain javascript integers. (or thinly wrapped).

At this point, so, maybe javascript  "_jsre" could be exposed as "
javascript.re" - or some other name space, that would allow some
standardization for this practice for other classes.

Regards,
   js
 -><-

**Comment by kikocorreoso** [comment]
> I think one thing that should come quite naturally on the long term is to
> have a way to access "native" or very thinly wrapped javascript objects -
> and maybe the namespace could be "javascript" module itself, or some other.

That's not a bad idea, a package with javascript alternative modules for some Python functionality. For simple and usual things it would be faster and lighter (in a custom *brython_dist.js*). For example, Decimals, statistics, fractions,..., and other number related modules are a pain to port and 99% of the times they are not very useful on a day to day basis. 

P.D.: Last days I was working in the *statistics* module introduced in CPython 3.4

**Comment by JamesHutchison** [comment]
My understanding is that the goal of Brython is to give developers the ability to write their web page logic in Python (with its helpful libaries) instead of javascript. I think once you start talking about things like integer and float precision you are stepping outside the target audience of the project, especially when you consider the cost/benefit of such a feature.

I agree with at least making an alias to _jsre as javascript.re, but I would want the functions to return a  MatchObject Python class (or similar), rather than a JSObject that has the same interface. It's a lot cleaner to interact with.

**Comment by jsbueno** [comment]
On 26 January 2015 at 21:39, JamesHutchison <notifications@github.com>
wrote:

> My understanding is that the goal of Brython is to give developers the
> ability to write their web page logic in Python (with its helpful libaries)
> instead of javascript. I think once you start talking about things like
> integer and float precision you are stepping outside the target audience of
> the project, especially when you consider the cost/benefit of such a
> feature.
>

Even when thinking on just this target audience, the principle of less
surprise dictates Brython should approach Python's behavior in all aspects.
I am developing day to day an app using Brython, and at the project state,
that demands testing each language feature I am using, and check if it
actually works.  Unlimited Integer precision, for example, although seldom
needed, is not a small part of Python's spec.

The project is fantastic, and it is well on track to have full Python 3
compliance on the language, if not library level. Staying short of full
dictionaries with arbitrary objects as keys, or unlimited numbers, or
string methods that don't escape regular expression markups in name of
performance for the regular objects would be foolish, and actually drive
people who like Python away.  Having "thin" objects for these in a separate
module, one can use to optimize performance, on the other hand is a major
plus. Just like "cython" is a superset of Python that allows extra markup
for native-code types, Brython can do that, but without the need for extra
syntax, for high performance "javascript dicts", "javascript ints",
"javascript regexps" and so on.

  js
 -><-

**Comment by mscuthbert** [comment]
Big plus for creating a javascript namespace with near native object speed performance. For code that needs to run under cPython and brython, what would be the best lightweight way of detecting this so that code can be forked to run under both? In my projects I use "if six.PY3:" a lot. It would be great to be able to use these hints to optimize out the most frequently called functions in my own projects.

**Comment by olemis** [comment]
See [this comment](https://github.com/brython-dev/brython/issues/188#issuecomment-129078116) about the priorities in the short-term . Optimizations will come later (... or in parallel , should we find contributors spending time in improving that aspect)
