### ISSUE TITLE
Typehints / intellisense for Brython?

### ISSUE THREAD

**Issue by AgarwalPragy** [brython-dev/brython#1162]
Developing in Brython makes your IDE throw all sorts of inspection warnings, since the IDE cannot find the imports.

**Steps to Fix:**
1. Stubs for Brython specific modules be created, and exposed via the brython package, so that they are accessible in the code as `from brython.browser import document`.
1. Allow imports via the brython package. That is, the following two imports should produce the same results when brython is loaded on the webpage.
    ```python3
    from browser import html
    ```
    
    ```python3
    from brython.browser import html
    ```

Everything else remains the same. These newly exposed modules simply provide the IDE with the definitions. Brython still uses its precompiled `brython.js` and `brython_stdlib.js` files to provide functionality for these imports.

**Comment by PierreQuentel** [comment]
@AgarwalPragy 
I have nothing against this idea, but I have never used an IDE and have no idea of how to achieve what you request. If someone wants to contribute a solution to this issue I will be pleased to include it.

**Comment by StnadardUsre** [comment]
I have made a basic stub file for this: https://pastebin.com/B7AzkAzx  It is far from comprehensive, but helps to get rid of most inspection warnings and enables basic auto completion, at least in PyCharm. Anyway, you can easily add missing stuff. Save the file as "browser.py" and put it next to your main script.

**Comment by gilch** [comment]
Maybe a .pyi file with type annotations would suffice? PyCharm, at least, seems to use those even if the corresponding .py file is absent. See [PEP 484](https://www.python.org/dev/peps/pep-0484/) for more information about the .pyi files. I'm also not sure if going through the `brython` package is necessary. It should be possible to have the PyPI package install multiple modules.

**Comment by PierreQuentel** [comment]
If this feature is included in Brython, it should not "get rid of most inspection warnings (...) at least in PyCharm", but of _all_ inspection warnings, on _all_ IDEs : if some names in a module raise a warning and others don't, I don't want to have to explain that it's because the Brython module is broken.

Providing a working solution means covering two different fields:

1. the names defined by the DOM specification

In the example provided by @StnadardUsre, all the names defined as attributes of `document` are included. Since they vary from a browser to the other, how to make sure that all the cases will be covered ?

If the attribute `style` of `document` is included, should all the attributes of `style` also be defined to avoid warnings ? Hopefully not, because that would make a very, very big module...

2. the names defined by Brython

This means the names defined in the browser package, but also other Brython-specific modules (`javascript`) should be covered. It means that each time a module is added or modified in the browser folder, the script browser.py should be updated, which means inspecting the names often defined in Python script, in Javascript programs, even in builtins_modules.js; it's not impossible, but not easy.

For the javascript module, I suppose that the IDE would require a javascript.py file ?

Moreover, some of the modules of the standard distribution that are written in Javascript (`array, math, random, unicodedata`, etc.). Sometimes names defined in the CPython version are not exactly the same as in the Brython version, how to manage this ?

**Comment by AgarwalPragy** [comment]
> If this feature is included in Brython, it should not "get rid of most inspection warnings (...) at least in PyCharm", but of _all_ inspection warnings, on _all_ IDEs : if some names in a module raise a warning and others don't, I don't want to have to explain that it's because the Brython module is broken.

Makes sense. In that case, we could start with unofficial support for now.
Here's an (incomplete) example: https://pastebin.com/ybSuqXhv
The biggest challenge in completing this would be taking care of all the undocumented things like `DOMNode.clone`, `DOMNode.focus`, `DOMNode.getSelectionRange` which aren't mentioned in the docs, but exist.

> Since they vary from a browser to the other, how to make sure that all the cases will be covered?
> If the attribute `style` of `document` is included, should all the attributes of `style` also be defined to avoid warnings? Hopefully not, because that would make a very, very big module...

We can document all that should be documented.
Things dependent on javascript specifications or browser implementations can be left out.
Things that Brython guarantees across all browsers must be included.

> It means that each time a module is added or modified in the browser folder, the script browser.py should be updated, which means inspecting the names often defined in Python script, in Javascript programs, even in builtins_modules.js; it's not impossible, but not easy.

The docs anyway need to be updated to include any new attributes/methods. Python docs are usually kept in sync with the code by making use of docstrings and Sphinx.

By keeping the stubs we envision here up to date with the implementation, we can also generate the docs automatically.
 
> Moreover, some of the modules of the standard distribution that are written in Javascript (`array, math, random, unicodedata`, etc.). Sometimes names defined in the CPython version are not exactly the same as in the Brython version, how to manage this?

Oh, that sounds troublesome. Are these differences documented anywhere?

**Comment by PierreQuentel** [comment]
I understand the need, but solving this issue requires a good knowledge of development tools. I can't keep it in the scope of the Brython project, so I am closing it with the tag "won't fix". Sorry about that ! If you want to create a specific project for this, I will try to help if I can.
