### ISSUE TITLE
returning False from function still causes form to submit

### ISSUE THREAD

**Issue by kveroneau** [brython-dev/brython#1169]
If I bind a Python function using document['myform'].bind('submit',mypyfunc) and then perform some logical tests on the form data and return False on failed validation, the form still submits to the server...  This makes Brython a bit useless for form validation on the client-side, I could change it to a button type, and perform the form submission manually, however binding onsubmit and using a standard submit button should work.  The return boolean from the binding function should fallthrough.

**Comment by PierreQuentel** [comment]
If you have a form like

```xml
<form id="test" action="/cgi-bin/get_test.py">
<input type="submit" value="ok">
</form>
```

and you use Javascript to validate the form with

```javascript
document.getElementById("test").addEventListener("submit",
    function(evt){
        return false
    }
)
```

the form will be sent despite the `return false` in the function.

To get the behaviour you expect, you need to change the form

```xml
<form id="test" action="/cgi-bin/get_test.py" onsubmit="return validate()">
<input type="submit" value="ok">
</form>
```

and the validation function
```javascript
function validate(evt){
    return false
}
```

You can also write the validation function in Brython, but since the `onsubmit`
handler expects only Javascript (which is a pity because the DOM is supposed to
be language-independant, but this is another topic...), you must put the
Brython function in this namespace using the object `browser.window`:

```python
from browser import window

def validate():
    return False

# put the function in the global Javascript namespace
window.validate = validate
```

Instead of binding the submit event inside the HTML tag, a better option IMO
is to use event binding, but instead of returning `False`, use the method
`preventDefault()` of event objects. So, keep the original form

```xml
<form id="test" action="/cgi-bin/get_test.py">
<input type="submit" value="ok">
</form>
```

and in Brython:

```python
from browser import bind

@bind("#test", "submit")
def validate(evt):
    if True:
        evt.preventDefault()
```

**Comment by kveroneau** [comment]
That worked, is this somewhere in the documentation where I may have missed it?  Also, thanks for pointing out the bind decorator, this is more Pythonic than using the document dict to perform the binding.  I ended up using the evt.preventDefault for anyone curious.

**Comment by PierreQuentel** [comment]
The `preventDefault()` method of event objects is not Brython-specific, it is described in the [DOM documentation](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault). I will have to add a form validation example in the gallery.

**Comment by PierreQuentel** [comment]
I close the issue, hoping that you have the information you need. If not, feel free to reopen it.

Merci !

**Comment by CookiePLMonster** [comment]
> I will have to add a form validation example in the gallery.

Has this ever happened? I don't see any examples utilizing forms at the moment.
