### ISSUE TITLE
toString method on classes seems to be ignored

### ISSUE THREAD

**Issue by alex** [brython-dev/brython#118]
Transcript from the online console:

```pycon
>>> class X(object):
...  def toString(): return "wat?"
... 
>>> X()
<X object>
>>> X().toString()
'[object Null]'
```

**Comment by jsbueno** [comment]
You are missing the "self" parameter in the toString method declaration - 
anyway, I can confirm the bug on the version currently running on the site:

>>> class X(object):
  def toString(self): 
     return "wat?"
  def othername(self):
     return "other"
>>> 
>>> a = X()
>>> a.toString()
'[object Null]'
>>> a.othername()
'other'
>>>

**Comment by kikocorreoso** [comment]
@alex 

Hi, the created object is stored here:

`__BRYTHON__.vars.__main__.a`

It is a js object and jsobjects have a method `toString()` so if you use that name for the method it will raise an error.

You can name your method `to_string`, `tostring` `Tostring`,  `ToString`,..., but no `toString`.

@PierreQuentel @earney Maybe this should raise an error or warning at traspile time for several 'reserved js words' in order to warn the user?

**Comment by PierreQuentel** [comment]
This is because in attribute resolution, Brython checks if the object has an attribute "toString", and all objects in Javascript have this attribute set. The solution was to put "toString" in the list of "forbidden" names, which transforms it internally into "$$toString"
