### ISSUE TITLE
Install location: data vs brython_data

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [brython-dev/brython#1180]
curious why 
```
pip install brython
```
deposits `brython.js` in `/usr/lib/python3.7/site-packages/data/`

perhaps `brython_data` would be more appropriate?

**Comment by PierreQuentel** [comment]
Thanks for mentioning this. I knew I was a complete idiot at setup.py ;-)

With the changes in release management ending at commit ed4cf70ffeec9cbae112a081b162f230d2479636, things should be a little cleaner. Instead of installing __`brython.py`__ and other scripts at the __`site-packages`__ level, all scripts are now inside the __`brython-3.8.0-py3.8.egg`__ directory, with a subdirectory __`data`__ holding the files installed by `python -m brython --install`.
