### ISSUE TITLE
Vue.js: browser.html: expose attribute name mapper

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [brython-dev/brython#1187]
1. see #1186 

2. `vue.js` likes crazy html attribute names:
https://vuejs.org/v2/guide/events.html

3. please expose attribute name generator:
https://github.com/brython-dev/brython/blob/master/www/src/builtin_modules.js#L225

4. so that the following convention 
`v_on_click` -> `v-on:click`
can be implemented:
```
from browser.html import BUTTON
button = BUTTON('hello-kitty', v_on_click='count++')
```
5. such than final html becomes:
```
<button v-on:click="count++">hello-kitty</button>
```

**Comment by PierreQuentel** [comment]
For this issue, as well as for #1186, you can use 
```python
button = BUTTON("hello-kitty", **{"v-on:click": "count++"})
```
Instead of the replacement of underscore by hyphen, which is questionable because it doesn't allow names with underscores as attribute names, it would probably be better to remove it, and mention the syntax above for attribute names that are not valid Python names. What do you think ?

**Comment by Andrei-Pozolotin** [comment]
re: `**{"v-on:click": "count++"}`
yes, already using this now, just feels ugly, and looking for a better way

**Comment by PierreQuentel** [comment]
I don't think it's so ugly and I will document it, but what do you mean by "exposing attribute name generator" ? Can you give an example of the API you would like for that ?

**Comment by Andrei-Pozolotin** [comment]
the api would be direct regex mapper:

`regex pattern` -> `regex replacement`

for example, for `v_on_click` -> `v-on:click`, which covers most `vue.js` directives:

```
<body onload="brython({ 
   debug : 1, 
   html_attr_mapper : {
      'v_([a-z]+)' : 'v-$1',
      'v_([a-z]+)_([a-z]+)' : 'v-$1:$2',
      'v_([a-z]+)_([a-z]+)_([a-z]+)' : 'v-$1:$2.$3'
   }
})">
```

**Comment by PierreQuentel** [comment]
I don't agree with this suggestion :
- it would mean adding a new parameter to the function `brython()`, just for one module (__`browser.html`__), and for a use case which is not so current and can be handled by the `**{}` syntax
- developers would have to use the _Javascript_ regular expression syntax, which is not the same as Python's ($1 instead of \1 for reference to matched groups)

Another solution would be to define a function `attribute_mapper` in module __`html`__, used to transform keyword parameters passed to the classes defined in this module. By default it would only replace underscores by hyphens, but it could be set to another function:

```python
import re
import browser.html

def vue_attr(attr):
    return re.sub("^v_(.*)_(.*)$", "v-\1:\2", attr)

browser.html.attribute_mapper = vue_attr

html.BUTTON(v_on_click="count++")
```

Would that be ok ?

**Comment by Andrei-Pozolotin** [comment]
re: `browser.html.attribute_mapper = vue_attr`
yes, this is a very good idea, thank you:

**Comment by PierreQuentel** [comment]
I think the commit above fixes the issue, it not feel free to reopen it.

Thanks for the report !

**Comment by Andrei-Pozolotin** [comment]
yes, that should fix it. please release? :-)
