### ISSUE TITLE
Releases after 3.7.2 break when using brython in a webworker via importScript

### ISSUE THREAD

**Issue by desean1625** [brython-dev/brython#1196]
I am using brython in a unique way allowing users to execute python code in a webworker via brython.

There are inputs and outputs to and from the python script and the main thread gets these messages. This allows users of my app to do custom transformations of data. However, the changes in 3.7.2 and later break brython working in a webworker when importing window. (note that in a webworker window is not available and is called self this is probably the issue)

"cannot import name '$$window'"

3.7.0 & 3.7.1 work great, but I would like to upgrade and get some of the other bug fixes.

Here is a code sandbox of my work distilled. Note that it probaby is a little bit hacky. :P 

https://codesandbox.io/s/brython-in-webworker-ss03z

You can change the version of brython used by changing the version number in brython-version.js

**Comment by PierreQuentel** [comment]
I tested the site (congratulations !) and could reproduce the bug. For version 3.7.2 in __`python_executor.js`__ I tried to replace
```python
from browser import window
```
by
```python
from browser import self as window
```
but I got this error message:
```
console:
	No module named browser.window Line:-61

Outputs:
	
```
After inspecting error traces I found that the bug is in the module `sys` of the standard library : until version 3.7.3 it had the line
```
from browser import window
```
In version 3.7.4 this line was removed; with the change above in __`python-executor.js`__ and setting `version` to 3.7.4 in __`brython-version.js`__, I get this message:
```
console:
	works

Outputs:
	{
  "output": "string",
  "value": "Hello from brython"
}
```
so hopefully it fixes the issue.

**Comment by desean1625** [comment]
So I think that deleting browser.$$window in this commit isn't needed. If it is a webworker the brython has already set _window to self which is the WorkerDedicatedGlobalScope I don't see any sense in deleting it, because it is essentially the window/global scope.
https://github.com/brython-dev/brython/commit/0f6d9a0de1bcdf960261c8488bbdf87cc87629e6#diff-1f835219867332cb706217e566272c28

I modified my codesandbox to use 3.7.4 where browser.$$window isn't deleted and things work as expected while still importing running 
```py
from browser import window
```

Are there reasons that I cannot think of that $$window should be deleted when in a webworker?

**Comment by PierreQuentel** [comment]
The reason to remove `window` in a web worker is compliance with the Web Workers API. As explained in the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) : _" using the window shortcut to get the current global scope (instead of self) within a Worker will return an error"_
