### ISSUE TITLE
Request: Include browser.aio in brython.js

### ISSUE THREAD

**Issue by bit-garden** [brython-dev/brython#1217]
In most of my use cases for aio, I only have the brython_stdlib.js imported for aio.

It would make sense to include aio as part of the smaller part of brython due to the async and await keywords being part of the language and the keywords are useless without some sort of asyncio engine. 

Including it in brython.js would allow for async behaviors without loading another 3.4MB of code that generally may go unused.

**Comment by PierreQuentel** [comment]
I am reluctant to adding too many modules inside __`brython.js`__ ; it should remain small, and limited to modules that are used by most Brython scripts, and I don't think it is the case for `browser.aio`.

The standard way to solve the issue is to replace __`brython_stdlib.js`__ by the script __`brython_modules.js`__, generated by `python -m brython --modules`.

I have modified the script __`browser.__init__.py`__ (it was a very old version with unused imports), with this change, if your HTML page only has
```python
import browser.aio
```
then __`brython_modules.js`__ has only 6kB.
