### ISSUE TITLE
Unable to externally load script via src=""

### ISSUE THREAD

**Issue by timjo6789** [brython-dev/brython#1240]
For some reason, I get this 
`brython.js:5183 Access to XMLHttpRequest at '../basichow/test.py?1572494543087' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`
This occurs when I added the `src="test.py"` to the
`<script type="text/python"></script>`
Using Chrome and Brython.js version 8.
The files are here.
[basichow.zip](https://github.com/brython-dev/brython/files/3792159/basichow.zip)
Any help be appreciated, thanks.

**Comment by PierreQuentel** [comment]
It's likely that you have loaded the HTML in the browser with the File / Open menu, or by double-clicking in the explorer, which means that the "protocol scheme" is `file`. 

If you start a web server in the application directory by `python -m http.server` and load the page by entering `localhost:8000/main.html` the error should not show; in this case the protocol is `http`, and the Ajax request sent to reach the script __`test.py`__ succeeds.

This is because when a script is loaded in the page with `<script type="text/python" src="main.py"></script>`, Brython has to send an Ajax call to the url _main.py_ to read the script content - this is necessary because unfortunately browser only load Javascript scripts.

**Comment by timjo6789** [comment]
@PierreQuentel,
Thanks for helping me to understand that. If that's the case then that makes it so that mobile application in html version non-possible with brython. A possible work around could be that python file pretends to be JavaScript file with the .js extension. Do you think something like this could work with the file://? If so then that will allow with  mobile application with html as well as offline non-server website.
A possible syntax would be
`<script type="text/python" src="main.js">`

**Comment by PierreQuentel** [comment]
This is already possible with [Brython packages](http://www.brython.info/static_doc/en/brython-packages.html). If you run `python -m brython --make_package test` in the application directory, it generates the Javascript program __`test.brython.js`__ that you can load with

```xml
<script src="test.brython.js"></script>
```
and then execute the code in main.py by
```xml
<script type="text/python">
import main
</script>
```

In this case there is no Ajax call, so the page will work with the `file` protocol. You can transfer the application files to a mobile phone and open the page, it will work :-)

**Comment by timjo6789** [comment]
@PierreQuentel,
Ah that worked, thank you for helping me out on that. As I've done these things, there was one more thing that didn't work. I did what you said and yet it produces the same error as the first comment about opening the file and reading the info.
`[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`
`Access to XMLHttpRequest at 'file:///../basichow/data%20here.txt?foo=1572549568553' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`
I then checked to see if it would still continue to function by adding the `document <= 'skipped'` on the next line, it didn't so that means open file will cause the program to crash. For my project that I'm doing, I need to be able to open a text file in the external <name>.brython.js file.
Thanks.

**Comment by PierreQuentel** [comment]
You have probably modified __`test.py`__ with something like 
```python
open("data here.txt")
```
The Python function `open()` is also implemented in Brython with an Ajax call (browsers don't have access to the computer file system). The call is blocking (ie not asynchronous) because the Python function is also blocking; this causes the deprecation message, but you can ignore it (cf. the Brython FAQ for more information). And the call fails anyway because the protocol is `file`.

For the moment there is no real solution to this problem (you could put the file content inside a string in a Python script and import it, but that's ugly...). I will try to find something better, I will keep you informed.

**Comment by Tax0787** [comment]
wow
