### ISSUE TITLE
__getattribute__ triggering on magic methods

### ISSUE THREAD

**Issue by ShaneFarrell** [brython-dev/brython#125]
In its current state defining \_\_getattribute\_\_ is completely unusable as it also catches internal calls to magic methods.

    class MyClass:
        def __getattribute__(self, item):
            print(item)
    
    print(MyClass())

Results in:

\_\_str\_\_
\_\_repr\_\_
[object Object]
<completed in  48.00 ms>

Whereas in CPython it results in:

<\_\_main\_\_.MyClass object at 0x0315BFF0>

    class AttributeAccessDict(dict):
        def __getattribute__(self, item):
            print(item)
            return self[item]
        def __setattr__(self, name, value):
            self[name] = value
    
    obj = AttributeAccessDict({"a": "b"})
    
    print(obj.a)

Results in:

\_\_init\_\_
\_\_getitem\_\_
\_\_getitem\_\_
\_\_getitem\_\_
...recursion limit times...
RangeError: Maximum call stack size exceeded
  module '\_\_main\_\_' line 3
        print(item)
  module '\_\_main\_\_' line 3
        print(item)
<completed in 4426.00 ms>

Whereas in CPython it results in:
a
b

It's worth noting that only in the second example \_\_init\_\_ is printed. This is presumably due to an implementation detail in dict's constructor. The same happens with list and tuple but not with object, int or bool.

**Comment by jsbueno** [comment]
__getattribute__ in cPython is tricky to be used correctly - and if your second example is to illustrate it not working in Brython, I am afraid it won't work in Python as well.  The fact that in cPython the magic methods do not trigger "getattribute" IS an implementation detail, due to the fact magic methods are acelerated in a native C struct and are called directly. It is rather an unfortunate exception to the behavior that every attrobute acces should trigger __getattribute__. 

If you implement __getattribute__ properly, you won't fall in an infinite loop, but rather, the recomedned thing to do is to implent __getattr__ instead. 

(I will check your examples and come back shortly)

**Comment by jsbueno** [comment]
Here you are:
```
class AttributeAccessDict(dict):
    def __getattribute__(self, attr):
        if attr.startswith("__") and attr.endswith("__") and len(attr) >= 5:
            return super(dict, self).__getattribute__(attr)
        print(attr)
        return self[attr]
    def __setattr__(self, name, value):
        self[name] = value
```

Escaping the attributes you are not interested in to the super class is the correct way to write ```__getattribute__``` in Python - any variant. Your example just works in cPython by chance due to the implementation detail I described above.

However, it is a fact that Brython should follow Python's language specifications and mimic as much of Python's behavior as possible. (for example, while trying the code above, I noticed that the automatic "super" call, without parameters does not work yet) - so let's check what Python's specs say about this to decide if this is a valid issue or an imlementation details we should not worry in emulate  -
From https://docs.python.org/3/reference/datamodel.html
```
object.__getattribute__(self, name)
Called unconditionally to implement attribute accesses for instances of the class. If the class also defines __getattr__(), the latter will not be called unless __getattribute__() either calls it explicitly or raises an AttributeError. This method should return the (computed) attribute value or raise an AttributeError exception. In order to avoid infinite recursion in this method, its implementation should always call the base class method with the same name to access any attributes it needs, for example, object.__getattribute__(self, name).

Note This method may still be bypassed when looking up special methods as the result of implicit invocation via language syntax or built-in functions. See Special method lookup.
```

So, see the "may" in the note? As I said, your script worked on Python3/2 by chance - it is deffinetely a behavior that should note be emulated.

**Comment by ShaneFarrell** [comment]
Fair enough. I suppose I should edit my scripts and that it should stay as it is. I had always assumed that Python used object.__getattribute(self, "...") internally and deliberately in order to prevent that.
