### ISSUE TITLE
Allow PEP8 compliant names in `browser` module

### ISSUE THREAD

**Issue by scoopgracie** [brython-dev/brython#1270]
It would be nice if `browser.document.get_element_by_id('id').inner_html` worked.

**Comment by PierreQuentel** [comment]
@scoopgracie 

Thanks for the proposal, but I have to say I don't agree with it :
- names like `getElementById()` and `innerHTML` are normalized by the W3C in the Web API, which is language-independant (not to be confused with the Javascript language), and as such must be supported by Brython
- because they are widely used, Brython already proposes an alternative syntax : `document["elt_id"]` instead of `document.getElementById("elt_id")`, and `element.html` instead of `element.innerHTML`

Having yet another spelling - and an even more verbose one - for the same feature would not be an improvement in my opinion.

**Comment by scoopgracie** [comment]
Ok, thanks! I wasn't aware of the existing alternative names.
