### ISSUE TITLE
Can't open() a file objects from input of type file

### ISSUE THREAD

**Issue by niansa** [brython-dev/brython#1279]
Hi!

Following code:
https://del.dog/bymowognoc.py

Results in:
https://del.dog/avegninawa.txt

So what am I doing wrong?

Tuxifan

**Comment by PierreQuentel** [comment]
Thanks for the report. The fix is related to the totally useless error message, but like in standard Python, the argument of `open()` can only be a string, not an instance of DOM File.
In the current development version I have added to the demo page an example of how to handle this kind of object. Here is a working version of the code you have submitted:
```python
from browser import bind, document, html, window

reader = None
# Create hidden upload button
uploadbtn = html.INPUT(type="file")
document <= uploadbtn

def file_loader(ev):
    # Get uploaded file
    file = ev.target.files[0]
    # Create a new DOM FileReader instance
    reader = window.FileReader.new()
    # Read the file content as text
    reader.readAsText(file)

    @bind(reader, "load")
    def file_importer(ev):
        window.console.log(reader.result)

# Bind it to the button
uploadbtn.bind("change", file_loader)
```

**Comment by niansa** [comment]
Thank you!

**Comment by niansa** [comment]
But, the example flying around im the repo of how to use it is wrong. ;-)
