### ISSUE TITLE
Incorrect and very slow random.randint() behavior

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#128]
This snippet:
```
from random import randint
count = 0
for x in range(1000):
	if randint(0,1000) > 600:
		count += 1
print(count)
```
produces what is evidently not random output:
```
 0
 <completed in 5586.00 ms>
```
And in an extraordinarily long time.

**Comment by kikocorreoso** [comment]
I will dig into it. In the meantime you could replace `random` with `__random` in the snippet above.

It is faster and is providing correct results.

Why `__random` is faster than `random`? The first one is a pure js implementation of part of the `random` module.

**Comment by kikocorreoso** [comment]
In the Brython site is not working correctly but in the dev version is ok.

I think the issue is related to #98 already solved.

Please, use a local site from the repo or use `__random` on brython.info to get correct results until version 3.0.3 would be uploaded to brython.info.

Sorry for the inconveniences.
