### ISSUE TITLE
Saving a lot of data to local object storage freezes everything

### ISSUE THREAD

**Issue by niansa** [brython-dev/brython#1282]
Saving a lot of data to object storage via local storage freezes everything.
As example, try to save following dict to the local storage:
https://del.dog/opparefuwo.py

**Comment by PierreQuentel** [comment]
@niansa 
Sorry for the late answer, and thanks for the report. 

This was because, for compliance with the Python language, I replaced the `json` module by the pure-Python version a few months ago, and it's much slower than using the Javascript JSON object. The new version of `object_storage` in the commit referenced above uses the Javascript object; the example included in your report now runs in a fraction of second.

**Comment by niansa** [comment]
Great!
