### ISSUE TITLE
Cannot import Request from urllib.request

### ISSUE THREAD

**Issue by mhucka** [brython-dev/brython#1346]
The following minimal test case,
```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.8.8/brython.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.8.8/brython_stdlib.min.js"></script>
  </head>
  <body onload="brython()">
    <script type="text/python">
     from urllib.request import Request
    </script>
  </body>
</html>
```

fails to load in a browser (Safari 13 if it matters) with the following error:
```
Traceback (most recent call last):
  module __main__ line 3
    from urllib.request import Request
ImportError: cannot import name 'Request'
```

The import statement above works in Python 3 outside of Brython. Other parts of urllib load in Brython; for example, the following works:

```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.8.8/brython.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.8.8/brython_stdlib.min.js"></script>
  </head>
  <body onload="brython()">
    <script type="text/python">
     from  urllib import parse
    </script>
  </body>
</html>
```

Why does the Request module fail? If only a limited number of modules in different packages are usable in Brython, how can one find out which ones they are, for a given Python package?

**Comment by PierreQuentel** [comment]
The minimalist version of __`urllib`__ is there to prevent modules that import it to fail, but you can't expect much from it : a browser cannot send HTTP requests, the only thing it can do is send Ajax calls, which most of the times will fail because of the "same origin" policy.

The [documentation page about stdlib](http://www.brython.info/static_doc/en/stdlib.html) mentions all the scripts that are common to Brython and CPython standard libs. I have updated it with a leading "*" before the script name when the versions are different (most are the same). It doesn't completely answer your request, but giving the detail of differences would be a lot of work; at least it suggests that some features might be missing.

**Comment by PierreQuentel** [comment]
I am closing this issue, as I don't think that I can do much more than the change in the doc page. Thanks for the report !
