### ISSUE TITLE
implement ast module, or a least its `literal_eval`

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1364]
Hello,

while trying to import `jinja2` for testing purpose, the import of `literal_eval` from `ast` module from stdlib failed. `literal_eval` is a safe `eval` which can be used with untrusted source (see https://docs.python.org/3/library/ast.html#ast.literal_eval) and could be useful in the web context.
Would it be possible to implement `ast` module, or at least its `literal_eval` method?

Thanks

**Comment by PierreQuentel** [comment]
Unfortunately not. The CPython module uses a module __`_ast`__ written in C, and even the function `literal_eval()` doesn't work without this module. In theory it would be possible to rewrite __`_ast`__  in Javascript, but this would require a much smarter developer than I ;-)

**Comment by goffi-contrib** [comment]
sure that's understandable. Out of curiosity have you evaluated the possibility of compiling python modules with C dependencies with webassembly? It's probably some work to create a build chain, but it would allow to use most Python modules. Is it something which can be seen in long term project of Brython, or would it be out of scope of the project? Thanks

**Comment by PierreQuentel** [comment]
I have not tried this approach because I don't know C and how to build programs, but if someone is able to produce Javascript from such files I would be very interested.

**Comment by goffi-contrib** [comment]
@PierreQuentel OK, I may have a look at a later point. For now I'm far too busy, but I'll definitely give you feedback if I try something with it.

**Comment by gilch** [comment]
Does this help? https://github.com/beeware/ouroboros/blob/master/ouroboros/ast.py#L38

The Ouroboros project is an attempt to implement the standard library in Python. It's not feature-complete yet, but maybe this part works.

**Comment by PierreQuentel** [comment]
@gilch 
This is the module __`ast`__, the same as in the CPython distribution, but it relies on a module __`_ast`__ (line 27) which is written in C.

**Comment by gilch** [comment]
@goffi-contrib CPython in WebAssembly has been done: https://github.com/iodide-project/pyodide/ but it takes even longer to load than Brython.

**Comment by Grahack** [comment]
> In theory it would be possible to rewrite **`_ast`** in Javascript, but this would require a much smarter developer than I ;-)

But @PierreQuentel could you please briefly explain how you parse Python code then? or just point to the relevant Brython source files?

Would this mechanism be accessible from JS or even Brython?

**Comment by PierreQuentel** [comment]
@Grahack 
There is a short explanation on the page [How Brython works](https://github.com/brython-dev/brython/wiki/How-Brython-works), the paragraph starting at "The translation to Javascript takes the following steps".

The result of function `py2js()` is a tree structure, but not meant to be compliant with the AST built by the ast module. Using it to generate a Python ast is probably very difficult.

**Comment by moepnse** [comment]
I am currently working on porting the [AST module](https://github.com/pfalcon/pycopy-lib/tree/master/ast/ast) of the [pycopy-lib](https://github.com/pfalcon/pycopy-lib) and [RestrictedPython](https://github.com/zopefoundation/RestrictedPython) to Brython.

**Comment by Grahack** [comment]
Interesting! Maybe you could still post news on this very issue for some folks like me to be notified. If you need some help I could try, at least for some testing.

**Comment by moepnse** [comment]
I ran a benchmark on an `AMD Athlon (tm) II X2 245e`. I realize that this CPU is not the newest.

```python
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Sample 2</title>
        <!-- Brython -->
        <script src="/static/brython/brython.js"></script>
        <script src="/static/brython/brython_stdlib.js"></script>
        <script src="/static/ast.brython.js"></script>
        <script src="/static/RestrictedPython.brython.js"></script>

        <script type="text/python">
import time
        
s_time = time.time()
from browser import document
print("from browser import document:", time.time() - s_time)

s_time = time.time()
from RestrictedPython import compile_restricted
print("from RestrictedPython import compile_restricted:", time.time() - s_time)

s_time = time.time()
from RestrictedPython import safe_globals
print("from RestrictedPython import safe_globals:", time.time() - s_time)

source_code = """
from os import *
"""

loc = {}
s_time = time.time()
try:
    # Leads to a SyntaxError because "*" imports are not allowed.
    byte_code = compile_restricted(source_code, '<inline>', 'exec')
except SyntaxError as err:
    document["output"].text = err.msg
print("byte_code = compile_restricted(source_code, '<inline>', 'exec'):", time.time() - s_time)

        </script>
    </head>
    <body onload="brython({debug: 1});">
        <div id="output">
        </div>
    </body>
</html>
```

The conclusion from the benchmark result bellow is: It is too time consuming to be ready for productive use.

```
from browser import document: 0.0010001659393310547
from RestrictedPython import compile_restricted: 2.6690001487731934
from RestrictedPython import safe_globals: 0.0009999275207519531
byte_code = compile_restricted(source_code, '<inline>', 'exec'): 3.8889999389648438
```

How it works: Currently, an `AST` is generated from the source code, which is then used by `RestrictedPython`. After the `AST` has been processed by `RestrictedPython`, it is translated back to Python source code and executed by `Brython`.

We should pool our efforts to get a usable version.

I will be in talks to get permission to release the modified version.

**Comment by moepnse** [comment]
Python's [compile](https://docs.python.org/3/library/functions.html#compile) function is able to translate an `AST` into a code object. This can then be executed by `exec`.

Since that doesn't work under `Brython`, I used an `AST unparser`. Specifically, I use this one: https://github.com/simonpercivall/astunparse/blob/master/lib/astunparse/unparser.py

And added the code bellow:
```python

import io

...

def unparse(ast_tree):
    stream = io.StringIO()
    unparser = Unparser(ast_tree, stream)
    return stream.getvalue()
```

Apparently attributes like [lineno] (https://docs.python.org/3/library/ast.html#ast.AST.lineno) are not set correctly by the [ast module](https://github.com/pfalcon/pycopy-lib/tree/master/ast/ast).

As an example, the `RestrictedPython` module requires the undocumented attribute `_attributes`, which is not set by the [ast module](https://github.com/pfalcon/pycopy-lib/tree/master/ast/ast) mentioned.

Lines like [this](https://github.com/pfalcon/pycopy-lib/blob/d607855dc5004464aa10f451d81c42a1d5a4cec7/ast/ast/parser.py#L514) have to be changed as follows, to support at least `lineno`:
 ```python
        return ast.Name(id=t.string, ctx=ast.Load(), lineno=t.start)
```

I modified the [class AST](https://github.com/pfalcon/pycopy-lib/blob/d607855dc5004464aa10f451d81c42a1d5a4cec7/ast/ast/types.py#L1) to this:
```python
class AST:
    _attributes = ["lineno",
    "col_offset",
    "end_lineno",
    "end_col_offset"]

    def __init__(self, *_args, **fields):
        fields.update(dict(zip(self._fields, _args)))
        for k, v in fields.items():
            setattr(self, k, v)
```

I think that's more of a botch of mine than the final solution, but it works.

**Comment by moepnse** [comment]
Can we reopen this issue for further discussion?

**Comment by Grahack** [comment]
Hi! Sorry I'm a bit lost. Since I'm interested only in AST could you explain how I could test this module only? Performance shouldn't be such an issue for my use case:
* for small (20LOC max) Python snippets, build the AST
* tweak this AST inserting Python instruction to count instruction executions like assignments, arithmetic ops…
* execute this new AST to obtain the number of assignments, arithmetic ops… encountered during the execution.

**Comment by moepnse** [comment]
@goffi-contrib I'm also working on an "ast" -less `literal_eva`l implementation. Currently with limited support for arithmetic operations.

@Grahack Since parts of the modified version were created during my time as an employee, I have to wait for the approval of the management.

Generally it is a complicated situation. Parts come from my company or from my free time, others from my employment.

**Comment by gilch** [comment]
I hacked together a (mostly) working `literal_eval` from `pycopy-ast` and CPython 3.6.

https://gist.github.com/gilch/efdd9a1f600cef976be921bb3c5ed421

**Comment by PierreQuentel** [comment]
I am doing some cleaning among the old issues. I am going to close this one, hoping that someone can provide a PR with an implementation of ast some day.
