### ISSUE TITLE
re module may be crashing Brython

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1365]
Hello,

while trying to import `jinja2` for testing purpose, Brython crashed when trying to import `_identifyer.py` with contain a regex with many unicode characters (see https://github.com/pallets/jinja/blob/master/src/jinja2/_identifier.py).

In the crash logs, we have this interesting log: `["bad character range \udf76-\ud800 at position 459"]`

**Comment by PierreQuentel** [comment]
I tried running this script with CPython 3.8 and it also fails:
```
E:\jinja\src\jinja2>e:/python38/python.exe _identifier.py
  File "_identifier.py", line 5
SyntaxError: Non-UTF-8 code starting with '\xe0' in file _identifier.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by goffi-contrib** [comment]
weird, it's working for me:
```sh
% python -c "import _identifier; print(_identifier.pattern)"
re.compile('[\\w·̀-ͯ·҃-֑҇-ֽֿ-ًؚ-ٰٟ-ۜ۟-ۤۧ-ܑۭ-݊ަ-ް߫-߳ࠖ-࠙ࠛ-ࠣࠥ-ࠧࠩ-࡙࠭-࡛ࣔ-ࣣ࣡-ःऺ-़ा-ॏ॑-ॗॢ-ঃ়া-ৄেৈো-্ৗৢৣ-ਃ਼ਾ-ੂੇ-੍ੑ-ઃ઼ા-ૅે-ૉો-્ૢ-ଃ଼ା-ୄେୈୋ-୍ୖୗୢୣா-ூெ-ைொ-்ௗఀ-ఃా-ౄె-ైొ-్ౕ-ಃ಼ಾ-ೄೆ-ೈೊ-್ೕೖೢೣ-ഃാ-ൄെ-ൈൊ-്)
% python --version
Python 3.8.2

```

**Comment by PierreQuentel** [comment]
Thanks again !

The issue was not in the __`re`__ module, the code crashed because the string passed to `compile()` has "surrogate pairs", and I realized that such strings are not managed in Javascript as in Python : the pair counts for 2 characters in JS and only 1 in Python, so that length, indexing, iteration etc. don't give the same result. I had to introduce a specific class for these strings, and implement a few methods, at least those required to make your example work.
