### ISSUE TITLE
browser.aio.ajax headers broken

### ISSUE THREAD

**Issue by Tomaat** [brython-dev/brython#1371]
I've ran into some trouble with aio.ajax
version: 3.8.8 from pipy

minimal example to reproduce (by sending a post to an echo-server):
```
<!doctype html>
<html>

<head>
<meta charset="utf-8">
<script type="text/javascript" src="brython.js"></script>
<script type="text/javascript" src="brython_stdlib.js"></script>
</head>

<body onload="brython()">
<script type="text/python">
from browser import aio, ajax

url = "http://httpbin.org/post"
header = {"Content-Type": "application/x-www-form-urlencoded"}
data = {"hello": "world"}

def foo(x):
    print("ajax", x.status, x.responseText)

def main():
    ajax.post(url, headers=header, data=data, oncomplete=foo)


async def amain():
    x = await aio.post(url, headers=header, data=data)
    print("aio", x.status, x.responseText)

main()
aio.run(amain())
</script>
</body>

</html>
```
you can see from the command-line logs that the `ajax.post` function uses the correct header, but the `aio.post` doesn't.

Solution:
In www/src/libs/_aio.js line 46 there's a small typo.
`headers = _b_.dict.$to_obj(kw)` should be `headers = _b_.dict.$to_obj(kw.$string_dict[key][0])`

I do not know what other effects this change has, nor do I have experience with contributing to this project. Can someone help me further?

**Comment by PierreQuentel** [comment]
@Tomaat 
Thanks for the bug report, I have tested your patch, it's ok !

There is a [page](https://github.com/brython-dev/brython/blob/master/CONTRIBUTING.md) about how to contribute - basically, submit a "Pull Request" with the proposed modification.

Since you provided the solution I can include it myself, but if you prefer to submit a PR just to test the "standard" contribution path, I will merge it.

**Comment by PierreQuentel** [comment]
@Tomaat 
@glyph submitted a Pull Request and I have merged it, I hope you don't mind. Thanks again !
