### ISSUE TITLE
Initial delay in web-app after page loads

### ISSUE THREAD

**Issue by deb17** [brython-dev/brython#1374]
Hi,
After watching Brad Traversy's crash course on brython, I decided to code a web-app using it. It is a calculator app with some math functions. You can find it [here](https://calcee.netlify.app). The problem is that after the web page loads, the app does not respond until nearly 50s or so. This happens only the first time - on reload, there is no delay. To recreate the issue, you would need to clear the browser's cache and then reload the page.
My repo is [here](https://github.com/deb17/calculator) . I am importing only the `functools` and `math` standard library Python modules. I am not using any cdn - all files are local.
Please help me debug this problem.
Thanks,
Debashish

**Comment by noahbroyles** [comment]
I noticed this same issue just trying the Brython demo clock from http://brython.info/. I coded the clock into this page: https://homepages.uc.edu/~broylend/midterm/about.html. The clock takes 6 seconds to load, while the clock on the Brython homepage loads almost instantly.

**Comment by PierreQuentel** [comment]
Sorry in advance for the long answer, but the problem is one of the 2 most difficult challenges Brython has to face (the other being generators, a nightmare !).

### 1. some modules require many, many other modules

Your code only has 3 imports : modules __`browser`__ and __`math`__ don't import anything else, but it's not the same for __`functools`__:
- __`functools`__ *must* import modules __`_thread, collections, reprlib, weakref, _functools`__ at module level, and *may* import modules __`typing, abc, reprlib, types, warnings`__ inside functions
- __`warnings`__ *must* import __`sys, traceback, linecache, re, tracemalloc`__
- __`re`__ *must* import __`sre_constants, copyreg, sre_parse, _locale, functools, enum, sre_compile`__

and so on, and so on. In the end, just because of __`functools`__ you end up having to precompile about 64% of the standard library (brython_modules.js for your application is 2,3 MB compared to 3,6 for brython_stdlib.js).

The most frustrating is that in fact your application only uses 17 modules, because it doesn't need any of the modules that __`functools`__ *may* import ! But since it's impossible to know in advance if they will be used, all modules have to be precompiled to JS and stored in the cache.

### 2. ideal solution, and why it's not possible :-(

Ideally, translating to Javascript and storing in cache could happen at runtime : when Brython runs

```python
import a
print(a.x)
```

the algorithm could be:
- execute code "import a"
- see if module __`a`__ is in the cache
    - if not, get the Python code of module __`a`__, translate to Javascript, store in indexedDB
    - else, load from indexedDB
- execute code "print(a.x)"

Unfortunately this is not possible because, by design, *access to indexedDB is asynchronous* (non-blocking) : storing into or reading from the database doesn't stop the program execution, which means that the next instruction ("print(a.x)") is executed just after the asynchronous call is done, not when this call completes. Of course, since "import a" is not completed, "print(a.x)" fails.

The only possible thing (at least the only one I found...) is to precompile and store in cache before starting to run the program. And with hundreds of modules to compile and store, it takes dozens of seconds...

### 3. workarounds

There are at least 2 workarounds (I ignore the radical solution of not using __`functools`__ at all ;-)

- don't use the indexedDB database, by setting the option _indexedDB_ to `false` :

```xml
<body onload="brython({indexedDB: false})">
```

In this case, the cache is not used and all modules are compiled to Javascript at each run. All runs take about the same time, which is much less than the first import with indexedDB but more than with the next runs with the cache

- if you keep the indexedDB cache:
    - hide the calculator on page load (`style.display = "none"`) and show a DIV with something like "Loading, please wait, it will be faster next time..." (maybe with a timeout of 1 or 2 seconds so that it will show only in the first run)
    - after the imports, remove this DIV and display the calculator

I am conscious that this is not ideal, if someone can think of a better solution I would be extremely pleased !

**Comment by PierreQuentel** [comment]
@noahbroyles 
Although I obviously don't have any figure, I would say that the issue submitted by @deb17 is not the general case. I see that you have set `{indexedDB: false}`, if you remove the option the loading time should be the same as on brython.info.

**Comment by PierreQuentel** [comment]
@deb17 I like the design of your calculator BTW :-)

**Comment by deb17** [comment]
Thanks @PierreQuentel ! I don't really need the `functools` module except for the `wraps` decorator, so I think I will leave it out. That should make brython_modules.js smaller and decrease the precompile time.

**Comment by noahbroyles** [comment]
@PierreQuentel Thank you, you have been very helpful! 
I actually added the `{indexedDB: false}` after reading your answer and the loading was improved by it.

**Comment by deb17** [comment]
It worked! I don't know much about brython, but isn't it possible to avoid compilation of standard library modules in the browser? If brython_stdlib.js contained the compiled js, that would save time.

**Comment by PierreQuentel** [comment]
@deb17 
__`brython_stdlib.js`__ doesn't contain the Javascript translation, but the Python source code of the standard distribution packed as a big JSON objects. Once translated, the code is something like 10 times bigger, it would make the file around 25 MB... It is the indexedDB cache that stores the JS translation.

**Comment by deb17** [comment]
@PierreQuentel Thanks a lot for taking the trouble of clearing my doubts! I am going to close the issue.
