### ISSUE TITLE
Change in script loading (appends timestamp)

### ISSUE THREAD

**Issue by ese942** [brython-dev/brython#1402]
# Issue 
Brython is appending a '?' and a timestamp to the url of loaded scripts.  This can cause script load to fail if the script URL always has a query parameter.

Behavior started for me today.  Could be related to recent Chrome 83 update.  Same behavior with brython versions 3.8.0 - 3.8.9.

# Example
From my webserver log: brython request to load a script.  Note the appended timestamp.  This is part of the original request, not added by my webserver logging.
192.168.1.176 - - [31/May/2020 23:16:13] "GET /retrieve?file=/py/myscript.py?1590959773117 HTTP/1.1" 404 -

Compare to this entry from my logs 2 days ago with no appended timestamp:
192.168.1.176 - - [29/May/2020 23:46:34] "GET /retrieve?file=/py/myscript.py HTTP/1.1" 200 -

Chrome console appears to confirm that brython is the source of the timestamp on the outgoing request:
GET https://example.com/retrieve?file=js/myscript.py?1590961295648 404 (cant find file: myscript.py?1590961295648)
e.ajax_load_script @ retrieve?file=js/brython.3.8.8.js:23
e.loop @ retrieve?file=js/brython.3.8.8.js:23
$B.parser._run_scripts @ retrieve?file=js/brython.3.8.8.js:23
$B.parser.brython @ retrieve?file=js/brython.3.8.8.js:23
onload @ retrieve?file=js/test.html:144

# Description
For some reason brython is appending a '?' and a timestamp to the script url.  Many webservers might ignore this and still return the file.  However, my server already has a query parameter with the filename.  When the query is parsed, the "?1590959773117" becomes part of the filename and voila, 404 not found.

I can fix for my own setup.  The questions to consider are:

1. If the '? timestamp' is a mistake - why is it only appearing now?  Why not 2 days ago?  Did chrome 83 change the way it handles something that brython uses for ajax requests?  Seems to affect versions of brython at least back to 3.8.0.

2. If '? timestamp' is not a mistake - why does Brython append this?  Shouldn't brython check if the url already contains a query marker ('?') first?  Shouldn't the fact that a timestamp is added to script load requests be mentioned in the documentation?  Why is this behavior only appearing now, after 4 years of never occuring?

3. Why is there no console error message? - this one I partly figured out.  My webserver was configured to assume any requested scripts from /py/ that don't exist, would be created shortly.  So it returned 204 (No content) instead of 404 (Not Found).  Brython saw these 204 responses and assumed everything worked properly.  It would be nice for brython to issue a console warning when a requested script is empty, regardless of the HTTP status code.  But I can't blame anyone for not doing that with 2xx.  FYI when I changed my server to return 404 brython put a nice big red warning in the console. :)

# Reproduce
Run brython 3.8.x on chrome 83 and check your python script webserver logs?

Hope this helps,
Edward

**Comment by PierreQuentel** [comment]
@ese942 
The `?<timestamp>` is related to browser cache. By default, Brython doesn't use it, so that changes to a script loaded by
```xml
<script type="text/python" src="myscript.py"></script>
```
are immediately visible when the page is reloaded.

To bypass browser cache, a fake additional parameter is added to the url, here the current timestamp : `myscript.py?1591080834924`

The cache can be enabled by running function `brython()` with the option `cache` set to true:

```xml
<body onload="brython{cache:true})`>
```

In this case, the timestamp is not appended to the url. This feature has not changed for a few weeks at least, so the change you observe is likely due to the fact that cache was enabled in your page and disabled later.

Anyway, there was a bug in the implementation, because I hadn't thought of the case when the script url already has a question mark. The commit referenced above tests this and, if true, adds the timestamp after a & instead.

**Comment by Kodiologist** [comment]
This just bit me. Shouldn't it be documented at https://brython.info/static_doc/en/import.html ?
