### ISSUE TITLE
Converting Python dict object to JS object

### ISSUE THREAD

**Issue by sedir** [brython-dev/brython#1433]
Hi! I'm new to Brython and just started porting a small existing project. 

Well, I have a JS library that I need to access and pass a dict as an attribute. The object in JS is visible as `toastr` and I can access in Python using `window.toastr`, so trying to pass the `window.toastr.options = {'option1': value, ...}`. However in the JS console browser I can't see the same structure when I inspect `toastr.options`:
```
{__class__: {…}, $numeric_dict: {…}, $object_dict: {…}, $string_dict: {…}, $str_hash: {…}, …}
```
It comes down to this: how can I correctly convert a Python dict to a JS object?

**Comment by PierreQuentel** [comment]
Brython is designed to support Javascript programs and work with Javascript objects, but the reverse is not true.

A Javascript object is by nature different from a Python dictionary : its keys are always strings. If the Python dictionary is
```python
d = {1: 'a', '1', 'b'}
```
it has two keys, the integer 1 and the string '1', but if a Javascript object is defined as
```javascript
var d = {1: 'a', '1', 'b'}
```
it only has one key, the string '1'.

If a Javascript program wants to use a Brython object, it has to convert it with a specific piece of code to the data structure that is adapted to this program (an object, or maybe an instance of `Map`). Moreover, Brython doesn't promise that the implementation of Python objects will remain stable across versions - in fact, in order to implement the preservation of insertion order in Python 3.7, the implementation of dictionaries has changed between versions 3.6 and 3.7.

**Comment by PierreQuentel** [comment]
I am closing the issue, if you think there is still an issue don't hesitate to reopen it.

**Comment by sedir** [comment]
Thank you for your answer, now I understand more about Brython and how can I use it properly.
