### ISSUE TITLE
json.dumps() and json.loads() are very slow

### ISSUE THREAD

**Issue by danijar** [brython-dev/brython#1458]
A workaround for encoding is to use JavaScript's `window.JSON.stringify()`. Calling `window.JSON.parse()` throws an error for me when called from Brython.

**Comment by PierreQuentel** [comment]
Can you post an example when `window.JSON.parse()` raises an exception ?

The suggested way to use Javascript's JSON is with the built-in module __`javascript`__:
```
Brython 3.8.9 on Netscape 5.0 (Windows)
>>> import javascript
>>> s = javascript.JSON.stringify({'a': 1})
>>> s
'{"a":1}'
>>> d = javascript.JSON.parse(s)
>>> d
{'a': 1}
>>> 
```

**Comment by PierreQuentel** [comment]
This issue has been discussed previously (#1259, #1173); there was a suggestion to replace the __`json`__ module by a pure Javascript version, but this was no possible because of some parameters of Python's `json.dump()` or `json.load()` that couldn't be supported by the JS version.

The version implemented in the commit referenced above is an attempt to use the much faster JS version in the most simple (and hopefully the most common) uses of the module : if no specific argument is passed to `load()` or `dump()`, other than `indent` for `dump()`, the JS version is used, otherwise the Python version is used.

Can you try with this new version, and does it improve the performance in your use case ?

This could probably be improved with the support of other arguments by the JS version (eg `separator`).

**Comment by PierreQuentel** [comment]
It was too good to be true... After a few tests I realise that dictionary order cannot be preserved if we use Javascript JSON... I'm afraid I will have to code a complete version of `dump()` to be sure to have the same results as with CPython.

**Comment by danijar** [comment]
I think JSON dicts are unordered according to the standard, so it might be fine if they don't preserve ordering?

I'll also provide an example of where `JSON.parse()` when I work on the code base next time. Should have included it in the issue in the first place.

**Comment by PierreQuentel** [comment]
In commit 61ec6a48804d12b7674d86f2e1fa96d3178c1a55 I have replaced the slow, pure-Python package by a single module, __`json.py`__, that uses the Javascript module __`libs/_json.js`__ where all the options of `load()` and `dump()` are implemented. It should be much faster than the Python version and not too far in performance from using `javascript.JSON`, with the advantage that it is compliant with the CPython module.

**Comment by PierreQuentel** [comment]
I am closing this issue. If you find other problems with the json module (compliance with the Python module or performance) don't hesitate to reopen it. Thanks again !

**Comment by danijar** [comment]
Thank you! Sorry I didn't get a chance to test it yet. I'll open a new issue in case I run into related problems in the future.
