### ISSUE TITLE
Side effect (cycles) when evaluating string representation of empty set

### ISSUE THREAD

**Issue by mircea3** [brython-dev/brython#1468]
In the following:
```
s1 = set()
print(len(s1), s1)
s1.add('hello')
print(len(s1), s1)
```

The output seems to show that cycles are detected:
```
0 set()
1 set(...)
```

A possible quick fix (py_set.js around line 250):
```
-   self.$cycle = self.$cycle === undefined ? 0 : self.$cycle + 1
    if(self.$items.length === 0){
        return klass_name + "()"
    }
+   self.$cycle = self.$cycle === undefined ? 0 : self.$cycle + 1
```

The output is now as expected:
```
0 set()
1 {'hello'}
```

**Comment by PierreQuentel** [comment]
Thanks @mircea3 

I don't remember why the attribute `$cycle` is used, probably because there is a need to handle circular references in dictionaries and lists and I might have thought at the time that the same should be done for sets.

But since a set can't be added to itself (it is not hashable) there is no need to support this case, and the attribute `$cycle` should be removed. Do you agree ?

**Comment by mircea3** [comment]
I believe it is still needed (?). For example:

```
s1 = set()
class Foo:
    s1 = s1
    def __repr__(self):
        return 'Foo(s1=%r)' % self.s1

s1.add(Foo())
print(s1)
```

**Comment by mircea3** [comment]
I believe it is still needed (?). For example:

```
s1 = set()
class Foo:
    s1 = s1
    def __repr__(self):
        return 'Foo(s1=%r)' % self.s1

s1.add(Foo())
print(s1)
```

**Comment by PierreQuentel** [comment]
You were right (as usual ;-). The commit fixes the bug, using the same mechanism as for dict and list circular references.
