### ISSUE TITLE
ReferenceError: brythonListener is not defined while calling brython function from javascript

### ISSUE THREAD

**Issue by nikhilc2710** [brython-dev/brython#1484]
I am trying to call brython function from javascript promise it giving error  **ReferenceError: brythonListener is not defined** how to solve this?
python/brython code
```
<script type="text/python">  
def execute(*args):
    print(str(args))
window.brythonListener=execute
</script>
```
javascript code

```
            function(data){
                console.log(data) //till here code works
                brythonListener(data)
            }
        )
```
what i am missing here?

**Comment by PierreQuentel** [comment]
Brython is designed to allow execution of Javascript code from Python code, but the reverse - using Python code from Javascript - is generally not a good idea.

In this example, the problem is that the Brython code is executed on page load; the attribute `window.brythonListener` is set after the page is loaded, and the Brython code has been executed. If the Javascript code is executed before that, the name will not be available.

A workaround would be to run `brython()` inside the Javascript code:

```xml
<body>

<script type="text/python">
from browser import window

def execute(*args):
    print(str(args))
window.brythonListener=execute

</script>

<script>
window.onload = function(ev){
  brython({debug: 2}) // run the Brython script, which sets window.brythonListener
  function f(data){
      console.log(data) //till here code works
      brythonListener(data)
  }
  f("hey !")
}
</script>
</body>
```

But it would be better to write everything in Brython...

**Comment by nikhilc2710** [comment]
Error still exsits after applying above workaround

**Comment by nikhilc2710** [comment]
Thankyou so much for help got it working by.  
```
<script onload="brython()" >     
function(data){
                console.log(data) //till here code works
                brythonListener(data)
            }
        )
</script>
```
if there any suggestion or ressource how to handel promise in brython would be great
