### ISSUE TITLE
Add tutorial pages to brazilian portuguese

### ISSUE THREAD

**Issue by CauaneAndrade** [brython-dev/brython#1505]
https://github.com/brython-dev/brython/tree/master/www/tutorial

- translate tutorial content to brazilian portuguese

**Comment by djeni98** [comment]
I can translate from English to Portuguese. 
Can I use this file as source?
-  https://github.com/brython-dev/brython/blob/master/www/tutorial/en/index.md

It it is ok, assign me to this issue.

**Comment by PierreQuentel** [comment]
For most of the documentation I prefer to limit languages to just French, English and Spanish because it's hard to keep the whole doc up to date; but the tutorial is less likely to change, so I welcome other translations, currently Italian and Breton (not yet on brython.info but it will come soon).

If you can do the translation, please submit a Pull Request with the Brazilian Portuguese version - I see that there is a big Brython fan club in Brazil :-)

**Comment by PierreQuentel** [comment]
I close this issue after merging PR #1521. Thanks again Cauane !
