### ISSUE TITLE
Show nice tracebacks when called from JavaScript

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1510]
While troubleshooting my Brython app, I noticed that I get a nice Pythonic traceback when there's an error in my Brython code, but not when my Brython function is called by JavaScript code, making errors hard to understand. Would be nice to have that.

**Comment by PierreQuentel** [comment]
Brython is designed to integrate Javascript programs as seamlessly as possible, but the reverse is false: _using Brython code from Javascript is generally not a good idea_, because Python objects are generally implemented very differently from their closest Javascript equivalent: Python dictionaries are very different from JS objects or Maps, Python sets are very different from JS Sets, Python classes are very different from JS "classes" (created by the keyword `class`), etc. 

Moreover, the implementation may vary from a Brython version to the next.

**Comment by cool-RR** [comment]
How does the second part of the paragraph imply the first part? Only if the function is taking one of these data types that are more complex than numbers and strings, right?

**Comment by PierreQuentel** [comment]
Not only for functions, for instance with this code
```xml
<script type="text/python3"">
from browser import window

window.s = {1, 2, 'a'}
window.test()
</script>

<script>
function test(){
    console.log(window.s.length)
}
</script>
```
The result will be `undefined` instead of the expected value, 3. To get the correct result the JS code should be
```javascript
function test(){
    console.log(window.s.$items.length)
}
```
which requires to know Brython's internals to do something useful with the Brython object from the JS code.

But maybe this is too general; can you provide an example where the JS traceback doesn't produce usable information ?

**Comment by cool-RR** [comment]
I've noticed how Python objects are hard to access from JavaScript, that's natural. But I'm talking just about running Python functions, which may not take complex arguments and may not return anything.

My code is too big and convoluted to share...

**Comment by cool-RR** [comment]
(I'm still in the go-crazy-and-write-lots-of-code part of my project.)

**Comment by PierreQuentel** [comment]
I am closing this old issue. If you wish to reopen it with more information, please do :-)
