### ISSUE TITLE
Make template braces customizable

### ISSUE THREAD

**Issue by peppelinux** [brython-dev/brython#1539]
As seen in
https://github.com/brython-dev/brython/blob/fe8f6787e0cea9fbe9bea5be308fa6fd9cf36a11/www/src/Lib/browser/template.py#L157

Would It be possibile to have a .register() method/func to change the symbol { in, for example, [?

At this time It looks as a constant in the code. 
This Will let us to use brython template as files, without collisions with jinja2 and Django templating system

**Comment by PierreQuentel** [comment]
@peppelinux 
It would be difficult, because the __`template`__ module transforms text nodes that have curly braces into Python f-strings, where expressions are enclosed inside {}. With another delimiter, the engine would have to parse the text and replace other delimiters with {}, add a way to escape the delimiters, etc.

I don't know about Django, but for Flask / Jinja the template files used by `render_template()` are located in a specific directory. If you put Brython pages in another one, there should not be any conflict.

**Comment by peppelinux** [comment]
Hi @PierreQuentel 
there would the possibility to replace the double braces {{ with the registered symbol before processing?

I'd also suggest to use fstring instead of string sum, for performance (https://stackoverflow.com/questions/38722105/format-strings-vs-concatenation?answertab=votes#tab-top)
````
text = '"' + text + '"'
````

thank you for brython, I'm loving it
