### ISSUE TITLE
Question about support of cp932

### ISSUE THREAD

**Issue by sakurai-youhei** [brython-dev/brython#1541]
Hello,

Thank you for your great work first of all.

Now I'm looking for possibility of cp932 encode/decode on Brython.

In CPython, the cp932 depends on [_codecs_jp](https://github.com/python/cpython/blob/v3.9.0/Modules/cjkcodecs/_codecs_jp.c). So, Q1) the cp932 can't be ported from CPython to Brython, am I right?

On the other hand, 834c5ccecef2960f7aa7e34e54ff79d3e369440c, #1177, #380, etc look like Q2) Brython does encode/decode some like utf-8 in JS first and then falling back to Python's `encoding.*`, doesn't it?

If Q1=true and Q2=true, then I assume Q3) right approach would be patching `__BRYTHON__.builtins.bytes.decode` in JS or writing own `encodings.cp932` in Python, correct?

P.S. Once I've joined mailing list, I'm gonna close this and move there; My apologies for overlooking the mailing list.

**Comment by sakurai-youhei** [comment]
Move to https://groups.google.com/g/brython/c/FnXpFnC3I_s.

**Comment by PierreQuentel** [comment]
@sakurai-youhei 
Thanks for the report. I have reopened the issue because I find it more convenient to work with the issue tracker than the Google group.

The commits referenced above should fix the issue.

Whenever possible the files written in C in CPython are translated to Python or Javascript in Brython. This is what I have done here:
- the script __`Lib/encodings/cp932.py`__ is the same as in CPython
- the script __`Lib/_multibytecodec.py`__ has been generated. It does nothing useful but must be present since __`cp932.py`__ imports a module __`_multibytecodec`__ written in C
- the script __`Lib/_codecs_jp.py`__ has also been generated to replace CPython's __`_codecs_jp`__. For compliance with the codec API it defines a function `getcodec()` that returns the `Codec` class with methods `decode()` and `encode()`. These methods use a multibyte encoding.
- __`_codecs_jp.py`__ uses the script __`libs/encoding_cp932.js`__ which contains the encoding / decoding tables for the CP932 encoding. These tables have been generated from the Unicode file _http://unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP932.TXT_ which provides a mapping between Unicode code points and their encoding in 1 or 2 bytes in cp932
- this JS script has been generated by __`scripts/make_encoding_js.py`__ developed for this specific encoding, but it could be used for other encodings if necessary

I tested these scripts with this example:
```python
jp = "私は今本を読んでいます。"
b = jp.encode('cp932')
assert b == b'\x8e\x84\x82\xcd\x8d\xa1\x96{\x82\xf0\x93\xc7\x82\xf1\x82\xc5\x82\xa2\x82\xdc\x82\xb7\x81B'
assert b.decode('cp932') == jp
```

Can you make a few tests and report if they work as expected ?

**Comment by sakurai-youhei** [comment]
@PierreQuentel Thank you very much for your complementation in code base!

I tried to poke a couple of corner cases like followings but I haven't succeeded to figure out any problematic cases. It looks working pretty fine for my use cases. :)

```python
assert b"\xEF\xBD\x9E".decode("utf-8").encode("cp932").hex() == '8160'  # ～
assert "ー ソ 十 表".encode("cp932").hex() == '815b20835c208f5c20955c'
```

**Comment by PierreQuentel** [comment]
Thanks, I am closing the issue then.
