### ISSUE TITLE
STDLIB optimalization

### ISSUE THREAD

**Issue by lovasb** [brython-dev/brython#1547]
Hi,

I tried to use the module optimalization tool of the Brython cli. Created one folder, copied brython_stdlib.js into. Created one Python file with the following content:

>   print('Hello world')

After runned:

> brython-cli --modules

The created brython_modules.js file is 144B.

Modified the Python file:

>   from functools import partial
>   print('Hello world')

The generated brython_modules.js file size is 2,3MB. If I check the content of the generated file, then I see for example the email module in it, which I didn't use.

Is there any chance to slim the output file more?

Thanks forwards,
Bence

**Comment by PierreQuentel** [comment]
You are right, but unfortunately there is no easy solution to this problem.

`brython-cli --modules` generates a list of the modules that are imported by __`functools`__, then all the modules that are imported by the modules imported by __`functools`__ and so on. In the end you have scripts in the __`email`__ package because:

__`functools`__ imports __`collections.namedtuple`__
__`collections`__ imports __`heapq`__
__`heapq`__ _may import_ __`doctest`__
__`doctest`__ imports __`pdb`__
__`pdb`__ imports __`pydoc`__
__`pydoc`__ imports __`email.messages`__

When you run `from functools import partial` all these scripts are not imported (__`heapq`__ doesn't actually import __`doctest`__), but at the time when `brython-cli --modules` is executed it's not possible to know which modules will be actually imported, it has to include them all.

**Comment by lovasb** [comment]
Dear Pierre,

Thanks for your answer. As I see the problem (the heapq module imports doctest in runtime if needed). I go through on the list_modules.py, and try to figure out which solution would be good for me.

I created a small Django - Brython bindig application (https://lovasb.com/projects/django-brython/), which can help to start the Pythonic frontend development. It would be great to integrate a "bundler" into it.

**Comment by lovasb** [comment]
Dear Pierre,

I'd like to integrate the Brython's module creation to Django static file system. I made some little changes to make list_modules.py reusable: https://github.com/brython-dev/brython/pull/1548
