### ISSUE TITLE
TypeError('unsupported callable')

### ISSUE THREAD

**Issue by bkyf** [brython-dev/brython#1585]
Hi,

If I try to call `inspect.getfullargspec` on a builtin method Brython returns a _**TypeError('unsupported callable')**_. However, with custom funtions, inspect.getfullargspec, works fine.

See an example below:
```
import inspect

def test(a):
    print(abs(a))
    
print(inspect.getfullargspec(test))
# returns: "FullArgSpec(args=['a'], varargs=None, varkw=None, defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})"

print("__________")

print(inspect.getfullargspec(__builtins__.abs))
# and
print(inspect.getfullargspec(abs))
# both trhow: 
# "File VFS.inspect.py, line 1132, in getfullargspec
#    raise TypeError('unsupported callable')from ex
# TypeError: unsupported callable"
```

**Comment by PierreQuentel** [comment]
@bkyf 
Thanks for reporting this issue. Unfortunately, by looking at the code of module __`inspect`__, function `getfullargspec()` uses the __`ast`__ module, which is not (yet) available in Brython because it's written in C in the CPython standard library. I am sorry to have to close the issue with the "wontfix" label :-(
