### ISSUE TITLE
print(object) returns [Object object] instead of __str__ result

### ISSUE THREAD

**Issue by pamelafox** [brython-dev/brython#1626]
Replicate with the following code:

```
class Lamb:
    species_name = "Lamb"
    scientific_name = "Lambius lambalot"

    def __init__(self, name):
        self.name = name
    
    def __str__(self):
        return "🐑 : " + self.name
        
lil = Lamb("lil")
print(str(lil))
print(lil)
```

The first print() successfully prints out the expected '🐑 : lil' but the second one prints out [Object object]. That is not expected behavior according to the docs and my Python3 interpreter (and looks suspiciously like a JS object! :).

**Comment by PierreQuentel** [comment]
Thanks @pamelafox !

I had wanted to change the implementation of Python strings for a long time and this issue was the opportunity to do so. Previously strings that include characters in the Supplementary Plane were implemented as instances of a specific class and not as Javascript strings, because their Javascript representation as strings has length 2 instead of length 1 in Python.

In this commit, all strings are implemented as Javascript strings, and the methods of the __`str`__ class are able to handle all characters, including the little 🐑 ;-)

**Comment by pamelafox** [comment]
Ah, it broke due to my use of emojis! I see, that makes sense, thanks for fixing this and my other bug! We use brython heavily for our 1000 person class here at UC Berkeley.
