### ISSUE TITLE
__name__ is __main__0

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#163]
In the following test code,
   
    <script type="text/python3">
    from browser import window
    window.alert(__name__) 
    </script>

The alert reports "\__main__0" for this example (Brython 3.1.1). The previous version reported "\__main__". 

I have seen another instance where the value reported is "\__main__92".

The expected value is "\__main__".

**Comment by PierreQuentel** [comment]
If there are several Python scripts in the same page, each one has its own namespace, so a different `__name__`

**Comment by tiggerntatie** [comment]
Thank you for clarification. I see now (I think) that this is a consequence of the big namespace changes that resulted from dealing with #121?

I have a few questions:

Does this namespace change *require* that each script have a distinct value for \__name__? It is not clear to me that there is a reason why each namespace can not have its \__name__ value be simply \__main__.

The problem that this raises is simple: the common method of writing test code that executes when a module is executed rather than imported:

    if __name__ == "__main__":
        do something..

will not work under this system. I am trying to allow, within reason, code that executes in multiple environments.

2. Would you prefer that inquiries of this nature (e.g. "when I do this obvious thing, something 'wrong' happens..") be posted to the Google group before creating a Github issue? I'm not sure to go with my problems...  

Thank you for this Brython.. it is amazing work!

**Comment by PierreQuentel** [comment]
Eric,

I realize that my answer to issue #163 was a little rough, sorry about that.

I can't give a general answer to where to ask questions : if users think
that something is an issue, the tracker is the right place to ask, even if
the "something" is actually a feature. The advantage of posting to the
Google group is that more people read it, and that it's easier to search (I
see that you posted the above message on github, but I can't find it on the
brython-dev site).

Anyway, I understand the problem you raise with the common test "if
__name__=='__main__'". I have changed the naming of scripts in the commits
referenced above :

- if a Python script has an attibute "id", it is used as the module name
- otherwise, the module name is "__main__" for the first script (instead of
"__main__0"), then "__main__0", "__main__1" etc.

With these changes, you can call several modules with the same name, by
setting their attribute "id"

Is this ok for you ?


2015-03-31 23:52 GMT+02:00 Eric Dennison <notifications@github.com>:

**Comment by tiggerntatie** [comment]
Pierre, thank you for elaborating.

I removed my original reply because I realized that I had not kept up with all of the recent changes made to directory structure and so on as I moved from 3.0.2 to 3.1.1, and I wanted to give more thought to the actual impact that this issue has on me and whether a work around is a problem. 

I also wanted to repost it on the Google group forum, because it is more of a discussion at this point.

Having said that, your solution sounds like a great compromise and one that will work well for what I am trying to do. Thank you!
