### ISSUE TITLE
cannot import name ajax

### ISSUE THREAD

**Issue by lix2k3** [brython-dev/brython#1636]
Tried 'from browser import ajax' using the last 3 point versions of the library.  I get the same error each time:

Uncaught cannot import name 'ajax'

**Comment by PierreQuentel** [comment]
@lix2k3 

Do you access the HTML page through a local web server, or by opening it with the browser's File / Open menu ?

**Comment by PierreQuentel** [comment]
I am closing the issue for now. If you have more information don't hesitate to reopen it.

**Comment by d-flood** [comment]
I am also having trouble importing ajax.

I am accessing the HTML page through the django local test server.


```python
from browser import document, alert, html

print('imported document, alert, and html')

from browser import ajax

print('imported ajax')
```

The log output of this is:

imported document, alert, and html

brython.js:9273 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
$download_module @ brython.js:9273
import_py @ brython.js:9320
exec_module @ brython.js:9475
t @ brython.js:6652
o @ brython.js:6656
e.import_hooks @ brython.js:14146
$B.$__import__ @ brython.js:9583
B @ brython.js:6941
$B.$import @ brython.js:9643
eval @ VM5599:21
e.loop @ brython.js:5363
$B.run_script @ brython.js:5175
e.loop @ brython.js:5371
s.onreadystatechange @ brython.js:5336
XMLHttpRequest.send (async)
e.ajax_load_script @ brython.js:5337
e.loop @ brython.js:5371
$B.parser._run_scripts @ brython.js:5231
$B.parser.brython @ brython.js:5158
onload @ (index):19
brython.js:9274 GET https://cdn.jsdelivr.net/npm/brython@3.9.0/Lib/browser/ajax.py?v=1618590626707 404
$download_module @ brython.js:9274
import_py @ brython.js:9320
exec_module @ brython.js:9475
t @ brython.js:6652
o @ brython.js:6656
e.import_hooks @ brython.js:14146
$B.$__import__ @ brython.js:9583
B @ brython.js:6941
$B.$import @ brython.js:9643
eval @ VM5599:21
e.loop @ brython.js:5363
$B.run_script @ brython.js:5175
e.loop @ brython.js:5371
s.onreadystatechange @ brython.js:5336
XMLHttpRequest.send (async)
e.ajax_load_script @ brython.js:5337
e.loop @ brython.js:5371
$B.parser._run_scripts @ brython.js:5231
$B.parser.brython @ brython.js:5158
onload @ (index):19
brython.js:9279 Error 404 means that Python module browser.ajax was not found at url https://cdn.jsdelivr.net/npm/brython@3.9.0/Lib/browser/ajax.py
brython.js:6308 Traceback (most recent call last):
  File http://127.0.0.1:8000/appex/__main__ line 5, in <module>
    from browser import ajax
ImportError: cannot import name 'ajax'
$io.write @ brython.js:6308
h @ brython.js:5488
e.handle_error @ brython.js:5382
e.loop @ brython.js:5369
$B.run_script @ brython.js:5175
e.loop @ brython.js:5371
s.onreadystatechange @ brython.js:5336
XMLHttpRequest.send (async)
e.ajax_load_script @ brython.js:5337
e.loop @ brython.js:5371
$B.parser._run_scripts @ brython.js:5231
$B.parser.brython @ brython.js:5158
onload @ (index):19
brython.js:6308 Traceback (most recent call last):
  File http://127.0.0.1:8000/appex/__main__ line 5, in <module>
    from browser import ajax
ImportError: cannot import name 'ajax'
$io.write @ brython.js:6308
h @ brython.js:5488
e.handle_error @ brython.js:5382
e.loop @ brython.js:5371
s.onreadystatechange @ brython.js:5336
XMLHttpRequest.send (async)
e.ajax_load_script @ brython.js:5337
e.loop @ brython.js:5371
$B.parser._run_scripts @ brython.js:5231
$B.parser.brython @ brython.js:5158
onload @ (index):19
brython.js:5384 Uncaught cannot import name 'ajax'
    at Object._b_.ImportError.$factory (eval at $make_exc (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:276216), <anonymous>:1:4204)
    at Object.$B.$import (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:354559)
    at eval (eval at e.loop (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:167880), <anonymous>:21:21)
    at Object.e.loop (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:167911)
    at $B.run_script (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:160581)
    at e.loop (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:168244)
    at XMLHttpRequest.s.onreadystatechange (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:167262)
    
   I am able to edit the HTML and send alerts, but I cannot get ajax working. What might I be doing wrong?

Thank you for any help!

**Comment by PierreQuentel** [comment]
@d-flood You probably haven't loaded __`brython_stdlib.js`__ in the page.

**Comment by d-flood** [comment]
Indeed, I did not do that!

Sorry, I misunderstood when to import the standard library. 

Thanks for clearing that up for me, I appreciate it.
