### ISSUE TITLE
marshal.dump raises AttributeError exception

### ISSUE THREAD

**Issue by rayluo** [brython-dev/brython#1640]
Stumbled upon this on Brython 3.9.1

```python
import marshal
marshal.dump
```

It would result in an exception:

```
AttributeError: dump
```

Question 1: Is that a bug? I do see [its reference in Brython's code base](https://github.com/brython-dev/brython/blob/3.9.1/www/src/Lib/test/sortperf.py#L31) but that is a test path in Python, which I do not know whether it was actually run and tested.

Question 2: How shall we interpret the "Brython-specific" column of this [table of "Brython distribution vs CPython 3.9"](https://brython.info/static_doc/en/stdlib.html)? Does it mean the modules in such a column are only partially implemented? Currently the `marshal.js` exists in this column.

**Comment by PierreQuentel** [comment]
The __`marshal`__ module in Brython is a very minimal implementation, mostly there to avoid errors when a program imports it. It relies on the Javascript JSON object for serializing and deserializing, as such it does not support all the types supported by the CPython module, and does not even try to respect the format, which is undocumented anyway.

In the commit referenced above I have added function `dump()` (and not `load()` as written in the commit message...). I did not include it so far because writing on disk is not supported, but this version can be used with an argument `file` that supports reading/writing bytes.

Writing a full CPython-compatible version of __`marshal`__ would be much work for little benefit : the module is seldom used for serializing (__`pickle`__ or __`json`__ are much more popular), and its use for CPython code is not relevant in Brython.

The "brython-specific" modules in the table can be 2 different things:
- modules that exist both in the Brython and CPython stdlibs, but are implemented differently in Brython (pure-Python version of C modules, or Python modules with slight adaptations for compatibility with Brython or the browser environment)
- modules that only exist in Brython, such as __`interpreter`__ or the __`browser`__ package

**Comment by rayluo** [comment]
Thanks for the detailed response, Pierre!

I agree with you, `marshal` is hardly used. I never use it in my projects. Recently I tried to use a library and that library somehow references `marshal`. I'll test that again soon to see how our latest commit works. If necessary, I might fork that library and switch it from `marshal` to `pickle`. :-)

Regarding the "brython-specific" modules, I believe you are looking into this from the implementation standpoint. A module implemented differently could mean it runs slower, which is understandable and fine. By the way, last time we found out that the module `configparser` (and/or its dependency `re` module) also run noticeably slower, but they are currently marked as "files in both distributions" column. That makes me interpret the "brython-specific" column as about API-compatibility.

I think, the developers using Brython care more about whether a module shipped in Brython is API-compatible with the original one in CPython. So, it would be more valuable to rename the "brython-specific" column into "Not fully compatible with CPython" (we do not even have to mention `interpreter` and `browser` package in such column, because they do not have compatibility concern). By the way, it would be helpful to have the missing functions implemented as `def load(...): raise NotImplementedError("Not yet implemented in Brython")` in the Brython code base, so that people do not even have to cross-reference the docs.
