### ISSUE TITLE
children returns all nodes, not only elements

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#1657]
Hello,

In Brython, the `children` attribute of a HTML Element returns all child nodes, while JS `children` returns only elements (cf. https://developer.mozilla.org/en-US/docs/Web/API/Element/children).

This is confusing and Brython should match JS behaviour.

To have all nodes, JS DOM Nodes have the `childNodes` method, this could be named `child_nodes` in Brython.

I've tried to use `list(some_elt)` and the result is the same as `some_elt.children`. It seems that there is currently no way to have only elements (Brython `children` version being overriding the JS version).

Here is a code to reproduce the issue (test with Brython `3.9.1` using https://www.brython.info/tests/editor.html):

```python

from browser import document
from browser.html import DIV

root_elt = DIV(DIV("some text") +  "text node")
document <= root_elt

print(len(root_elt.children), root_elt.children)
assert len(root_elt.children) == 1
```

As show with the assertion, expected result should be 1, not 2.

Thanks.

**Comment by andy31lewis** [comment]
I see from [this page](https://brython.info/static_doc/en/attributes.html) that element.children is one of the convenience properties defined by Brython. Obviously it acts as a wrapper for the DOM childNodes property.
But because it has the same name, it hides the DOM children property.  So maybe the simplest solution is just to rename the Brython convenience property (maybe to child_nodes as suggested)? Then the DOM children property would become available, because it wouldn't be hidden.

Andy

**Comment by PierreQuentel** [comment]
Merci Jérôme ! You are right, it's better to be compliant with the specification. I have updated the documentation.

Note however that this is described in the DOM (or Web API) specification, and not dependant of any language; in other words, it is _not_ the "JS behaviour". I know it's easy to make the confusion because everything is mixed in the same namespace inside JS programs...

**Comment by goffi-contrib** [comment]
thanks for the quick fix @PierreQuentel and you are right about Web API, my bad (furthermore, it makes specially sense in the case of Brython).
