### ISSUE TITLE
The error: "bad character range [object Object]" catched while i import the "requests" module

### ISSUE THREAD

**Issue by k1916** [brython-dev/brython#1670]
Whenever I import a third-party library, such as requests, pandas and so on, there will be errors. I have used the "brython-cli --modules" command to generate the JS file and import it into the HTML file.
Just like this:
![image](https://user-images.githubusercontent.com/60846729/117127293-7d2e8100-adce-11eb-908a-de057a7afc32.png)

**Comment by PierreQuentel** [comment]
@k1916 
Thanks for reporting this, the error was a side effect of the replacement of the __`re`__ module in the latest release. The commit referenced above should fix it.

But trying to import libraries such as __`requests`__ and __`pandas`__ will fail, because they use modules that are not written in Python. Brython cannot handle programs written in C.

Moreover, __`requests`__ is used to send HTTP requests, and the support for this in browsers is limited because of the "same origin" policy : you can only send Ajax calls, and they will fail if they are not in the same domain as the calling page, or if the server doesn't accept cross-origin requests (most of them don't).
