### ISSUE TITLE
json not recognising NaN, Infinity or -Infinity

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1673]
Hi again

The CPython `json` module recognises `NaN`, `Infinity` and `Infinity` in files or strings and converts them to the Python equivalents `nan, `inf` and `-inf`.  Brython isn't doing that at the moment:

```python
import json

L = json.loads("[NaN, Infinity, -Infinity]")
print(L)
```
Output from CPython: `[nan, inf, -inf]`
Output from Brython:
`Exception: <Javascript SyntaxError>: JSON.parse: unexpected character at line 1 column 2 of the JSON data`

(Interestingly, `json.dumps([nan, inf, -inf])` **does** give the correct result `"[NaN, Infinity, -Infinity]"`, but the round trip doesn't work.)

Thanks!

Andy

**Comment by PierreQuentel** [comment]
I am afraid that this issue can't be fixed. These values are not in the strict JSON specification, and the CPython module has an option `allow_nan` that produces `NaN, Infinity, -Infinity` when set (the default), but raises a `ValueError` otherwise.

I have documented this difference with CPython in the [syntax](https://github.com/brython-dev/brython/blob/master/www/doc/en/syntax.md) page.

**Comment by andy31lewis** [comment]
Thank you, Pierre.
It is not a major problem, so I will close this issue.
Andy
