### ISSUE TITLE
Bug with `help`

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1682]
When I type `help(pickle.dumps)` in the Brython console I get nothing. When I type it in CPython, I get some help text.

**Comment by Froggo8311** [comment]
It seems that any help() argument uses the standard output, which is set to `console.log` in JS. Try going to the DevTools console and seeing any output there.

**Comment by PierreQuentel** [comment]
Hello Ram,

Commit 9f72738bb4fedaececee0b8af17cd41f88beb73a introduces a new implementation of `help()`. An assumed difference with the standard implementation is that for standard lib modules, instead of writing text content to the REPL console, a new window is opened with the Python docs page.

I am closing this old issue. Feel free to comment if necessary.
