### ISSUE TITLE
Python version should be visible

### ISSUE THREAD

**Issue by cool-RR** [brython-dev/brython#1683]
Which Python version does Brython support? This version number should be visible on the Readme and website.

**Comment by andy31lewis** [comment]
As I understand it, the version numbers correspond, so Brython 3.9 is equivalent to Python 3.9, Brython 3.8 is equivalent to Python 3.8, etc.

(The third (patch) numbering does not correspond because that is for bug-fix releases and Python and Brython won't have the same bugs! For example Python recently released a 3.9.4 two days after releasing 3.9.3 because of a bug they found in 3.9.3.)

Hope that helps,

Andy

**Comment by cool-RR** [comment]
Whether this is the actual policy or not, it should be made clear. And in
any case, the main page should explicitly say which Python version we
support.

**Comment by PierreQuentel** [comment]
Brython uses the standard for Python implementations (cf. [PEP 421](https://www.python.org/dev/peps/pep-0421/)):
`sys.version` is the Python language version
`sys.implementation` is the Brython version, with attributes `name` and `version`

Since Brython 3.8.0, the major/minor version numbers are the same for Python and Brython.

**Comment by cool-RR** [comment]
Good, but this needs to be immediately visible to people who are casually
looking at the main page of the website and the GitHub readme, because this
is one of the key considerations people have when choosing whether to use a
python package (or in this case an alternative implementation.)

**Comment by PierreQuentel** [comment]
Done in commit b03dc133d014cbfa8855afdf27c26790452f25b1

**Comment by rayluo** [comment]
> Done in commit [b03dc13](https://github.com/brython-dev/brython/commit/b03dc133d014cbfa8855afdf27c26790452f25b1)

Should this issue be closed, then? So that we can shrink the open issues list a little bit...

**Comment by cool-RR** [comment]
Sure.
