### ISSUE TITLE
__rmul__ should be used when right operand is subclass of left operand

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1686]
Hello Pierre

(I admit this is a rather obscure use case ;-) )

In the Python documentation, https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types,
in a box below the list of `__rxxx__` reflected methods, we find:

> Note: If the right operand’s type is a subclass of the left operand’s type and that subclass provides a different implementation of the reflected method for the operation, this method will be called before the left operand’s non-reflected method. This behavior allows subclasses to override their ancestors’ operations. 

The following code is a minimal example, :
```python
class Squared(float):
    def __mul__(self, other):
        return self**2 * other

    def __rmul__(self, other):
        return self**2 * other

x = Squared(4)
y = 3
print(x * y)
print(y * x)
```
In CPython, this gives `48.0` in both cases;  in the first case, x's `__mul__` is looked at first because x is on the left.  In the second case x's `__rmul__` is looked at first, because of the rule I quoted above.

In Brython, the first case gives `48.0` as expected, but the second case gives `12.0`; I assume this is because Brython looks first at y's `__mul__` to see whether it can handle x; it finds it can (since x is a subclass of  `float`) and so it uses that.

Thank you as always,

Andy

**Comment by PierreQuentel** [comment]
Hello Andy,

Thanks for the report, I was not aware of this rule.

In fact, it was not applicable to your example because `Squared` is not a subclass of `int`; it failed for another reason, an incorrect implementation of most of the special methods such as `__add__` or `__radd__` for classes bool, int, float, complex : instead of returning `NotImplemented`, the previous implementation tried the "reflected method".

In commit d5b6128 I fixed these methods and your example worked as expected.

Commit 73bad09 actually fixes the bug, making the following example work as in CPython:

```python
class Squared(int):
    def __mul__(self, other):
        return self**2 * other

    def __rmul__(self, other):
        return self**2 * other

x = Squared(4)
y = 3
assert x * y == 48
assert y * x == 48
```

**Comment by andy31lewis** [comment]
Hi Pierre,

You're right, I should have used `x = Squared(4.0)` and `y = 3.0` to properly illustrate the rule I was referring to!

But anyway, thank you for fixing the problem in both cases.

Andy
