### ISSUE TITLE
Simple syntax for blocking efficiently

### ISSUE THREAD

**Issue by kmindspark** [brython-dev/brython#1739]
Hi,
The application I am developing for requires users to write Python code, which means I want to give them a very simple code interface - aka not requiring async/await knowledge from them. However, they need to be able to call a function that blocks for a given number of seconds, and currently the way I do this is with a busy wait. However this is bad for performance and leads to massive CPU utilization. Are there any good ways I can allow users to write simple code such as wait(10) and internally handle that as a non-busy wait?

**Comment by kmindspark** [comment]
```
from browser import aio, timer

def compute_val(x, y):
    return x + y
    
async def a_function_which_sleeps(dist):
    print('starting to sleep')
    await aio.sleep(dist)
    print('ending my sleep')

# ONLY THIS BELOW FUNCTION IS WHAT THE USER SEES
async def main():
    """This function will be called during execution."""
    x = compute_val(2, 1)
    print(x)
    await a_function_which_sleeps(x)
    print(f"moved robot")

    result = await aio.sleep(2)
    print(f"future awaited")


aio.run(main())
```
For example, I want to execute the equivalent of the above code when the user types the following.
```
def main():
    """This function will be called during execution."""
    x = compute_val(2, 1)
    print(x)
    a_function_which_sleeps(x)
    print(f"moved robot")

    result = aio.sleep(2)
    print(f"future awaited")
```

@PierreQuentel would appreciate your input on this.

**Comment by PierreQuentel** [comment]
By design, browsers do not support other blocking functions than `alert(), prompt()` and `confirm()`; it is impossible to write blocking functions in Javascript.

So, no, there is no equivalent of `time.sleep()`; you have to write asynchronous code. Your function `main()` should be defined as `async def main()` and the function that sleeps should be awaited (`await a_function_that_sleeps(x)`).

I am conscious that this is a limitation of Brython compared with CPython (it is documented [here](https://www.brython.info/static_doc/fr/syntax.html)), but there is nothing we can do about it.
