### ISSUE TITLE
How to deal with server not serving *.py files?

### ISSUE THREAD

**Issue by coproc** [brython-dev/brython#1748]
I am trying to deploy a Brython project on a server that responds with "500 Internal server error" when requesting a *.py file. Renaming the file to *.txt and referencing it like that (`<script type="text/python" src="overview.txt"></script>`) works, but using the Python `import`-statement for one's own modules does not work this way. Putting all code into one *.txt file works, though ... Is there an easier solution to this problem?

**Comment by PierreQuentel** [comment]
Interesting, thanks !
In the commit referenced above I have added an option "python_extension" to pass to function brython() to specify another extension than ".py".
For instance, `brython({python_extension: '.bry'})` will use this extension for imports.
Is this ok ?

**Comment by rayluo** [comment]
> For instance, brython({python_extension: '.bry'}) will use this extension for imports.
Is this ok ?

It would not be a bad thing to have such an alternative. It may come in handy, when the Brython project contains only a few .py files. It might not be practical to rename all .py to .bry if a project (and/or its vendored dependency) contains tons of .py files.

@coproc , my Apache knowledge has been rusty, so please take my following guess with a grain of salt... Could it be possible that you were serving your Brython project in Apache's CGI mode, so that Apache was trying to run your .py scripts on the server-side? As a rule of thumb, serving Brython project as a pure static front-end website would work fine. FWIW, you can do it with Github Pages, which is completely free. See an example [here](https://rayluo.github.io/brython-project-template/).

**Comment by coproc** [comment]
@rayluo I do not have any control over the server as it is run by a commercial provider. All I can do is uploading files.

**Comment by coproc** [comment]
> For instance, `brython({python_extension: '.bry'})` will use this extension for imports.
> Is this ok ?
sounds perfect. I will try it.

**Comment by PierreQuentel** [comment]
I have included the change in the latest release (3.9.6).
