### ISSUE TITLE
Documentation about asyncfs is outdated. What to read instead?

### ISSUE THREAD

**Issue by mkondratyev85** [brython-dev/brython#1752]
Hello Pierre! As you stated in the answer to this issue: https://github.com/brython-dev/brython/issues/1749, the module asyncio was removed and replaced by browser.aio. 

So examples from this [page](https://brython.info/static_doc/en/asyncfs.html) can't be reproduced. I tried to import asyncfs from browser.aio but it looks like there is nothing similar to asyncfs inside browser.aio. 

Is there a way to save a file locally in the modern version of brython?

**Comment by PierreQuentel** [comment]
I have removed this outdated file from the server.

Saving a file locally is not possible with code like `with open(f, 'w'): f.write(s)` because of the browser's "sandboxed" execution model.

There is an example in the [demo page](https://brython.info/demo.html), section "select, read and save a local file" that shows how you can use the browser's "save" menu.

Another solution to save data locally is to use local storage or indexedDB.
