### ISSUE TITLE
partial functions cannot be called from javascript

### ISSUE THREAD

**Issue by louisabraham** [brython-dev/brython#1866]
```
window.test = partial(print, 1)
```

`window.test()` works from python but not from js: I get `Uncaught TypeError: test is not a function`.

**Comment by louisabraham** [comment]
replacing `from functools import partial` with the sample code from the [docs](https://docs.python.org/3/library/functools.html#functools.partial) solves the issue.

**Comment by PierreQuentel** [comment]
Thanks for reporting this @louisabraham.

Brython is designed to be able to use Javascript programs / frameworks from within Python code, but not the other way round (using Python code from within JS programs).

For this particular case:

- in module **`functools`**, `partial` is a Python class, and `partial(print, 1)` is an instance of this class, not a function. Instances happen to be callable because `partial` has a method `__call__()`
- in the translation from Python to Javascript, a Python call like `f()` is not translated to Javascript `f()` but to `__BRYTHON__.$call(f)()`, where `$call` transforms a Python callable to a Javascript function. Here, `$call()` uses `partial.__call__`

You _can_ make your code work with `__BRYTHON__.$call(window.test)()`, but it requires knowing Brython internals, and the internals are liable to change between releases.

The best advice I can give is not to expect too much from calling Brython from JS : it might work by chance in some cases, but not in others.
