### ISSUE TITLE
[ISSUE] Import "browser" could not be resolved

### ISSUE THREAD

**Issue by Nico1945** [brython-dev/brython#1878]
Hello 
I currently have 2 files in the same directory.
- index.html
- main.py

"Index.html" code is as follows:

`<!doctype html>`
`<html>`

`<head>`
`    <meta charset="utf-8">`
`    <cript type="text/javascript" src="brython.js"></script>`
`    <script type="text/javascript" src="brython_stdlib.js"></script>`
`    <script type="text/python3" src="main.py"></script-->`
`</head>`

`<body onload="brython(1)">`
`    <script type="text/python">`
`    from browser import document`
`    document <= "Hello"`
`    </script>`
`</body>`

`</html>`

"main.py" code is as follows (there is only 1 line of code. It is for trial):

`from browser import document`

I am working with Visual Studio Code.
Python3 and Brython3.10.4 are installed on my Mac.

Visual Studio Code is giving me the following error message:
_Import "browser" could not be resolved_

The Python 3 interpreter is correctly linked to Visual Studio Code, 
And I also checked that Brython is correctly installed in Python 3 "bin" director (it is!).

Could someone explain me why I am having the "Import browser" error ?

Thanks a lot.

**Comment by PierreQuentel** [comment]
Hello,

I am not familiar with Visual Studio but I suppose that it scans the CPython directory to see if `import browser` succeeds. Since this module is Brython-specific, it fails.

I don't know if there is a workaround. In any case it's not a Brython issue, so I am going to close it.

Thanks for the report anyway !

**Comment by Nico1945** [comment]
Hello Pierre
Thanks for your reply.

Two last questions:
1/ Would you have an example of code of what I want to do?
2/ In the issue is Visual Studio Code, then I will change the coding environment. On your side, could you please tell me which coding environment you are using ? I would try with that one.

Thank you.

**Comment by PierreQuentel** [comment]
There is a typo in your code:
```xml
<script type="text/python3" src="main.py"></script-->
```
should end with `</script>`, not `</script-->`. Otherwise the example looks good.

I develop and test Brython with [TedPy](https://github.com/PierreQuentel/TedPy), an editor I wrote myself - it's such fun to reinvent the wheel ! You can give it a try but it's more a toy than anything else ;-)

**Comment by Nico1945** [comment]
Thank you Pierre.
My final goal is to develop an web application that will read Yahoo Finance data. 
I was wondering if Brython would work with Yahoo_fin API. I have tried and it seems it doesn’t work on my side. 
May I ask you to give it a try? 
I am just thinking my coding environment is not appropriate. I am also working on Mac.

Thanks a lot.

**Comment by PierreQuentel** [comment]
Running in a browser, Brython scripts can only send Ajax calls to urls, and it seems that the Yahoo site doesn't support cross-origin requests : I get the usual error message

```
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://finance.yahoo.com/quote/NFLX/balance-sheet?p=NFLX. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. Code d’état : 200.
```

So I'm afraid you won't be able to use Yahoo_fin :-(

**Comment by Nico1945** [comment]
Understood. Thanks a lot Pierre.
I will then search for another way.

**Comment by jabezborja** [comment]
VSCode is unusual with Brython's import implementation as instead of having Brython on a virtual environment where the VSCode checks for imports, it's on the HTML itself.

I think the only way to resolve `Import "browser" could not be resolve` in VSCode is to create a brython-specific linter extension on VSCode.
