### ISSUE TITLE
Event binds seem to overwrite each other

### ISSUE THREAD

**Issue by vlanore** [brython-dev/brython#1892]
Hello!

I'm new with brython and I'm trying to generate a set of links, where each link binds to a different callback.
The issue is that binds seems to overwrite each other and all links call the last callback declared.
When I run the following code :

```python
def a():
    document <= "a"

def b():
    document <= "b"

for x in [a, b]:
    name = x.__name__
    document <= html.A(name, href="javascript:void(0);", id=name)
    document <= "  "
    document[name].bind("click", lambda _: x())
```

then links 'a' and 'b' both call `b`, where I expected link 'a' to call `a` and link 'b' to call `b.`
If I reverse the list to `[b, a]` then both links call `a`.

Is this a bug or am I doing something wrong?

I'm running brython 3.10.4, installed with `pip` and run in chrome with `http.server`.

Thanks for your time and for the great project 😄

**Comment by PierreQuentel** [comment]
Bonjour Vincent,

Although the behaviour is not intuitive, it's not a bug, that's how lambdas in loops work in Python (see for instance [this stackoverflow post](https://stackoverflow.com/questions/2295290/what-do-lambda-function-closures-capture) for an explanation).

You can achieve the expected behaviour by writing the lambda this way:
```
document[name].bind("click", lambda _, x=x: x())
```

**Comment by vlanore** [comment]
Oh, my bad, I should have know that 😅 
I confirm that it works on my end with the proposed fix.

Thanks a lot for the lightning fast answer.
