### ISSUE TITLE
Support Tatsu

### ISSUE THREAD

**Issue by mach881040** [brython-dev/brython#1916]
Tatsu is a Pure Python library:

https://github.com/neogeny/TatSu

It contains the following construct, which Brython does not understand:

https://github.com/neogeny/TatSu/blob/master/tatsu/infos.py#L25

```python
name: str|None = 'Test'
```

**Comment by mach881040** [comment]
Any chance of Tatsu support in the next release?

**Comment by PierreQuentel** [comment]
@mach881040 

I worked on this issue when you submitted it, but after the fixes referenced above, I found that there was an issue with a specific feature used by Tatsu (interaction between generators, context managers and garbage collection) which required important changes to the current Brython parser; and since I am working almost full time on a rewriting of the parser, I didn't put this issue on top of the list.

I can't guarantee how long it will take before I can resume work on it, but I keep it in mind.

**Comment by PierreQuentel** [comment]
The example on Tatsu's Github page now works: 

```python
GRAMMAR = '''
    @@grammar::CALC


    start = expression $ ;


    expression
        =
        | expression '+' term
        | expression '-' term
        | term
        ;


    term
        =
        | term '*' factor
        | term '/' factor
        | factor
        ;


    factor
        =
        | '(' expression ')'
        | number
        ;


    number = /\d+/ ;
'''


if __name__ == '__main__':
    import json
    from tatsu import parse
    from tatsu.util import asjson

    ast = parse(GRAMMAR, '3 + 5 * ( 10 - 20 )')
    print(json.dumps(asjson(ast), indent=2))
```

It is very slow, but I had such a hard time making it work that I give up trying to know why.
