### ISSUE TITLE
How to use brython with svelte

### ISSUE THREAD

**Issue by ElectriCherph** [brython-dev/brython#1922]

**Comment by Froggo8311** [comment]
What are you attempting to accomplish? You should be able to just do it using the same method you would do in HTML.

**Comment by PierreQuentel** [comment]
Would you be so kind as to explain what svelte is ?

**Comment by Froggo8311** [comment]
> Would you be so kind as to explain what svelte is ?

Svelte is an HTML-based language. I am not exactly sure of the benefits, but I do know that it provides the ability for non-javascript if-statements with elements (something along the lines of "if a value is true, show these elements, if not, show these instead", etc.) and it has the ability to have more advanced visual animation.

**Comment by mach881040** [comment]
^^ svelte is an AOT compiler + language that attempts to anticipate and pre-compile reactive patterns

**Comment by PierreQuentel** [comment]
Would you be so kind as to explain what an AOT compiler is ?

**Comment by mach881040** [comment]
Most compilers you are familiar with are AOT, ie, gcc. They just do the work ahead of time, and accept tradeoffs because they must, in a sense, predict the future.

**Comment by PierreQuentel** [comment]
I don't even remember the last time I used a compiler, and I don't know C. So I still don't understand what this issue is about.

**Comment by mach881040** [comment]
They are basically asking for a demo/prototyp of using svelte and brython, akin to the other reactive programming demos on the brython website.

**Comment by ennec-e** [comment]
[Svelte] is a new sleek web framework like ReactJS/VueJs/Angular and the like. Except it has some fresh ideas and seems to be gaining some popularity now. Proponents seem to like it being fast and light in production while being _easy to get started developing with_.

I don't understand much about web frameworks myself but I think the compiling they are referring to above is that Svelte pre-compiles everything to required vanilla JS + HTML rather than shipping the whole framework with the website. 

Demo of what I think OP was referring to https://svelte.dev/examples/else-blocks

[Svelte]: https://svelte.dev/

**Comment by PierreQuentel** [comment]
After a quick look at the documentation, I am convinced that Svelte and Brython cannot work together:
- with Svelte, developers write .svelte files with a specific "templating language", then the framework translates these files to HTML pages with Javascript inside. For each change in the source code, the Svelte-to-Javascript engine has to be run
- Brython translates Python code to Javascript inside existing HTML pages on page load. When code is changed, just reload the page

I am not saying that one approach is better than the other, just that the way they work make them incompatible.
