### ISSUE TITLE
lambda expression (sometimes!?) emits invalid javascript

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#195]
Trying to update to the latest Brython, I noticed that my test suite for brytly no longer passes.  If you look at this commit - https://github.com/glyph/brytly/commit/bedbf7add82ea65dba0c0f0ed0361b7fbb460378 - you can see that an apparently-equivalent expression, `def something(): ...` on the one hand and `something = lambda: ...` on the other, produce very different results.  the lambda expression version appears to produce invalid javascript, but I'm not sure how to debug exactly what it's emitting.

I spent quite a while trying to boil this down to a simpler case, but if I extract the code from the testing infrastructure that's running it, it doesn't seem to provoke the same buggy behavior.  I will continue testing but hints as to how to make it easier when things go wrong would be really appreciated.

To see it break,

```console
$ git clone https://github.com/glyph/brytly
Cloning into 'brytly'...
remote: Counting objects: 76, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 76 (delta 9), reused 0 (delta 0), pack-reused 53
Unpacking objects: 100% (76/76), done.
Checking connectivity... done.
$ cd brytly/
$ git submodule init
Submodule 'Brython' (https://github.com/brython-dev/brython) registered for path 'Brython'
Submodule 'Deferred' (https://github.com/glyph/deferred) registered for path 'Deferred'
$ git submodule update
Cloning into 'Brython'...
remote: Counting objects: 8832, done.
remote: Compressing objects: 100% (287/287), done.
remote: Total 8832 (delta 207), reused 0 (delta 0), pack-reused 8545
Receiving objects: 100% (8832/8832), 14.95 MiB | 1.70 MiB/s, done.
Resolving deltas: 100% (5749/5749), done.
Checking connectivity... done.
Submodule path 'Brython': checked out 'c8112fab7367430360d92a6d606fef2330d9893b'
Cloning into 'Deferred'...
remote: Counting objects: 171, done.
remote: Total 171 (delta 0), reused 0 (delta 0), pack-reused 171
Receiving objects: 100% (171/171), 54.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (85/85), done.
Checking connectivity... done.
Submodule path 'Deferred': checked out 'b634c621b3f2e831ad776cc0d969402e69869efc'
$ virtualenv .venv
New python executable in .venv/bin/python
Installing setuptools, pip, wheel...done.
$ .venv/bin/pip install -r requirements.txt 
Collecting klein (from -r requirements.txt (line 1))
Collecting twisted>=15.2.0 (from -r requirements.txt (line 2))
Collecting werkzeug (from klein->-r requirements.txt (line 1))
Collecting zope.interface>=3.6.0 (from twisted>=15.2.0->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./.venv/lib/python2.7/site-packages (from zope.interface>=3.6.0->twisted>=15.2.0->-r requirements.txt (line 2))
Installing collected packages: werkzeug, zope.interface, twisted, klein
Successfully installed klein-15.0.0 twisted-15.2.0 werkzeug-0.10.4 zope.interface-4.1.2
$ .venv/bin/python server.py 
```
then hit http://localhost:8192/test in a browser.

**Comment by PierreQuentel** [comment]
The bug was in py_utils.js, function $B.$lambda : the name for the local namespace for the lambda expression is built from the module name where the lambda is defined ; if the module is inside a package, the dots are replaced by an underscore ; the regular expression passed to replace() missed the "g" flag.

To find the bug : 

- in the tested HTML page I replaced `<script type="text/javascript" src="/www/src/brython.js"></script>` by the list of scripts (like in www/tests/index.html), so that traces added to the individual scripts like py_utils.js are taken into account when the test is run again
- to see how the lambda expression is translated I added a debug level : `<body onload="brython(10)">`
- the translation calls the function `$B.$lambda`. It is located in py_utils.js ; this is not documented, but a search in the Brython scripts should find it
- I added a few `console.log()` in this function, until I found that it was one of the lines

```
eval('var '+sc_id+'=env[i][1]')
```
that raised an exception, because a dot had not been translated to _

**Comment by glyph** [comment]
Thanks so much for the quick fix and the explanation!

**Comment by PierreQuentel** [comment]
By the way, the implementation of lambda and of comprehensions is terrible and very slow... It should use self-executing anonymous functions, instead of passing the Python source code to a function at run time.

**Comment by glyph** [comment]
For the moment, as long as it works for a demo, it's fine by me :).  The best optimization is the one that goes from "not working" to "working" - everything from there on out is negotiable :).

**Comment by jsbueno** [comment]
Cool - maybe this bug is what was making me unable to upgrade to a newer
Brython version - I will try again with git master.
