### ISSUE TITLE
s='</script>'  results in SyntaxError

### ISSUE THREAD

**Issue by shark-in-a-hat** [brython-dev/brython#1975]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <script type="text/javascript" src="brython_new.js"></script>
        <title id="title">Test</title>
        
    </head>    
    <body lang="en-US" onload="brython({debug:1, indexedDB:0})" >
        <script type="text/python">
            s='''</script>'''
        </script>
    </body>
</html>
```

Having </script> inside a string anywhere in the Python script results in a SyntaxError
```
SyntaxError: unterminated triple-quoted string literal (detected at line 1)
```
I'm guessing the parser see this as:
```
<script type="text/python">
s='''</script>
```

**Comment by PierreQuentel** [comment]
I understand that this might seem confusing, but it's not related to Brython, it's the expected behaviour of the browser's HTML parser: it sees a start tag `<script>`, then an end tag `</script>`, and sets the content of the script to what is between start and end, here the string `s='''`, which is invalid Python.

There is a similar Javascript error with HTML code like

```xml
<script type="text/javascript">
var s = "</script>"
</script>
```

I don't know if there are other workarounds but you can replace the code by
```python
s = '<' + '''/script>'''
```

**Comment by shark-in-a-hat** [comment]
Okay, got it. 
I'm no good with js, I didn't realise it's a HTML/javascript quirk and it took me a while to figure it out. 

Since I'm using the string as a template anyway, my workaround is 
```
s = '</{script}>' .format(script='script') 
```
