### ISSUE TITLE
Add async/await support?

### ISSUE THREAD

**Issue by roger-** [brython-dev/brython#210]
Now that Python 3.5 has support for them and ECMAScript 7 is (probably) gonna do the same, it would be great if we could start using the `async`/`await` keywords to implement asynchronous calls.

**Comment by olemis** [comment]
This is a very interesting feature I'm keen to implement sooner rather than later . Like [I said before](https://github.com/brython-dev/brython/issues/188#issuecomment-102416069) this might be useful to implement #188 .

**Comment by MetaMemoryT** [comment]
:+1:

**Comment by PierreQuentel** [comment]
This has been done in version 3.7.0rc1

**Comment by glyph** [comment]
This does not appear to work correctly.

Playing around in the REPL at https://brython.info/tests/editor.html?lang=en

```
import browser
import traceback
import asyncio
async def foo():
    browser.alert("Fetch...")
    request = asyncio.HTTPRequest("https://brython.info")
    response = await request
    browser.alert("Hooray! " + str(request is response))

asyncio.ensure_future(foo())
```

`await` should be resolving a future into its result (presumably an HTTP response?) not just returning the future.  It's not clear to me if anything useful is possible with this implementation of `await`.

**Comment by PierreQuentel** [comment]
I reopen this issue, it's true that the current implement is not really usable.

The main problem is that the CPython __`asyncio`__ module relies on _blocking functions_ (`run()`, `run_until_complete()`), and that such functions can't be defined in Javascript. Morevoer, it is not possible to define an event loop other than the implicit one provided by the browser.

In recent commits I have implemented `async` and `await` with the same Javascript keywords, and added a new module, __`browser.aio`__, which is designed as a replacement for __`asyncio`__. Currently the __`aio`__ module exposes 4 functions: 

- `get(url)` : returns a coroutine object that represents a GET request for the resource at location `url`
- `post(url[, data])` : same for POST request
For the moment, these objects have the same interface as Javascript's `fetch` built-in function; for instance the result of `await get(url)` is a coroutine object that has methods such as `text()` or `json()`.
- `sleep(seconds)` : a coroutine that waits for the specified number of seconds
- `run(coroutine[, onsuccess, onerror])` : a non-blocking function that runs the coroutine. Since it is non-blocking, if there are instructions after `run()`, the execution order is unpredictable. The _onsuccess_ and _onerror_ functions are called when the coroutine succeeds or fails.

With these functions, this code runs as expected: 
```python
from browser import document, html, window, aio

results = []

async def f(url):
    req = await aio.get(url)
    txt = await req.text()
    return (url, len(txt))

async def g(urls):
    document <= html.BR() + "wait 3 seconds..."
    await aio.sleep(3)
    for url in urls:
        document <= html.BR() + f"get page at {url}"
        r = await f(url)
        results.append(r)

def report(*args):
    for url, size in results:
        document <= html.BR() + f"file at {url}: {size} bytes"

document <= "Start..."
aio.run(g(["ajax.html", "clock.html"]), onsuccess=report)
```

This is still at a very early stage, I am still not comfortable with this way of programming; this post is for information, and a feedback request.

**Comment by PierreQuentel** [comment]
I have added support for `async with` and `async for`, and improved support for async/await-enabled Ajax requests.

I have also introduced `aio.event(element, event_name)` to support asynchronous-style event handling.

These features are now [documented](https://github.com/brython-dev/brython/blob/master/www/doc/en/aio.md). I think the issue can be closed.

**Comment by glyph** [comment]
🎉 Thanks, I’ve enjoyed playing with this!
