### ISSUE TITLE
Brython recent version cannot run on Midori

### ISSUE THREAD

**Issue by lefranco** [brython-dev/brython#2120]
Lubuntu 2210

brython-cli --version
 -> Brython version 3.11.0

sudo snap install midori
-> midori browser installed

run midori
go to site made with brython https://diplomania-gen.fr/ working fine with edge, safari, firefox, chrome

no page
CTRL + shift + I

three errors : 

SyntaxError: No identifiers allowed directly after numeric literal
brython.js:8021

ReferenceError: Can't find variable: __BRYTHON__
brython_modules.js:1

ReferenceError: Can't find variable: brython
onload diplomania-gen.fr:21

(no such errors at least on chrome/firefox)
Is midora missng a feature required by brython produces code ?

**Comment by PierreQuentel** [comment]
I had a similar bug report recently and it was because the browser did not support [Javascript BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt), and Brython has a few BigInt literals written like `1n`. 

I suspect very much that it is the same for this Midori browser. A Google search for "Midori BigInt" didn't help; if the browser has a console, try entering `1n`.
