### ISSUE TITLE
import datetime is very slow

### ISSUE THREAD

**Issue by lefranco** [brython-dev/brython#2124]
As the subject says.
(I do not if that qualifies as a bug, more a hint for improvements)
I have profiled all import times for all "customers" of a web site made in Brython and came to this conclusion.

**Comment by PierreQuentel** [comment]
As usual, it depends on what you call "slow".

On my 5-year old laptop (Windows 10, CPU @ 2.5 GHz, RAM 8 GB) :
- without **`brython_stdlib.js`** embedded in the page, `import datetime` takes 0.5s on Firefox and 1.4s on Chrome
- with **`brython_sdtlib.js`** and the indexedDB cache enabled (which is the default), the first run takes less than 1s and the next runs between 0.2 and 0.3s on both browsers

**Comment by lefranco** [comment]
With more or less the same computer I agree I get the same stats 
 **Import datetime... : 1335ms (8.97%)**
That is a great price...
Therefore I have planned to rewrite natively the functions I used in datetim and avoid importing it.

There is a more expensive import 
import enum
**import enum... : 3794ms (25.49%)**
I shall probably also get rid of that one.

**Comment by PierreQuentel** [comment]
Is there a reason why you don't include **`brython_stdlib.js`** ?

**Comment by lefranco** [comment]
Sorry, I probably was unclear.
Below is what I do, following some advices I got from the brython forum.

I compile offline using brython-cli make_modules
I upload on site the brython_modules.js
There is already the brython.js sitting on the site

My html page has :

### <script src="brython.js"></script>
<script src="brython_modules.js"></script>
<body onload="brython()">


<script type="text/python">
import index
</script>




I will do whatever loads the page the faster !

**Comment by PierreQuentel** [comment]
If you
1. install brython in a folder (`brython-cli install`)
2. remove **`demo.html`**
3. replace the code in **`index.html`** by
```python
import time

t0 = time.time()
import datetime
print(time.time() - t0)
```
4. run `brython-cli make_modules`
5. in index.html, replace **`brython-stdlib.js`** by **`brython_modules.js`**

you should see that the loading time is in the order of 0.2s.

In fact, because the **`datetime`** module is liable to import modules from the stdlib that themselves import other modules etc., you get a **`brython_modules.js`** which is not much smaller than **`brython_stdlib.js`** (3,1 MB against 4,5 MB), so you can skip steps 2, 4 and 5 with no noticeable difference for end users.
