### ISSUE TITLE
Problem with input()

### ISSUE THREAD

**Issue by edbotstudio** [brython-dev/brython#2174]
Here's a simple Python program that works fine:

```python
unknown = "No eye deer who you are {param}"
known = {
    "james" : "{param} is cool",
    "george" : "{param} is a hero",
    "wanda" : "Super {param}",
    "anna" : "Go {param}, go!",
    "john" : "{param} rules the market"
}
while True:
    name = input("Type a name: ")
    if name == "q":
        break

    response = None
    lname = name.lower()
    if lname in known:
        response = known[lname]
    else:
        response = unknown

    print(response.format(param = name.title()))
````

When I run in the Brython Editor nothing gets printed until the program exits (by typing 'q') which is not what the code is supposed to do. Is this expected behaviour or am I missing something?

**Comment by PierreQuentel** [comment]
It depends which browser you use, and maybe which OS (I'm on Windows 10):
- in Firefox the messages are printed
- in Chrome or Edge, they are not printed the first time you run the script, but if you exit by hitting 'q' and reload the page, the behaviour changes and you see the messages. Very strange !

Implementing Python blocking functions such as `input()` is difficult in the browser because the execution model is non-blocking; you cannot define a Javascript function that blocks until the user does something. The only blocking functions in Javascript are the built-in `prompt(), alert()` and `conform()`, and it seems that for Chrome and Edge, if these functions are executed inside a loop, nothing is printed in the console or changed in the document until the loop exits...

A workaround that works in all browsers is to wrap the loop inside a non-blocking function. It's not as straightforward as the CPython version, but Brython provides functions that make it not too difficult:
```python
from browser import aio
from browser.widgets.dialog import Input

unknown = "No eye deer who you are {param}"
known = {
    "james" : "{param} is cool",
    "george" : "{param} is a hero",
    "wanda" : "Super {param}",
    "anna" : "Go {param}, go!",
    "john" : "{param} rules the market"
}

async def loop():
    while True:
        name = await Input("Type a name: ")
        if name == "q":
            break
    
        response = None
        lname = name.lower()
        if lname in known:
            response = known[lname]
        else:
            response = unknown
    
        print(response.format(param = name.title()))

aio.run(loop())
```

**Comment by PierreQuentel** [comment]
I forgot to mention an experiment I made of an [interactive interpreter](https://brython.info/console_input.html) that supports the same `input()` as the CPython REPL, as well as `time.sleep()` (make sure to load it with https, not http). 

It uses a web worker, and as such it cannot use the Brython modules that interact with the DOM, this is why it has remained an experiment and not the features Brython REPL; but for teaching Python it might be a solution.
