### ISSUE TITLE
[PEP-3107] Python3 Function Annotations Support

### ISSUE THREAD

**Issue by juancarlospaco** [brython-dev/brython#228]
```python
Python 3.4.0 (default, Jun 19 2015, 14:20:21) [GCC 4.8.2] on linux
>>> def a(b:int) -> int:
...     return b
...
>>> a(42)
42
```

```python
Brython 3.2.0 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.81 Chrome/43.0.2357.81 Safari/537.36
>>> def a(b:int) -> int:
Traceback (most recent call last):
  module __main__ line 209
    cursorToEnd()
  module __main__ line 137
                        traceback.print_exc()
  module exec_46 line 1
    def a(b:int) -> int:
         ^
SyntaxError: invalid syntax
>>> 
```

It fills a `functionname.__annotations__` with a `dict` type object of with raw values from annotations.

Useful info:
- **PEP**: https://www.python.org/dev/peps/pep-3107/#use-cases
- **Static Typing** *(use case)*: https://gist.github.com/juancarlospaco/94f98cff7f9accd8d618#file-static_typing_python3-py
- **More use cases** and cool ideas: http://stackoverflow.com/q/3038033
- *Post your link or info on the comments below...*

¯＼(⊙_ʘ)/¯
----------------

**Comment by mscuthbert** [comment]
I suggest when doing this to go straight to the Python 3.5-alpha implementation of PEP0484 ( https://www.python.org/dev/peps/pep-0484/ ) and the typing module, because there may be some ways to use these hints to gain significant speedups in the compiling of python to js, if the signature of the values and the return are known.
