### ISSUE TITLE
html.INPUT maxLength attribute

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#2370]
Hi,

Just a little one. According to at least one HTML website [https://www.w3schools.com/tags/att_input_maxlength.asp] the HTML ``<input>`` element has attributes `maxlength` and `minlength` (all lowercase), but if we specify them with Brython, they don't appear as attributes in the DOM.

What does work with Brython is to specify attributes `maxLength` and `minLength` (note difference in case). New users might not think to try this. Could these two particular attributes be changed to all lowercase? Thanks a lot!

````
Brython 3.12.1 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Type "help", "copyright", "credits" or "license" for more information.
>>> from browser import html
>>> 'maxlength' in dir(html.INPUT())
False
>>> 'maxLength' in dir(html.INPUT())
True
````

**Comment by PierreQuentel** [comment]
Hi,

Here are 4 different tries at setting the attribute `maxlength`

```python
from browser import html, document

entry1 = html.INPUT(maxlength=10)
document <= entry1

entry2 = html.INPUT()
entry2.maxlength = 10
document <= entry2
assert entry2.maxlength == 10

entry3 = html.INPUT()
entry3.maxLength = 10
document <= entry3

entry4 = html.INPUT()
entry4.attrs['maxlength'] = 10
document <= entry4
```

`entry1`, `entry3` and `entry4` have the correct behaviour (maximum entry length is 10) but `entry2` has no maximum length.

This is another example of the difference between DOM elements _attributes_ and _properties_. `<input>` tags have an _attribute_ `maxlength`, which can be written in any case (`maxLength, MaxLength` etc...) since attributes are case-insensitive ; the matching _property_ is `maxLength` (case-sensitive)

With `entry2.maxlength = 10` you set the _property_ `maxlength`, but there is no _attribute_ associated with it, the _attribute_ `maxlength` is not set.

With `entry3.maxLength = 10` the _property_ is the one associated with the _attribute_

The last example is the one recommended in the [documentation](https://www.brython.info/static_doc/3.12/en/attributes.html): you can set the attribute by setting the dictionary-like object `entry.attrs`, with the attribute name written in any letter case.

**Comment by tjnaughton** [comment]
That explains it; the ``entry2`` approach was the one I was using. Thanks for the quick response and detailed explanation. I'll adopt the ``attrs`` approach in future!
