### ISSUE TITLE
Compatibility with ES6

### ISSUE THREAD

**Issue by olemis** [brython-dev/brython#242]
[ES6 Harmony](http://www.ecma-international.org/ecma-262/6.0/) standard's been finalized on June 2015 . As such some new native structures would have to be mapped onto Python concepts (and vice-versa) . The following approaches might be considered :
- Detect browser support and choose amongst one of two transpilers specific for ES5 vs ES6 
- Standardize Brython core to always emit ES6 code and require ES6 shims (e.g. [es-shims/es6-shim](https://github.com/es-shims/es6-shim) ) for legacy browsers .
- Keep code generation low-profile by only targeting legacy browsers and include improvements (e.g. in `JSObject`) for recent extensions (e.g. `Map` , `Promise`, ...)
- add your own ...

**Comment by PierreQuentel** [comment]
This is very exciting ! It's too early to choose between these options but as the ES6 features are introduced in modern browsers Brython should obviously take advantage of them.

(Olemis, can you fix the URL leading to the ES6 spec ?)

**Comment by olemis** [comment]
done , sorry

**Comment by olemis** [comment]
@PierreQuentel  IMO we better move forward with this early . It seems to me that all major browsers (ok , maybe except MSIE ) should be supporting this by 2016 . OTOH , for instance , promises feature will be very helpful in order to implement aspects of some open tickets .

**Comment by olemis** [comment]
And , at present , by using [es6-shim](https://github.com/es-shims/es6-shim/) only Safari 6.0 and mobile browsers seem not to be in supported platforms list .

**Comment by PierreQuentel** [comment]
In commit 818e01f4946754fead45ad31a103901a782e3af6 I implemented support for the ES6 iteration protocol. It's just a matter of testing if the JS object has the attribute `Symbol.iterator` set when Brython looks up the `__iter__` method, and if so use `for item of iterator` to generate the matching Python iterator.

**Comment by p-i-** [comment]
*"Standardize Brython core to always emit ES6 code and require ES6 shims (e.g. es-shims/es6-shim ) for legacy browsers"*

I like the sound of this -- to me it sounds the most responsible long-term strategy. The process is optimised for new browsers, whilst still supporting old browsers.

As ES6 -> ES7 -> ... over the years, this process is extensible.

**Comment by olemis** [comment]
@p-i-  I'm starting to think this is the case because , even if we keep codegen low-profile to target legacy browsers , there will always be new bindings that should be added .

**Comment by olemis** [comment]
The dark side of this would be the performance and feature coverage of shims . Besides that would imply that Brython would be dependent on third-party libs but . Nonetheless in the end i t seems to me this would not be quite a big concern because at code level we'd only have to worry about ES6 API compatibility ; we do not care how new features were loaded in each page .

**Comment by p-i-** [comment]
I remember from economics some kind of "cheap fast good" triangle. Where you can only get 2 out of 3.  So if it is cheap and fast it is not going to be good. And if it is cheap and good you will have to wait for it. And if it is good and fast it is going to cost you.

Maybe the sides to this triangle are: 
 1. keeping Brython source clean, lean and mean
 2. fast performance
 3. browser support / avoiding third-party dependencies

Or something like this...
The way I usually go in my own work is:  of paramount importance is to keep my codebase maintainable. Performance is often secondary to this. If I can support obsolete systems at the expense of performance / third-party, then that is fantastic!

I imagine the important thing is that Brython actually runs on everything ES5 and up, I don't think it would be realistic to hold yourselves to the goal of optimising for non-cutting-edge technology.

I think one has to lean into the technology wave to surf it, keep the weight on the front foot.

I know nothing of the Brython internals,  so I don't have much of value to say here. But I hope you don't find yourselves having to simultaneously maintain an ES5 and ES6 version. I was digging into the source code of PyCXX (C++ <--> Python) and the whole project had split into 2 wings for Python 2.x and 3.x. And I think this was the beginning of the end, it had fallen into passive maintenance and become really messy -- I think because of the doubled effort required in mirroring modifications across both wings.

π

**Comment by PierreQuentel** [comment]
I close this very old issue
