### ISSUE TITLE
Running async function without await 

### ISSUE THREAD

**Issue by thewh1teagle** [brython-dev/brython#2470]
Sometimes I forget to add await to async functions calls, but it doesn't throw errors, and I find it hard to find the cause.
Can you add check for that and throw error in that case?
Thanks

**Comment by PierreQuentel** [comment]
That would not be compliant with the Python language, where this code is valid and does not throw any error or even warning

```python
async def f():
    pass
```

**Comment by PierreQuentel** [comment]
Sorry for the misunderstanding.

In the new example, CPython doesn't raise any error or warning either.

**Comment by PierreQuentel** [comment]
Thanks, there was something missing in Brython. The commit above raises a `RuntimeWarning` like in CPython. 

It does so when exiting the execution frame, which leads to a minor difference with CPython. In code like
```python
async def example():
  print('example')

example()

print('ok')
```
Brython shows the `RuntimeWarning` _after_ printing "ok", whereas CPython shows it _before_. I suspect that this is caused by the garbage collector : after the line `example()` is executed, the coroutine object is not referenced anymore and the runtime engine can immediately detect that it has not been awaited. For Brython, garbage collection is performed by the Javascript engine and it's impossible to adapt it.

With a slightly different example, CPython and Brython both report the warning _after_ printing "ok"
```python
async def example():
  print('example')

c = example()

print('ok')
```
