### ISSUE TITLE
string.format() issues

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#260]
Hi all.  One of our TA's tested string.format() using the code samples from [here](https://docs.python.org/3/library/string.html), and she found quite a few issues.  I don't think I should enter them one-at-a-time, so here they all are, and I presume you can close this and refactor these into individual issues as appropriate (is that the right way to handle a situation like this?).

As for priority, on our side most of these would be considered low priority, though of course that's just our perspective.  :-)

<pre>
* Complex number example fails
Expected:
> c = 3-5j
> print('real part is {0.real}, imaginary part is {0.imag}.'.format(c))
>>> real part is 3.0, imaginary part is -5.0.
Brython:
> c = 3-5j
> print('real part is {0.real}, imaginary part is {0.imag}.'.format(c))
>>> AttributeError: complex object has no attribute 'real'

* Using name of specification (which would be useful for looping) crashes
Expected:
> text = "hello"
> print('{0:{fill}{align}16}'.format(text, fill=0, align=">"))
>>> 00000000000hello
Brython:
> text = "hello"
> print('{0:{fill}{align}16}'.format(text, fill=0, align=">"))
>>> ValueError: unsupported format character '}' (0x7d) at index 1

Other errors: (I put the expected output in the comments)

* Escaping squiggly brackets:
> # without an argument
> print("I have {{}} bananas.".format()) # I have {} bananas.
>>> KeyError: 0
> # with an argument
> print("I have {{}} bananas.".format(2)) # I have {} bananas.
>>> I have {2} bananas.
> # with an extra field and an argument
> print("I have {{}} and {} bananas.".format()) # I have {} and 2 bananas.
>>> KeyError: 1
My guess is the {{}} doesn't actually escape, so they are being treated as fields without any arguments, hence the KeyError (which I am assuming is the same as an IndexError since it's giving the first missing index? not sure about this though).

* When a !r conversion is specified, the escaped characters are still in printed string format
> print("I have {!r} bananas.".format("\\yellow")) # I have '\\yellow' bananas.
>>> I have '\yellow' bananas.
Note: this also occurs with !a conversion, which apparently uses the repr form of the string
> print("I have {!a} bananas.".format("\\yellow")) # I have '\\yellow' bananas.
>>> I have '\yellow' bananas.

* When a !a conversion is specified, the non-ascii characters are not converted to their hex/unicode representation
> print("I have {!a} bananas.".format("42₵")) # I have '42\u20b5' bananas.
>>> I have 42₵ bananas.

* Alignment issues:

* Left alignment (<) apparently only crashes for integers; it works for strings and floats
> print("I have {:*<10} bananas.".format(42.5)) # I have 42.5****** bananas. (works as expected)
>>> I have 42.5****** bananas.
> print("I have {:*<10} bananas.".format(42)) # I have 42******** bananas.
>>> ReferenceError: _aligned is not defined

* Center alignment (^) works, but not for floats
> print("I have {:*^10} bananas.".format(42)) # I have ****42**** bananas. (works as expected)
>>> I have ****42**** bananas.
> print("I have {:*^10} bananas.".format(42.5)) # I have ***42.5*** bananas.
>>> TypeError: (missing - left).repeat is not a function

* = alignment crashes for integers, and produces an incorrect output for floats
> print("I have {:*=10} bananas.".format(-42)) # I have -*******42 bananas.
>>> ReferenceError: _value is not defined
> print("I have {:*=10} bananas.".format(-42.5)) # I have -*****42.5 bananas.
>>> I have *****-42.5 bananas.

* Right alignment (>) works, but not by default for integers (seems to work completely for floats though)
> print("I have {:>10} bananas.".format(42)) # I have         42 bananas. (works as expected)
>>> I have         42 bananas.
> print("I have {:10} bananas.".format(42)) # I have         42 bananas.
>>> ReferenceError: _aligned is not defined
> print("I have {:10} bananas.".format(42.5)) # I have       42.5 bananas. (works as expected)
>>> I have       42.5 bananas.

* Special 0 spec (equivalent to 0 fill and = alignment) usually crashes, incorrect for floats (probably same bug as for = alignment)

* , spec doesn't work for floats
> print("I have {:,} bananas.".format(42000)) # I have 42,000 bananas. (works as expected)
>>> I have 42,000 bananas.
> print("I have {:,} bananas.".format(42000.0)) # I have 42,000.0 bananas.
>>> I have 42000.0 bananas.

* c output spec doesn't work
> print("I have {:c} bananas.".format(42)) # I have * bananas.
>>> I have 42 bananas.
</pre>

Hope this helps, and thanks as always.

David

**Comment by olemis** [comment]
@dkosbie your report is ok , since all cases are related to a single aspect i.e. `string.format()` .

If you're willing to contribute a more involved approach , at least until we finally be able run CPython test suite , would be to add in [www/tests/test_* modules](https://github.com/brython-dev/brython/blob/master/www/tests/) the code illustrating the failures you find along the way .

Should you consider that your issues are totally unrelated to the original intent of existing test modules , then feel free to create a new one ; but please always keep test_ prefix in file name . After that also add the new module name in the list returned by [discover_brython_test_modules](https://github.com/brython-dev/brython/blob/master/www/tests/brython_test_utils/__init__.py) . By doing so your new module will be considered in the [interactive tests page](https://github.com/brython-dev/brython/blob/master/www/tests/index.html) as well as the [QUnit test suite](https://github.com/brython-dev/brython/blob/master/www/tests/run_qunit.html) .

Once you get this done then send us a pull request . We'll notice the failures and be able to work towards fixing'em .

Thanks for your reviews . Keep up the good work !
:)
