### ISSUE TITLE
How do you get variable values, functions, etc?

### ISSUE THREAD

**Issue by aaronmatenga** [brython-dev/brython#265]
In our online course (teaching python) we have previously been using ```__BRYTHON__.vars.__main__``` to get variable values and functions. For example if a user wrote the python code:
```
name = input("What is your name?")
print(name)
```
we would use the following code to access their variable to check it has the correct value:
```
__BRYTHON__.vars.__main__['name']
```

With the latest brython update this no longer seems to work. Is there any other way we can get access to these?

Thanks

**Comment by PierreQuentel** [comment]
Hello,

This was discussed recently in [the Google Group](https://groups.google.com/forum/?fromgroups=#!topic/brython/GK1G86FYig4). The way to access the global namespace in the borwser console is : 

```python
globals = __BRYTHON__.globals()
```

**Comment by aaronmatenga** [comment]
Thanks for your help! Sorry I forgot to close the issue.

Aaron

**Comment by BrenBarn** [comment]
I just tried to use `__BRYTHON__.globals()` in the browser console and got this error:

    $B.frames_stack[($B.frames_stack.length - 1)] is undefined

Has something changed?

**Comment by jonathanverner** [comment]
Using `git bisect` it seems that this broke in commit d393a0e1fcd4b9c6439ca736c64ff6c15b60fef8.

**Comment by PierreQuentel** [comment]
Reading this thread more than one year after, I see this feature as a flaw in previous implementations.

To get the name of currently used variables inside a Python script _while it is running_, you can use the built-in functions `locals()` and `globals()` ; they use the frame stack maintained by the runtime engine.

But _once the script is finished_, the frame stack is empty, the reference to variables used in the script is lost. It's like when you run a CPython script in a console.

So yes, something changed, but it's much more the expected behaviour than before.
