### ISSUE TITLE
base64.b64encode( bytearray(b'<Z\x00N') gives TypeError: Cannot read property '__class__' of undefined

### ISSUE THREAD

**Issue by p-i-** [brython-dev/brython#274]
This fails on the console:

    import base64
    b = bytearray(b'<Z\x00N')
    b64 = base64.b64encode( b )

    Internal Javascript error: TypeError: Cannot read property '__class__' of undefined

Works on https://repl.it/BF8j/1

**Comment by rdb** [comment]
The problem is in `Lib/binascii.py`, function `b2a_base64`.  It calls `ord(final[0])`, but final is a bytes object, and indexing a bytes object produces an integer.  This causes the `ord` function to return `undefined`.

Since CPython 3's b2a_base64 only accept byte objects and not strings, it seems that the solution is to just remove the ord() calls from the Brython version.

**Comment by PierreQuentel** [comment]
Thank you, I fixed the bug as you suggested. `binascii` is one of the modules borrowed from PyPy because it's implemented in C in CPython.

**Comment by p-i-** [comment]
It appears there is still a related bug:

Using 
    buf = bytearray(b'EZ\x86\xdd\xabN\x86\xdd\xabNE[\x86\xdd\xabN\x86\xdd\xabN')

I get:

    brython_dist.js:4553 Traceback (most recent call last):
      module __main__ line 254
        print( "Ready!" )
      module __main__ line 219
        	buf64 = base64.b64encode( buf )
      module base64 line 28
        encoded =binascii .b2a_base64 (s )[:-1 ]
      module binascii line 194
        a =ord (final [0 ])
    TypeError: ord() expected a character, but int was found

**Comment by PierreQuentel** [comment]
Correct, it was the same problem, removing `ord()` avoids the exception. The result was not correct though, because of another bug in operator precedence between `| ^ &`. The result is correct for this example now.
