### ISSUE TITLE
raise timeout exception rather than hang on infinite loop

### ISSUE THREAD

**Issue by dkosbie** [brython-dev/brython#289]
Hi all.  This is a feature request rather than a bug report.  It is not uncommon for students to write code with infinite (or effectively infinite) loops.  If this code is run in Standard Python, they can simply shift-ctrl-c to break out of the loop.  But if this code is run in Brython, they have no means of breaking out of the loop, and they lose their browser session, which must be reset.  This would be a major problem for us, except we have added a fairly simple workaround.

Before running their code, we rewrite it so that inside each "while" and "for" loop, we first check how long their code has been running, and raise an exception if it has been too long (which for now we set at 4 seconds, but of course that could be changed dynamically at the user's preference).

This has worked very well for us.  An infinite loop times out gracefully after 4 seconds.

We also reset the start time after a call to input(), so long-running interactive console programs do not timeout inadvertently.  When we get to event-based graphics programs, we will do the same for the various event handlers, so a program will not timeout while waiting for an onEvent call.

Anyhow, we are fine, and it mostly works as is.  I say mostly because our code rewriting was not done in the most sophisticated manner, and so we will fail on some edge cases.  But mostly it works and works reasonably well.

Even so, it would be nice if we did not have to rewrite code, and if this facility was built into Brython, or so I imagine.  One could imagine a call to enable/disable the feature, and another one to set the timeout delay (these could be merged into a single call with a delay of -1 effectively disabling the feature).  If it was disabled by default, this would be a backwards-compatible change.

Thanks as always for your great work!

David

**Comment by PierreQuentel** [comment]
David,

I understand the request, I often find myself in this situation of unresponsive scripts because there is an infinite loop somewhere, either because of a bug in the Python code, or in Brython itself.

But in this case, since the browser is running a Javascript program, it pops up the "unresponsive script" window, and the user can choose either to continue program execution, or stop it, in which case he gets control again and the session is not lost.

This is built-in in all modern browsers, so I don't think there should be something specific to do in Brython. Am I missing something ?

**Comment by dkosbie** [comment]
Hi Pierre.  Thanks for the quick reply.

The unresponsive-script solution unfortunately doesn't work well for us.

For one thing, it does not always happen.  In fact, I just ran an infinite loop on brython.info using an up-to-date Safari and it hung forever.

Secondly, even when it does happen, there are two problems.  I then ran the same infinite loop on brython.info using an up-to-date Chrome, and I got the unresponsive-script window, but:  (1) it popped up way too late, maybe 30 seconds, during which a student is stuck doing nothing but waiting; and (2) it did reset the window, with the "Aw Snap" screen.  When I reload, it's a new page load, which we do not find desirable simply due to a simple bug in student's code.

Thanks again.

David

**Comment by PierreQuentel** [comment]
David,

In the commit referenced above I propose a solution for this issue. 

I define a global variable `__BRYTHON__.loop_timeout`, that can be set with function `set_loop_timeout()` in module __browser.timer__. The value is in seconds.

If this variable is set, the Brython engine transforms all the `for` and `while` loops so that if the loop takes more than the specified value, a `RuntimeError` is raised.

I have implemented an exemple in the page tests/index.html. A new checkbox "loop timeout" has been added ; if it is checked, a value is requested, and the above technique is used.

It doesn't seem to have a huge influence on performance.

Does this help ?
