### ISSUE TITLE
[bug] Brython does not raise an UnboundLocalError

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#327]
Using Python 3.4.1, I have the following:
```
>>> a = 3
>>> def plus():
...     a += 1
...     print(a)
...
>>> plus()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in plus
UnboundLocalError: local variable 'a' referenced before assignment
```

Doing the same with Brython 3.2.2, using http://brython.info/tests/editor.html?lang=fr, no error is raised and 4 is printed.

**Comment by aroberge** [comment]
Note: when I do this on my site, I see a message logged in the console, message coming from Brython's line of code:

    if($arg===undefined){console.log('arg '+i+' undef in '+$fname)}

I suspect that this is where an exception should have been raised.

**Comment by PierreQuentel** [comment]
Merci André !

I didn't notice there was this regression since previous versions. I rewrote and simplified the algorithm to detect such errors, but it's hard to imagine tests that cover all use cases. These ones throw the expected `UnboundLocalError` : 

```python
def f():
    a += 1
f()
```

```python
def f():
    a = a+1
f()
```

and this one passes :

```python
def f():
    for i in 1,2:
        if i==2:
            x = a
        else:
            a = 1
    return x

assert f()==1
```

If you detect cases when this is not correctly handled don't hesitate to reopen this bug.

**Comment by aroberge** [comment]
Merci Pierre!   As you know, I do not hesitate to file issues! :-)

**Comment by aroberge** [comment]
```python
a = 3

def plus():
    print(a)
    a = 7

plus()
```

yields
```
Internal Javascript error: TypeError: Cannot read property '$nat' of undefined
  module 'editor' line 97
        exec(src, ns)
```
