### ISSUE TITLE
ABCMeta and isinstance issues

### ISSUE THREAD

**Issue by fsvend** [brython-dev/brython#347]
I just tested Brython 3.2.1 and this fails to execute correctly:
```
from abc import ABCMeta, abstractmethod

class interface(metaclass=ABCMeta):
    @abstractmethod
    def test(self):
        return

class implementation(interface):
    def test(self):
        return

i = implementation()
print(isinstance(i, interface))
```

The implementation doesn't honour the abstract base class, ie. I can rename 'test' in the implementation class and instantiate it. This shouldn't be possible. Also, the print statement returns False, which is wrong.

**Comment by PierreQuentel** [comment]
Thanks for the report. The commit referenced above fixes the bug in the sense that `print isinstance(i, interface)` is true. But I'm not sure what you mean by _ I can rename 'test' in the implementation class and instantiate it. This shouldn't be possible._ : the code doesn't raise an exception in CPython.

**Comment by fsvend** [comment]
Hi, and thanks for the reply. Reg. what was unclear: What I tried to say was that if I change the implementation class so that it doesn't implement the interface contract, it can still be instantiated. In Brython, I can instantiate an abstract class (!), like so:
```
from abc import ABCMeta, abstractmethod
class interface(metaclass=ABCMeta):
    @abstractmethod
    def test(self):
        return

i = interface() # this ought to raise an exception, but it doesn't
print(id(id))
```
The code above throws with "TypeError: Can't instantiate abstract class interface with abstract methods test" in CPython 3.2.1, and it should have raised an exception in Brython too. It seems Brython doesn't support metaclasses, and should probably fail when trying to import abc, etc.

It's not clear from the brython.info page what version of Python Brython targets. I've assumed that, say Brython 3.2.1, ought to be compatible with Python 3.2.1. Is that assumption correct?

**Comment by PierreQuentel** [comment]
Thanks for explaining. This bug is fixed in the commit referenced above.

I don't pretend that all the features of metaclasses are supported, but saying that _Brython doesn't support metaclasses_ is slightly exagerated. It actually succeeds in importing abc, as the code you use to report the bug shows. Not all Python developers are PEP 3119 experts - I certainly am not - so it you find other issues it's very helpful if you can report them as you already did.

The target Python version is currently the one you get with the standard

```
>>> import sys
>>> sys.version_info()
```

Brython version number is not related to the Python version supported. You can take a look at the releases list, it changes regularly with a set of new features, improvements and bug fixes.

**Comment by fsvend** [comment]
Hi Pierre Quentel, and sorry for the exagerration. After commit 0eb59f8e9fedb, it works as expected. Thanks for the fast response and fixes. Keep up the good work!

One more thing: It is very slow, at least on my machines, to browse the Brython source repository, since you include the generated brython{_dist}.js files in each commit. Have you considered not including the generated files in each commit?

**Comment by PierreQuentel** [comment]
The addition of brython_dist.js is recent, it was done to offer the possibility to run Brython code on any web page, without any installation on a server or local machine, just by loading this script from rawgit as explained in the home page.

What tool do you use to browse the source code ?
