### ISSUE TITLE
c.listattr.append doesn't work if c is subclassed from svg object

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#366]
Hello again

This is really a continuation of the previous issue (365).  The same example as before:

>>> import browser.svg as svg
>>> class C(svg.circle):
...     def __init__(self, r):
...         self.rlist=[]
...         self.rlist.append(r)
... 
>>> a = C(5)
>>> a.rlist
[]

rlist is now a list rather than a string.  But append does not work.  In fact I've just tried extend as a workaround, and that doesn't work either:
>>> a.rlist.append(99)
>>> a.rlist
[]
>>> a.rlist.extend([99])
>>> a.rlist
[]

Thanks again

Andy

**Comment by andy31lewis** [comment]
A bit more testing - basically the list is "silently immutable"  ie changing it doesn't throw an exception, but has no effect. But assigning the whole list, indexing and slicing work:

>>> a.rlist = [1,2,3]
>>> a.rlist
[1, 2, 3]
>>> a.rlist[2] += 99
>>> a.rlist
[1, 2, 3]
>>> a.rlist[2] = 99
>>> a.rlist
[1, 2, 3] 
>>> a.rlist[2]
3
>>> a.rlist[1:3]
[2, 3]

Hope that helps,

Andy

**Comment by PierreQuentel** [comment]
Thanks again Andy. The issue was not related to the previous one : `self.rlist` would return a _copy_ of the list, not the list itself...

BTW to include Python code inside a bug report, you can use the Markdown syntax : enter a line with <code>\`\`\`python</code>, then the code, then another line with just <code>\`\`\`</code>
