### ISSUE TITLE
Dist files in repository

### ISSUE THREAD

**Issue by caryoscelus** [brython-dev/brython#397]
Distribution files (under www/src/: brython.js, etc.) are currently included in git and clutter commit diffs (as well as `git diff` output). The only positive side i can see is having ready to use brython right after `git clone`, but those who don't intend to develop brython should probably use releases instead and those who do would need to compile stuff anyway.

**Comment by PierreQuentel** [comment]
These files must remain in the repository because one of the ways to use Brython is to load these scripts from rawgit : either the latest official release or the current development version.

**Comment by caryoscelus** [comment]
I see. But why not create special branch for them or just host separately?

**Comment by caryoscelus** [comment]
It would break existing links if removed completely, but it's possible to put warnings in `brython.js` and don't update it in future.

**Comment by PierreQuentel** [comment]
With the current solution we don't have to do anything else than push changes to the repository, and changing CDN would break existing applications that currently use rawgit. This is too much to pay just to avoid a few extra output in git diffs.

**Comment by olemis** [comment]
Including `brython.js` in source code makes it almost impossible to recursively grep across the source code . No matter the pattern it's almost 100% certain that it will show up in `brython.js` , which ends up including a looong line of almost all available source code . That's why I am keen to favour @caryoscelus arguments. But yours, @PierreQuentel , are important as well as . Is it possible to make'em both work ? I guess so .

Development could happen in a new branch (named e.g. `develop` like in [this successful workflow](http://nvie.com/posts/a-successful-git-branching-model/) ) not including `brython.js` . From time to time , when code is stable and an intermediate milestone is achieved , the changes will be incorporated (i.e. merged) back into `master` , which is followed by the generation of `brython.js` file .

@caryoscelus @PierreQuentel do you think we can make this work ? Does it make sense to you ?

**Comment by PierreQuentel** [comment]
I also have unwanted results in brython.js and brython_dist.js when I search something in Brython code (and I do it all the time, as you can imagine), but I just ignore them.

The workflow in Brython is different : development happens in master branch, which is not really unstable : I always check that the integrated test suite passes without error before pushing. This is what makes the rawgit development version usable. The releases are just a snapshot of the master branch when an important feature has been added, or a critical bug fixed, or too much time has passed since the latest release.

To avoid the problems you mention there is a very simple solution : manually remove the generated files after you have cloned the repository.

**Comment by caryoscelus** [comment]
@olemis 
That's a bit different problem. It could be fixed by, for example, moving sources away from `www/src` while keeping dist files there.

@PierreQuentel 
Just removing generated files will make unusable local brython, so it's not really a solution.

What seems to me to be the best solution (which would address these issues as well as maintaining compatibility) is the following:

1. create `dist/` directory, ignored by git and point build scripts to output there
2. create `deployment` branch which would contain only `dist/`
3. add git hooks to commit `dist/` on commit or before push to master
4. 
 * either replace `brython.js` with simple script making warning in js console and loading actual `brython.js` from `deployment` branch
 * or just put warning there and stop updating it (this would change current behaviour of having most recent `brython.js` at current location, but those who maintain their applications should see the warning and those who don't shouldn't have problems with old version)

That said, there's probably also a dirty local solution: apply step 1 locally and remove `www/src/brython.js` (and make any necessary changes so that local brython still works) and then `git update-index --assume-unchanged` on all changed files. Since that setup would be broken by next update in master, put those changes in script to be called from git hooks. This might work, but seems to be too complex and might also have problems when master updates build scripts or `index.html`.

**Comment by olemis** [comment]
@PierreQuentel I am not sure that deleting brython.js is a solution . On the one hand dev files like `www/tests/index.html` (but not limited to) include individual source code files (e.g. `www/src/py2js.js` et al.) . On the other hand web pages in the gallery include `www/src/brython.js` file . So removing them means , at least , that samples in the gallery will not work . 

@caryoscelus I am not quite sympathetic to your `deployment` branch proposal .
