### ISSUE TITLE
str.islower() and str.isupper() when str does not contain alphabetic characters

### ISSUE THREAD

**Issue by hcrites54** [brython-dev/brython#423]
Greetings!
I have having trouble with islower() and isupper().
```
print("0123".islower())
print("!!!".isupper())
```
Expected Output: False False
Actual Output: True True

str.islower() and str.isupper() are to return True only if they actually contain at least one alphabetic character and it is either lower or upper case.  In my examples, neither contains an alphabetic character at all, therefore it should return False.  In Brython, I am getting True.
Thanks!
Heather

**Comment by KarimJedda** [comment]
Hi,

i think the problem lies here:
https://github.com/brython-dev/brython/blob/498d27f3f5d14b7d46f3d6f54f84828461f5e18b/www/src/py_string.js#L1184

in any node cli, if you do the same thing, you get:
> test = "012"
'012'
> test.toUpperCase()
'012'
> test == test.toUpperCase()
true
> test = "!!!"
'!!!'
> test == test.toUpperCase()
true


maybe adding ' && $.self.search(/[a-z]/)==1' to both would help? I don't know, i'm not a javascript freak.

Well, I wanted to start learning Ecmascript 6 tonight, but I found Brython so I'm doing Brython now.

**Comment by PierreQuentel** [comment]
Thanks for the report Heather !

To be compliant with Python I have built a regular expression to detect lowercase, uppercase and titlecase letters (`$B.cased_letters_regexp` in __brython_builtins.js__) ; this regexp is used in `str.lower()` and `str.upper()`.
