### ISSUE TITLE
A python 2 port?

### ISSUE THREAD

**Issue by chibill** [brython-dev/brython#435]
Is there any possibility of a version of brython that is build to run python 2 instead of 3?

**Comment by jsbueno** [comment]
On 28 May 2016 at 12:26, William Gaylord <notifications@github.com> wrote:

> Is there any possibility of a version of brython that is build to run
> python 2 instead of 3?
>

What for?

Even that being feasible, there is no reason for that -
Brython is Python compatible, but it is not like major Python projects can
be run - simply
due to the different environment, and also due to the impossibility of
running extensions in
native code.

Now - compatibility with large projects from the past are the sole and only
reason one
might want to start a project in Python 2 these days.
The language has gone ahead in every respect.

If you have some code in Python 2 that you would like to reuse on the
browser with Brython,
just run Python's own "2to3"  on your code.

 js
-><-

**Comment by chibill** [comment]
Mostly because I still use Python 2 because most libs (even fully Python) are not ported to 3 or won't work on 3. Was just asking.

**Comment by kikocorreoso** [comment]
what libs do you need that are not ported to python 3?

BTW, you can separate the logic of the application and use python3 (Brython) on the client side and python 2 on the server side.

**Comment by chibill** [comment]
That's the problem the lib is on both sides....

**Comment by chibill** [comment]
It's parallel Python.

**Comment by kikocorreoso** [comment]
The library you want to use is this one: http://www.parallelpython.com/ ?

Anyway, A solution for CPython will never work out-of-the-box (neither python2 o 3). If you want to parallelize code on the browser you need to change the logic of the code as in the browser you would need to use something like webworkers to allow your code to use multiples cores. Check [1] and [2] for potential solutions.

[1] https://blog.mozilla.org/javascript/2015/02/26/the-path-to-parallel-javascript/
[2] https://adambom.github.io/parallel.js/

**Comment by chibill** [comment]
That's the thing it should work as it's pure python I just have to move the sub processes calls to make new webworkers instead. I will see if it loads in py 3 as it was last updated like 4 years ago.

**Comment by kikocorreoso** [comment]
Let us know the progress here or in the mail list!!! 
:smiley:
