### ISSUE TITLE
Passing arguments through brython() function

### ISSUE THREAD

**Issue by NicoPy** [brython-dev/brython#442]
I'd like to be able to pass arguments to executed script.
For example : 
`brython({debug:1, ipy_id:['Test1'], args:['arg1, 'arg2, 'arg3]})`
In the script, sys.argv would contain args argument of brython() function (with script name in sys.argv[0]).

**Comment by kikocorreoso** [comment]
To better understand it, `'arg1'`, `'arg2'` and `'arg3'` would be arguments for the script with id `Test1`?

**Comment by NicoPy** [comment]
That's right.
Maybe its better with a list of list. Each list being arguments of an element of ipy_id.

**Comment by NicoPy** [comment]
Since there is no complete name space separation between scripts run with brython() function, there is no way to set separate arguments for each script.

**Comment by PierreQuentel** [comment]
Yes, you can specify the script id to identify a specific script.

I implemented a feature (not commited yet) to capture arguments passed to brython with

```
<body onLoad="brython({debug:2, args:{script1:[1,2]}})">
```

and then get the arguments in this script by : 

```
<script type="text/javascript" id="script1">
import sys
print(sys.argv)
</script>
```

This is done by using the execution frame stack, without having to manage a specific version of modules for each script.

Would that be ok for your use case ?

**Comment by kikocorreoso** [comment]
@NicoPy when you say this:
> Since there is no complete name space separation between scripts run with brython() function, there is no way to set separate arguments for each script.

What do you mean with this?

If I do this, using `brython()`, i.e., no `ipy_id`:

http://jsfiddle.net/L94jcew0/1/


```
<script id="test1" type="text/python">
msg = "message from test1"
</script>
<script id="test2" type="text/python">
from browser import alert
#from test1 import msg

alert(msg)
</script>
```

I get an error message. I have to explicitly import `msg` from *test1* to get the correct behavior:

http://jsfiddle.net/L94jcew0/2/

```
<script id="test1" type="text/python">
msg = "message from test1"
</script>
<script id="test2" type="text/python">
from browser import alert
from test1 import msg

alert(msg)
</script>
```

If I use `ipy_id` option it is true what you state and the first option posted above will work because the original use for this option was to allow people run brython snippets in the notebook in an easy and simple way. so all the scripts stated in the `ipy_id` option is a final concatenated bigger standalone script.

**Comment by NicoPy** [comment]
@kikocorreoso 

> If I use ipy_id option it is true what you state and the first option posted above will work because the original use for this option was to allow people run brython snippets in the notebook in an easy and simple way. so all the scripts stated in the ipy_id option is a final concatenated bigger standalone script.

This is what I use. I thought that calling brython() function with different ipy_id parameter would create a new brython instance totaly uncorrelated with the others. This is not the case.

@PierreQuentel Yes, that would be perfect.

**Comment by PierreQuentel** [comment]
Ok, I pushed the change in commit c096620

**Comment by NicoPy** [comment]
Thanks.
I'll test it asap.

**Comment by NicoPy** [comment]
It does not seem to work.
Adding args dict has no effect.

**Comment by PierreQuentel** [comment]
I'm not too sure about what you call "passing args dict" but in CPython when you pass arguments on the command line `sys.argv` is a list of strings. You can pass the equivalent of a dictionary by `python script.py -key value`, not by `python script.py {key: value}`.

Another thing to remember is that the arguments passed to brython() are Javascript objects, which are not the same as Python dictionaries - keys are always converted to strings, for instance.

I think the best would be to control that all the items in args[script_id] are simple Javascript types (strings or numbers) and raise an exception otherwise.

**Comment by NicoPy** [comment]
With a simple html file, it works when removing ipy_id parameter.
However, I have not been able to make it work with dynamically calling brython() function.
