### ISSUE TITLE
Error on successful import of Module in Directory

### ISSUE THREAD

**Issue by ashes999** [brython-dev/brython#458]
Hi,

TLDR: when importing a module in a directory, I get a Javascript console error, even though the import succeeds.

My directory structure looks like this:

```
index.html
main.py
m1.py
m2/m3.py
```

`index.html` contains `<script type="text/python">import main</script>`

`main.py` contains:

```python
import m1
from m2 import m3
```

I can consume `m1` calls, and `m3` calls fine. But, I see this error in the Javascript console:

```
GET http://localhost:8000/m2.py?v=1468988022921 404 (File not found)
```

This made me crazy, until I realized the file actually imported correctly!

Is there any way to get rid of the console error?

**Comment by PierreQuentel** [comment]
This is explained in the section "Frequently Asked Questions" of the documentation.

**Comment by ashes999** [comment]
Are you referring to this question in the FAQ?:

> Q : I see a lot of 404 errors in the browser console when I run Brython scripts, why is that ?

It explains why this problem occurs, but it doesn't explain how to get rid of the error. Does that mean it's not possible to not have an error?

Let's say I have a module file in a directory, and it generates a Javascript error. If I have 6-8 of these, I'll see 6-8 Javascript errors in the console. When I ship my app to production, users will always see it. That's a problem.

Is there any way to "tell" Brython specifically where the file is located, instead of having it probe likely locations until it finds the file?

Alternatively, is there any way to not show an error until it finally fails to find the file (when it raises the `ImportError`)?

**Comment by ashes999** [comment]
There are a couple of things I have a hard time understanding:

1) The import succeeded, even though there was an error. Shouldn't there be a console message indicating as such? There's no easy way to see that the import succeeded.
2) If I have `a/b.py` and `a/c.py`, why would importing `a.b` or `a.c` look *first* for `a.py`?

**Comment by PierreQuentel** [comment]
I agree that it would be nice to get rid of the 404 messages (which, BTW, are not "Javascript errors"), but there is no API to control this from Javascript, thus from Brython ; each browser has options to filter what is printed in the console, unfortunately this can't be set by a program. If someone has an idea, I would be glad to know.

Anyway, all those messages appear in the browser console ; it's only the users that open it (mostly developers) that will see the 404 errors. Otherwise, either the import succeeds, or there is an `ImportError`. And there is indeed a console message saying that the import succeeds : it is the one with the response code 200.

In standard Python, there is no way (unless with terrible hacks) to tell a script that for `import X`, the module to load is the file *X.py* or *X/\_\_init\_\_.py* or *Lib/site-packages/X.py* ; CPython tries the locations in the file system a certain order. Brython does the same, but without access to the file system, it has to make Ajax calls until the module is found.

You are right with `import a.b` : it's no use trying to import a module a.py. I will fix this.

**Comment by ashes999** [comment]
Thanks, I appreciate the detailed responses. (Sorry, I should have mentioned that I'm new to Python.)

I guess this is stuck the way it is (hence why it's in the FAQ). Thanks for clarifying.
