### ISSUE TITLE
super() behaviour does not match Python's when an object's '__class__' attribute is changed.

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#481]
The following code 

```
def extend_instance(obj, cls):
    """
        Apply mixins to a class instance after creation
        (thanks http://stackoverflow.com/questions/8544983/dynamically-mixin-a-base-class-to-an-instance-in-python)
    """

    base_cls = obj.__class__
    base_cls_name = obj.__class__.__name__
    obj.__class__ = type("Extended"+base_cls_name, (cls,base_cls),{})

class Mixin(object):
    def __setattr__(self, name, value):
        if not name.startswith('_'):
            print("Mixin setting", name, "to", value)
            super().__setattr__(name,value)
        else:
            super().__setattr__(name,value)
            
class Test:
    def __init__(self):
        self._dct={}
    
    def __setattr__(self,name,value):
        if not name.startswith('_'):
            self._dct[name]=value
            print("Test setting", name, "to", value)
        else:
            super().__setattr__(name,value)
    def __getattr__(self):
        if not name.startswith('_'):
            return self._dct[name]
        else:
            return getattr(self,name)
    
t=Test()
extend_instance(t,Mixin)
t.c=20
```
outputs (tested on the Brython.info editor, reported version 3.2.7)
```
Mixin setting c to 20
```
(i.e. Test's setattr is never called) while Python (3.3,3.4) outputs
```
Mixin setting c to 20
Test setting c to 20
```
(i.e. Test's setattr is called)

**Comment by PierreQuentel** [comment]
Wow. This one was hard !

Your example now works, but I'm not sure if the method is correct. 

To resolve `super().__setattr__`, I use the implicit arguments `type, object_or_type` of `super()` (they are added by the Brython parser by static code analysis). In your example, in `Mixin.__setattr__`, these arguments are `Mixin, self`.

I first search if `__setattr__` is defined in one of the subclasses of `type` ; if the only one found is `object.__setattr__` (which is the case for `Mixin`), I search if a `__setattr__` is defined in the `object_or_type` class hierarchy above `type` (in your example, the parent classes of `self` above `Mixin`, ie `Test` and `object`). Since `Test` defines a method `__setattr__`, it is used as the result of `super.__setattr__`.

This is more guesswork than applying a well documented description of `super()` : the one given in the Python documentation is not complete enough. If your have more information please let me know.
