### ISSUE TITLE
Cannot read property 'length' of undefined on nested DOMNodes

### ISSUE THREAD

**Issue by hrehfeld** [brython-dev/brython#546]
Possibly related to #434 or #422 ?

    from browser import document
    c = document.createElement('foo')
    el = document.createElement('div')
    el.appendChild(c) # doesn't matter if they are children
    el.c = c
    el.c.clear()
    print('after clear')

results in:

    Javascript error TypeError: Cannot read property 'length' of undefined
        at Object.DOMNodeDict.clear (brython.js:10299)
        at brython.js:10149
        at eval (eval at run_script (brython.js:4103), <anonymous>:25:77)
        at run_script (brython.js:4103)
        at XMLHttpRequest.callback (brython.js:4076)

    brython.js:4904 Traceback (most recent call last):
    RuntimeError: TypeError: Cannot read property 'length' of undefined

    brython.js:4077 Uncaught Error
        at Object._b_.RuntimeError (eval at $make_exc (brython.js:6224), <anonymous>:97:409)
        at run_script (brython.js:4106)
        at XMLHttpRequest.callback (brython.js:4076)

Other weirdness also happens around this member.
Interestingly, 

    c.clear()

seems to work.

Using 

    // version [3, 3, 0, 'alpha', 0]
    // implementation [3, 3, 0, 'alpha', 0]

on chrome 55.0.2883.87

**Comment by jonathanverner** [comment]
Attributes on a `DOMNode` behave in a special way and, in my opinion, it is best to avoid them. 

Your problem comes from the fact that accessing a `DOMNode` attribute  returns it wrapped as another `DOMNode` (the logic is in [www/src/py_dom.js](../blob/master/www/src/py_dom.js#L443) starting at line 443). In your particular case `el.c` will, in fact, be `DOMNode(c)`. However, the `DOMNode` constructor expects a native `DOMElement` not a `DOMNode` so the `el.c` will behave in a weird way. 

The easiest way to fix this would be just to prevent setting attributes on a `DOMNode`. What do you think, @PierreQuentel?

**Comment by hrehfeld** [comment]
OK, this is really unexpected. I was surprised by all the wrapping going on as well.

Is there any way to avoid the DOMNode at all, and just use the JS nodes then? I don't really see any advantage besides the "pythonic" interface for my code.

I think it is/would be a disadvantage for brython if node attributes could not be used at all.

**Comment by PierreQuentel** [comment]
The commit referenced above fixes the bug that caused your code to break : as Jonathan noticed, `el.c` was not the DOMNode instance but a wrapper around this node. 

`DOMNode` instances are the way DOM nodes are represented in Brython ; there is no such thing as a "JS nodes", the DOM is language-independant. Since setting attributes on a DOM node is allowed, there is no reason why Brython would not support this.
