### ISSUE TITLE
Remove child element issue

### ISSUE THREAD

**Issue by hir3npatel** [brython-dev/brython#557]
Hi,

I try the code below with the latest release of brython, I expect it to delete the first table row, and nothing else (see the break statement). It seems to delete the entire table body including all rows under the table body. This is code that worked on a previous brython release, on previous chrome versions. I have updated chrome to 56, and brython to 3.3.0. I'm not sure if this issue is with brython or a new chrome, or my code is incorrect (although the code behaved as I expected in previous releases)

```

<!DOCTYPE html>
<html lang="en">
<head>    
<script src="brython.js"></script>
<script src="brython_stdlib.js"></script>
</head>

<body onload="brython()">
<script type="text/python">
from browser import document
table = document['mytable']
tbody = table.get(selector="TBODY")[0]

for row in tbody.get(selector="TR"):
    tbody.remove(row)
    break
</script>


<table id="mytable">
<thead></thead>
<tbody>
    <tr><td>one</td></tr>
    <tr><td>two</td></tr>
    <tr><td>three</td></tr>
</tbody>
</table>
</body>
```

**Comment by PierreQuentel** [comment]
Thanks, there is a problem with this method : it conflicts with the [method of the same name](https://developer.mozilla.org/fr/docs/Web/API/ChildNode/remove) on DOM nodes ; I think it didn't exist when I wrote the Brython method `remove()`.

Unfortunately the syntax is not the same : 
- the DOM method `element.remove()` removes the element
- in Brython, `element.remove(child)` removes `child`, which must be somewhere below `element` in the DOM tree (not necessarily a child of `element`)

Since Brython must support the DOM API, it is not a good idea to keep a Brython-specific method. In the commit referenced above, `remove()` behaves like in the DOM API, and writes a warning in the console for existing code that uses this method. I have removed the method from the documentation and adapted the demos in the gallery.

With this change, the code in your example can be
```
for row in tbody.get(selector="TR"):
    tbody.removeChild(row)
    break
```
or
```
for row in tbody.get(selector="TR"):
    row.remove()
    break
```

Is this ok for you, or do you see other options ?

**Comment by hir3npatel** [comment]
Thanks for the quick investigation and fix, much appreciated. removeChild is perfect, it also reads a lot better in the code, I will adjust the code. Thanks for fixing the docs too, I was using remove because that's how the docs had it. Glad it's solved though, thanks again.

**Comment by PierreQuentel** [comment]
Cool, I close the issue then.
