### ISSUE TITLE
Function evaluated multiple times in chained expressions

### ISSUE THREAD

**Issue by jonathanverner** [brython-dev/brython#575]
I came across this [old post](https://news.ycombinator.com/item?id=5807700) on YCombinator which mentions the following incompatibility between Brython and CPython:
```python
x = 0
def impure():
    global x
    x += 1
    return x

print(0 < impure() <= 1)
```
In the comparison on the last line the function `impure` is called only once by CPython, but twice by Brython.

**Comment by PierreQuentel** [comment]
Thanks for mentioning this very old bug, I don't remember seeing it at the time.

It was because `expr1 < expr2 < expr3` was naively translated to 

```python
(expr1 < expr2) and (expr2 < expr3)
```
so when `expr2` was a function call, the call was made twice...

I had to modify it to the result of an anonymous Javascript function, something like : 

```javascript
(function(){var tempvar=expr2; return (expr1 < tempvar) && (tempvar < expr2)})()
```
