### ISSUE TITLE
import asyncio 

### ISSUE THREAD

**Issue by Anon731** [brython-dev/brython#616]
Importing asyncio module raises errors. ([tested in your console](https://www.brython.info/tests/console.html?lang=en,))
It requires selector.py file which one requires 'another',py file. 

Do i actually have to import this module in some specific way or its just a bug?

**Comment by jonathanverner** [comment]
It is probably a bug. I was the one who originally implemented asyncio support, but that was when I was just starting to learn async-style programming in python. I have a much simplified [version](https://gitlab.com/Verner/Logika-Website/blob/master/site/django_brython/static/django_brython/python/brdj/simpleaio.py) of asyncio suitable for the browser (and mostly compatible with the standard asyncio) and will try to eventually merge it. But don't hold your breath, I don't have much time these days :-(

**Comment by mementum** [comment]
> I have a much simplified version of [asyncio](https://gitlab.com/Verner/Logika-Website/blob/master/site/django_brython/static/django_brython/python/brdj/simpleaio.py) suitable for the browser

The link is not reachable for mere mortals (`404`)

But I think the point raised by @Anon731 is simply importing the module is broken whilst at the same time being present in the documentation with an example:

  - https://www.brython.info/static_doc/en/asyncio.html

(Even if in Spanish)

People will try the example, see it's broken and get the wrong opinion about `brython`

Potential approaches

  - Fix it (but holding the breath is currently not the best option)
  - Remove the aforementioned documentation page to avoid creating any false expectations
  - Add a disclaimer to the page indicating that the module used to work in an older version of Brython but it currently doesn't

Note: `asyncio/selectors.py` is present. It's only functionality seems to be to choose between the different `select/poll` methods available in different *Unix* variants. It may be worth a try disregarding the import, because such select are not going to be present in the browser.

**Comment by jonathanverner** [comment]
@mementum about the link: I forgot that the repository is private, sorry.

As you don't like holding your breath, the merge request #634 should fix asyncio. The documentation page should still include a disclaimer, though, because so far it is not very well tested.

As far as selectors & other win/unix specific stuff is concerned, the new implementation throws out a large chunk of the stuff which doesn't make sense in the browser. 

If you are interested in asyncio & Brython, I would love to hear your thoughts both on the implementation and on stuff which would be nice to have...

**Comment by mementum** [comment]
Thanks for adding the pull request. As it has already been integrated, I will (and I guess others too) have a look at it.

`asyncio` is of course interesting to replicate the patterns usually seen in `javascript`, but the shock here is that when looking at the docs ... it should have simply worked ... but as the OP of this ticket initially noticed it didn't.

With regards to Brython and even if listing that in this ticket is for sure out of scope, a couple of things which were mentioned in other ticket related to *metaclasses*

  - Support of `__init__` and `__call__` in metaclasses.
  - Support of `setattr(cls, ...)` during `__new__` in metaclasses (once the class has been created)

My projects do usually tend to make heavy use of metaclasses following C++ principles: *do as much as possible during compilation and a lot less when executing*. If something can be done at class level it will only be done once, rather than during the instantiation of each object.

A long shot:

  - A reorganization of the filesystem. `stable` (for `cdn.rawgit`) is a `tag`. Hence the question: *Can it be a branch ala `gh-pages`?

    The idea behind this is to have a very light branch which only serves as a delivery vehicle, contains only the necessary files and is completely isolated from the master/development branches.

  - Generalization of `scripts/*`. A quick look at some of them seems to show that some things are hard-coded. `make_dist.py` can for example be generalized for people to generate their own `.vfs.js`

  - Some work in the documentation. Some examples

    - `asyncio` is in Spanish in the English version and not present in the Spanish version

   - `<link rel="pythonpath" ...` is not documented in the import mechanism.

      See here: https://www.brython.info/static_doc/en/import.html

      But it is documented in a foreign site apparently for an older version: https://www.calculator29.com/Software/Lab/Brython/static_doc/en/import.html

This is no criticism of the project. Just areas that seem to have room for improvement (documentation is at the end of the day the hardest part, because programming is fun and documenting isn't)

**Comment by jonathanverner** [comment]
As far as documentation goes, I will try to write something longer for asyncio. The current state is probably due to commit fd77a53fccd7f6f794c where @kikocorreoso translated my original writeup to Spanish, but in the process replaced the English version with the Spanish one :-)

**Comment by mementum** [comment]
In any case and with merge of the simpler `asyncio` this ticket can probably be closed.
