### ISSUE TITLE
Feature request: add pip support client side

### ISSUE THREAD

**Issue by windelbouwman** [brython-dev/brython#635]
Hello,

It would be great if from a running console, python packages could be installed by using some sort of a pip command. I guess packages would then be downloaded from pypi and compiled and loaded via brython. Is this worth adding? Or is this already possible in some sense?

Best regards,
Windel

**Comment by jonathanverner** [comment]
It would, of  course, have to be limited to pure python packages. And even for them, it would be probably very hard (you would have to port pip to Brython and deal with the fact that in the Browser, you don't have a proper filesystem). Still, I think it might be doable...

**Comment by windelbouwman** [comment]
Okay, good to know that it is doable! What would be a logical sequence of steps to get this done?

I can imagine something like this:
- Add some sort of virtual file system (VFS) support
- Port pip

But probably there is more details involved?

**Comment by PierreQuentel** [comment]
I think the easiest would be to improve the __brython__ package.

Currently it can build the setup.py for a whole Brython application, so that the application can be uploaded to PyPI and installed by the standard __pip__  (cf. issue #491 for details).

For a package, I imagine that another option for __brython__ would create the setup.py script to upload the package to PyPI.

I have not started to work on it, but I imagine that in a Brython application directory, running something like

```
python -m my_package --install
```

would add the package files in the __brython_modules.js__ script and / or add the package files in the directory so that they can be imported by the standard Brython import mechanism.

**Comment by chfw** [comment]
I have just released a mini tool, [brython-pack](https://github.com/chfw/brython-pack) that packs your **pure** python library, as well as its prescribed dependencies on brython_stdlib, into a single brython VFS file(brython_modules.js). 

And during the packing process, it strips off docstrings and useless newlines in order to reduce file size.

Hope this tool answers the feasibility question and allow you to wish more :)

**Comment by jonathanverner** [comment]
@chfw This is very interesting. It would be nice to integrate this with @PierreQuentel's brython script which automatically figures out the dependencies (by parsing the python files and searching for import statements). Btw, your [pyecharts.js](https://github.com/chfw/pyecharts.js) seems very nice. It might be nice to either add it to the [Gallery](http://www.brython.info/gallery/gallery_en.html?lang=en) or add a new section to the website having links to Brython in actual use... What do you think, @PierreQuentel ?

**Comment by chfw** [comment]
@jonathanverner , I am glad that you liked pyecharts.js. And I am happy to get it listed on brython site. It's a honour. I will try to figure out the auto-lookup of dependencies in next release.

**Comment by PierreQuentel** [comment]
@chfw I like it too, can you add it to the wiki page "Brython in the wild" ?

I'm looking forward to next versions of brython-pack, packaging Brython applications is discussed in issue #491 but the current solutions need to be improved.

**Comment by niccokunzmann** [comment]
I would like to include modules from the site-packages.

PyInstaller allows for code analysis and which modules include which.
```
from PyInstaller.lib.modulegraph import find_modules
g = find_modules.find_modules([], ["pytest"])
print(list(g.getReferences("pytest")))

```

> It would be nice to integrate this with @PierreQuentel's brython script which automatically figures out the dependencies (by parsing the python files and searching for import statements)

Which module are you referring to?

I wonder how to include packages from the site-packages.
1. included in the `__BRYTHON__.VFS`
2. Could we also add a loader to the [meta_path](https://docs.python.org/3/reference/import.html#the-meta-path) which loads the modules from other locations such as zip files?
3. Maybe, it would also be sufficient, to install packages to a virtualenv, zip the folder and include it via a zip-loader.
4. Or maybe not even this but to copy the site-packages folder next to the html file. Thus, import statements handle the modules.

I am fairly new to brython, so I wonder: How can I include pytest so I can import it and how can this be achieved elegantly for any pure-python module.

Now reading https://github.com/brython-dev/brython/issues/491 .

**Comment by PierreQuentel** [comment]
I am closing this old issue. The requested feature is not implemented, what you can do is to install CPython packages with pip, then add them to a Brython application by `python -m brython add_package <package_name>`.
