### ISSUE TITLE
possible silent overflow of larger ints

### ISSUE THREAD

**Issue by vbr** [brython-dev/brython#68]
Hi,
I only recently tested Brython and am pretty amazed - thanks for providing this implementation!

While experimentig in the interactive mode, I noticed an unexpected behaviour for larger ints, which may indicate silent overflows; floats are more sensible in this case. cf. the following results (using Opera 27 dev on win 7):

Brython 3.0.0 on Netscape 5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2188.2 Safari/537.36 OPR/27.0.1683.0 (Edition developer)
>>> [(x,2**x) for x in range(68,80)]
[(68, 295147905179352830000), (69, 590295810358705700000), (70, 1), (71, 2), (72, 4), (73, 9), (74, 1), (75, 3), (76, 7), (77, 1), (78, 3), (79, 6)]
>>> [(x,2.0**x) for x in range(68,80)]
[(68, 295147905179352830000.0), (69, 590295810358705700000.0), (70, 1.1805916207174113e+21), (71, 2.3611832414348226e+21), (72, 4.722366482869645e+21), (73, 9.44473296573929e+21), (74, 1.888946593147858e+22), (75, 3.777893186295716e+22), (76, 7.555786372591432e+22), (77, 1.5111572745182865e+23), (78, 3.022314549036573e+23), (79, 6.044629098073146e+23)]
>>> 
Some oddities also appear at the bounds of the float type - the integers start to appear as NaNs: 

>>> [(x,2**x) for x in range(1020,1030)]
[(1020, 1), (1021, 2), (1022, 4), (1023, 8), (1024, NaN), (1025, NaN), (1026, NaN), (1027, NaN), (1028, NaN), (1029, NaN)]
>>> [(x,2.0**x) for x in range(1020,1030)]
[(1020, 1.1235582092889474e+307), (1021, 2.247116418577895e+307), (1022, 4.49423283715579e+307), (1023, 8.98846567431158e+307), (1024, inf), (1025, inf), (1026, inf), (1027, inf), (1028, inf), (1029, inf)]
>>> 

I currently don't have usecases for such calculations in Brython, but I'd prefer a more transparent handling of these cases; probably raising an exception (as the generally unlimited precission of int in python probably isn't available in the underlying javascript).

regards,
   vbr

**Comment by earney** [comment]
Pierre has created the long_int module, and I've created a long_int1 which "imports" the javascript libraries big.js, bignumber.js and decimal.js.  These libraries are very similar, so it was easy to create a wrapper for these javascript libraries in python.

**Comment by earney** [comment]
Should we allow the int object be "promoted" to a long_int object if we think a mathematical function will result in a value greater than 2^53?   This could add some some additional complexity to the int object, and could slow operators down a bit.  This is definitely a down side, or maybe we could have an option in the brython function to use a long_int instead of an int as the default?   Just a thought...

What do others think?

**Comment by PierreQuentel** [comment]
Brython currently uses native Javascript numbers to represent Python integers. Any other solution would ruin performance : at the moment the loop

```python
a = 0
for i in range(N):
    a += 1
```

is faster than with CPython, I don't think it can be the case with any implementation of long_int (but I would be glad to be wrong)

Another option would be to add tests on all operations on integers to see if the result is beyond the Javascript range, and in this case return an instance of `long_int`, but this would also reduce performance a lot. All this for use cases which are not so common - the bug was reported more than 2 years after Brython was first published.

In my opinion, we should leave the implementation as it is now, document this difference with the Python language reference, and provide a `long_int` module to be used in the cases when developers need integers of arbitrary length ; for instance, the `uuid` module should be modified to use `long_int` instead of `int`.

**Comment by juancarlospaco** [comment]
Ok, it should not be the unique difference with CPython3 anyways *(Remember the `print` with 256 args bug)*
:smile_cat:

**Comment by PierreQuentel** [comment]
Juan Carlo,

That's correct, but don't confuse the Python Language Reference and the CPython implementation ; I don't think the number of arguments is specified in the Language Reference, but the fact that integers have unlimited length is, in section 3.2 : 

```
Integers (int)

    These represent numbers in an unlimited range, subject to available (virtual) 
    memory only
```

**Comment by juancarlospaco** [comment]
Both facts are correct  :smile:  I agree with the consensus.

**Comment by kikocorreoso** [comment]
+1 on what @PierreQuentel says (leave the actual implementation). Brython should be CPython compliant but we will have some corner cases like this one. And performance is quite important also.

**Comment by vbr** [comment]
I am happy with the proposed approach to keep the default numeber operations using the native javascript numbers and providing the long_int implementation.
(I am not sure, whether some additional functions could be provided for testing the precision,but I guess, this could be more or less a matter of comparing the result of the computation with ints and long_ints, which can be done manually anyway.)

**Comment by earney** [comment]
+1

**Comment by earney** [comment]
can we close this, or are there some issues we need need to address?

**Comment by earney** [comment]
I have not heard anything for almost 2 months, so I'm going to close this.  Please reopen if necessary.
