### ISSUE TITLE
re module

### ISSUE THREAD

**Issue by JamesHutchison** [brython-dev/brython#70]
The re module results in a very large performance hit when it's imported. It also fails this regex I encountered:

```
import re
a = 'hello() abcdefg'
re.match('''(.*?)(\S+)\Z''', a)
```

This should match the string given but it doesn't.

**Comment by PierreQuentel** [comment]
I just found that it's not related to the re module itself, it's because of a bug in the handling of the backslash character in strings. '\S' should be equal to r'\S', but Brython makes them different. If you make the first argument of re.match a raw string
```python
re.match(r'''(.*?)(\S+)\Z''', a)
```
the result is correct

I will see if I can fix this
