### ISSUE TITLE
Travis-CI is broken

### ISSUE THREAD

**Issue by mementum** [brython-dev/brython#740]
With this commmit 4de50db52b3d16860ad80f356c54615994079e0c because PhatomJS doesn't support `Number.isInteger` and `Number.isSafeInteger`

According to *MDN* both are not supported by *Internet Explorer*. For example:

  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

**Comment by jonathanverner** [comment]
I am not sure adding Polyfills just because PhantomJS does not support a given feature makes sense. The problem with PhantomJS is that its development status is not clear (it has a maintainer, but the last release was almost two years ago, not counting the minor pre-release 9 days ago). Moreover it is based on QtWebKit (itself based on WebKit from 2013) which is being deprecated by Qt. Anyway, for the time being I have disabled testing on PhantomJS in bca00e2906d557329452dfad630a3335507076. It would be much more interesting to test on Edge and Safari, I will try to investigate using [saucelabs](https://saucelabs.com/) for this...

**Comment by mementum** [comment]
In this case and much more than PhantomJS the problem, imho, is *Internet Explorer* which doesn't support those primitives.

One could of course consider deprecating support for *Internet Explorer* in *brython*, which would in turn open the door to write more modern and better *Javascript* (by no means am I an expert, not even a decent beginner), but I believe it would at the same time hinder the adoption of *brython* (for whatever the reason, there are always people looking for *Internet Explorer* compatibility)

Just my two cents.

**Comment by jonathanverner** [comment]
Sorry, I missed the negation in the sentence "according to MDN both are **not** supported" :-) Adding a polyfill in this case of course makes more sense. 

On a sidenote, I wonder whether it would make sense to use a transpiler (e.g. [babel](https://babeljs.io/)) to preprocess brython. That would allow us to use modern javascript (which is much, much, better). But this is slightly offtopic in this thread and should be discussed on [the mailing list]( https://groups.google.com/d/msg/brython/bxlzUEEivos/5KOgKSc2DAAJ).
