### ISSUE TITLE
Problems with module ipaddress

### ISSUE THREAD

**Issue by aparamon** [brython-dev/brython#794]
[ipaddress](https://docs.python.org/3/library/ipaddress.html) is a very minimal module depending only on functools. Unfortunately, it is not interpreted correctly by Brython. To reproduce:
```python
import ipaddress
print(ipaddress.ip_address('192.168.0.1'))
print(ipaddress.ip_address('2001:db8::'))
```
As a result:
1. Import takes ~30 sec on my laptop,
2. Memory is quickly depleted if Chrome DevTools is open,
3. Exception is raised:
```pytb
Traceback (most recent call last):
  module __main__ line 2
    print(ipaddress.ip_address('192.168.0.1'))
NotImplementedError: int.to_bytes is not implemented yet
```
For completeness, CPython outputs:
```
192.168.0.1
2001:db8::
```

**Comment by jonathanverner** [comment]
- The slow import is probably due to functools being a very heavy import. The best option here is to just reimplement the two decorators (`total_ordering` and `lru_cache`) inline in `ipaddress.py`.
- I have no idea where the memory use comes from, this is probably a separate bug. Unfortunately, I can't help much here as I don't have any experience debugging "memory leaks" in javascript.
- The `NotImplementedError` is there because no one had the time to implement the `to_bytes` method of `int`. I currently don't have almost any time, but I'd be happy to review and merge a pull request, if you provided one. The implementation should go [here](https://github.com/brython-dev/brython/blob/f51804c2e79acc54dddfe356965170e439ce0d12/www/src/py_int.js#L77).

**Comment by aparamon** [comment]
An experiment shows that `functools` is not the culprit:
```python
import functools
print(dir(functools))
```
gets executed quickly and successfully.
From the code, I cannot see that `ipaddress` does something particularly heavy/unusual; maybe there is some obvious/easy-to-spot buglet in Brython?

I'm not sure how to debug mem-leaks also, unfortunately, but it seems that long import time and mem-leaks are connected.
