### ISSUE TITLE
'document' decorator examples aren't valid python

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#805]
The demo often suggests this syntax:

```
@document['something'].bind("click")
def something(event):
    ...
```

This is not syntactically valid Python.  Specifically, the thing that goes after `@` in a decorator is not a general expression, but has certain limitations.  Brython's suggested way of handling events probably shouldn't be built around a pattern that will give learners syntax errors when they try with any other python runtime!

**Comment by PierreQuentel** [comment]
Oops ! I didn't know that, I thought that any expression could be a decorator. Reading the [PEP](https://www.python.org/dev/peps/pep-0318/), it is mentioned that it was rejected due to [Guido's "gut feeling"](https://mail.python.org/pipermail/python-dev/2004-August/046711.html).

I will have to change the documentation and example for compliance. But do you think there is a chance that this use case makes the core devs reconsider their position ?

**Comment by glyph** [comment]
Ironically I disagree strongly with this decision, and to this day frequently want to do `@somethingDeferred(...).addCallback)` and am annoyed that it is not possible. So if I could have influenced the core devs’ position here I already would have :)

**Comment by BrenBarn** [comment]
It seems like there would be other ways to use a decorator-based binding syntax that still comply with Python syntax.  What about `@bind('element_id', 'click')`?  I think it would also be possible to create a magic `element-getter` object that uses `__getattr__` to allow something like `@doc.element_id.bind('click')`.

**Comment by PierreQuentel** [comment]
@BrenBarn 

Looks nice, thanks ! `bind()` would have to be in module __browser__ I guess.

The first argument of `bind(target, event)` could be a string, in this case the best would be a CSS selector, as suggested by Jonathan.
```python
@bind("#btn-1", "click") # selection by id ; binds a single element
@bind(".foo", "click") # selection by class ; binds several elements
def click(evt):
    print("clicked", evt.target.text)
```

It could also be a reference to a single DOMNode instance, or to a list of DOMNode instances:
```python
# single element
element = document.select("button")[3]
@bind(element, "click")
def click1(evt):
    ...

elements = [elt for elt in document.select["td"] 
    if elt.text.startswith("XXX")]
@bind(elements, "click")
def click2(evt):
    ...
```

These don't add much to the current syntax:
```python
def click1(evt):
    ...
document.select("button")[3].bind("click", click1)

def click2(evt):
    ...
for element in [elt for elt in document.select["td"] if elt.text.startswith("XXX")]:
    element.bind("click", click2)
```
except that we wouldn't have to type the function name twice.

Your second suggestion to replace `document["element_id"]` by `document.element_id` is unfortunately not possible for the reason given by Jonathan ; you couldn't handle an id such as "row-1".

I will commit a first implementation of `browser.bind()` shortly so that you can test it and suggest changes / improvements. @BrenBarn can you post a message on the Google Group to get more feedback ?
