### ISSUE TITLE
standard logging library 

### ISSUE THREAD

**Issue by bcopy** [brython-dev/brython#841]
Hi, I'm trying to use standard python logging.

When running the following in the Brython editor...  :

```python
import logging
logger = logging.getLogger(__name__)
logger.debug("Hello world")
```
... I get :
```
'cOutput' object has no attribute '__len__'
```

Is standard python logging supported in Brython ? Must it be set up a certain way ?

**Comment by jonathanverner** [comment]
Hmm, yet another bug in my [performance "fix"](https://github.com/brython-dev/brython/commit/bfd0c1db2cd23aaa1f7f80107245699a7d7714a7) of the editor & console stdout implementation. Logging should normally be supported, it just isn't by the editor and console at the moment... I'll try to fix this as soon as possible, but since on Friday I am leaving out of internet reach for a month, this might be delayed...

**Comment by jonathanverner** [comment]
Actually, I will keep this bug open as the logging library still fails (although for a different reason now):

The failure is somewhat mysterious. It seems that setting `record.message` on line 547 of logging/__init__.py doesn't make it available in `record.__dict__` leading to an error on line 365 of the
same file...

**Comment by PierreQuentel** [comment]
The example in the original post now passes without error (it's not clear to me what it's supposed to do - I never used the `logging` package - but in CPython there is no visible result either).
I am closing this issue. If there are other problems with this package please open another issue.
