### ISSUE TITLE
indexedDB cache prevents reloading client code (brython_modules.js style)

### ISSUE THREAD

**Issue by benjaminrigaud** [brython-dev/brython#860]
Hello!

I just cloned master to hunt  new bugs and create a new project and I discovered the indexedDB cache won't let me reload some code I just updated & compiled into a new brython_modules.js

A force refresh won't help: I still see the first version of my code.
The page loaded in a private window works fine.

I use brython_modules.js

workaround: `indexedDB.deleteDatabase('brython_stdlib')` in the javascript console.

**Comment by PierreQuentel** [comment]
Commit  fa235b2 should have fixed it ; can you check ?

**Comment by benjaminrigaud** [comment]
Hello @PierreQuentel 

Sorry, It doesn't work (Tested on Chrome) :

```
using indexedDB for stdlib modules cache
hello imported 3 (it should be 4)
[Violation] 'success' handler took 4709ms
```

I would say it is worse :) Now it always takes 5 seconds to load.

Do you have selenium tests? I could try to make a new one reproducing the issue.

Ben

**Comment by PierreQuentel** [comment]
@benjaminrigaud 
Same question as for issue #881 : you say that the script doesn't work, but it seems that [Violation] is only a warning in Chrome (cf this [post](https://stackoverflow.com/questions/42218699/javascript-chrome-violation-violation-handler-took-83ms-of-runtime) on stackoverflow)

**Comment by benjaminrigaud** [comment]
Hello Pierre,

The script is working fine, but it is loading the previous version (the cached one) and it won't refresh the most recent one.

The warning highlights a high loading time: is that expected to be that high with IndexedDB?

Ben

**Comment by PierreQuentel** [comment]
With the latest versions the bug seems to have been fixed:
- create a new Brython instance in a folder with `python -m brython --install`
- in this folder create the script __`a.py`__
```python
x = 1
```
- remove __`demo.html`__ to avoid adding the stdlib scripts it needs in
  __`brython_modules.js`__
- edit the __`index.html`__ file with the script
```python
import a
print(a.x)
```
- run `python -m brython --modules`
- in __`index.html`__, replace
```xml
<script type="text/javascript" src="brython_stdlib.js"></script>
```
by
```xml
<script type="text/javascript" src="brython_modules.js"></script>
```
- start the web server (`python -m http.server 8081`) and open url
  _http://localhost:8081_ : the browser console shows the information
  message "using indexedDB for stdlib modules cache" and the result is "1"

- edit __`a.py`__
```
x = 2
```
- re-run `python -m brython --modules` and reload the page : the console shows
  "2" as expected

I close the issue, if you find cases when the code is not correctly reloaded feel free to re-open it.
