### ISSUE TITLE
datetime.strptime increases load / init time by ~5 seconds

### ISSUE THREAD

**Issue by benjaminrigaud** [brython-dev/brython#881]
Hello,

Something like:
```
from datetime import datetime
print(datetime.strptime('2018-07-01', '%Y-%m-%d'))
```
Will add about 5 seconds to the loading / init time of my page.

With or without indexedDB.

Chrome gives me a warning `[Violation] 'readystatechange' handler took 5162ms`

**Comment by PierreQuentel** [comment]
@benjaminrigaud 
I also get slower results with Chrome than with Firefox (which takes ~2 seconds with indexedDB cache), but it seems to be only a warning : does the script work, ie prints the date ?

**Comment by benjaminrigaud** [comment]
Hello Pierre,

The script is working fine, but it is loading the previous version (the cached one) and it won't refresh the most recent one.

The warning highlights a high loading time: is that expected to be that high with IndexedDB?

Ben

**Comment by PierreQuentel** [comment]
Bonjour Benjamin,

In commit 15cdad930b5bc7a62785b4ff90a4dc04dedea488 I have rewritten the `strptime()` implementation, using a Javascript module instead of the pure Python module used before, which imported many other modules. On my PC, with indexedDB cache enabled, the code runs much faster with this new version. Can you check ?
The new module is still work in progess, some formats are not handled yet.

**Comment by PierreQuentel** [comment]
I close the issue, in case you think there is still a problem you can reopen it. Merci !
