### ISSUE TITLE
object creation performance and object organization

### ISSUE THREAD

**Issue by JamesHutchison** [brython-dev/brython#90]
I'm making this a short issue because I'm still looking into this, but while attempting to better optimize the string formatting, I found that there is quite a lot of overhead of to creating some objects, and this stems due to some core functions having to do more work than they should.

For example, `getattr` should really be done just like python. You just traverse backwards in a list of dictionaries looking for a key, and then throw an attribute error when you run out. Unfortunately, the function is filled with special cases and does work that should be done somewhere else (like creating a function from an existing function). From what I can tell, this stems from providing compatibility with javascript objects and some of it may not even be applicable anymore.

Instantiating tuples, lists, and dicts which should be cheap, are also expensive. In fact they're more expensive than instantiating custom classes.

Here's different code @ 1000 iterations, after I've already applied some optimizations. `foo` is just a dummy class:

```
{} 0.2739999294281006
foo() 0.003000020980834961
[1,2,3] 0.09300017356872559
(1,2,3) 0.09099984169006348
"%s" % "hello" 0.018000125885009766
("hello",) 0.09799981117248535
"%s" % ("hello",) 0.11699986457824707
"hello" + "_" + "there" 0.009999990463256836
"%s_%s" % ("hello", "there") 0.12899994850158691
```

**Comment by PierreQuentel** [comment]
Thanks for the report, very interesting

I just pushed changeset 4e55eac2f6a74cb7155273ccbd15b47b7d00974a which speeds up literal list and tuple creation

In the general case, yes, getattr is complex. It has to handle the complexity of attribute resolution in Python, with multiple inheritance, different kinds of class methods (staticmethod, classmethod etc.), descriptors and properties, etc.

You are probably right saying that in some cases the process could be simplified. Can you elaborate for instance on "creating a function from an existing function" ? Maybe you refer to the resolution of x.f where x in an instance of a class A which defines a method f : currently, a new function is created every time the resolution is done. This is because f may have been modified between two resolutions, as in

```python
print(x.f)
A.f = other_function
print(x.f)
```

**Comment by JamesHutchison** [comment]
Nice change, here's 1000 formats with your improvement:

[1,2,3] 0.002000093460083008
(1,2,3) 0.000999927520751953
"%s_%s" % ("hello", "there") 0.14700007438659668

And here it is after I apply with my optimizations:

"%s_%s" % ("hello", "there") 0.04399991035461426

Not bad, going from ~500 ms to ~40 ms :)

My format code is still WIP but I would expect the string legacy format to end up being about the speed given.

**Comment by cforger** [comment]
Since this is referenced in another issue, I wonder if it's possible to break this task up into smaller chunks, so others can handle some of it? While the larger issue of optimizing object creation is clear to me, including how to properly timeit to ensure progress, what can be chopped/replaced is less clear for anyone new to Brython.

To put it another way - Has anyone written a source overview of Brython, or thought about increasing the comment level in the code? Check out CPython's py_dict.c - It's very well documented, and makes it easy for anyone to jump in and start applying modifications.

In a few weeks I'll have more time to browse the source and grok things, but more documentation would always be welcome.

**Comment by earney** [comment]
do you mean: https://hg.python.org/cpython/file/3a95a74aca4e/Objects/dictobject.c

**Comment by cforger** [comment]
Pardon me, yes - Getting confused on the naming conventions.

**Comment by earney** [comment]
LOL.. At first I thought,  thats where Pierre got the naming convention  py_xxxx.   :)

**Comment by PierreQuentel** [comment]
I think we can close this issue
