### ISSUE TITLE
The del statement has no effect

### ISSUE THREAD

**Issue by coproc** [brython-dev/brython#923]
From the Brython console:
```python
Brython 3.7.0 on Netscape 5.0 (Windows)
>>> v

NameError: name 'v' is not defined
Traceback (most recent call last):
  module __main__ line 129, in myKeyPress
    _ = editor_ns['_'] = eval(currentLine, editor_ns)
  module <module> line 1
    v
>>> v = 1
>>> v
1
>>> del v
>>> v
1
```
But after `del v` accessing `v` should raise a `NameError` again.

**Comment by pavelmaksimov** [comment]
I am also interested in this behavior

**Comment by darthglowball** [comment]
The del function doesn't work in this case:

`<script id="script0" type="text/python">
      from browser import alert
      hello = {"a":1,"b":2}
      alert(len(hello))
      del(hello["a"])
      alert(len(hello))
    </script>`

It should alert 2 then 1, but it alerts 2 then 2 in Chrome.

**Comment by PierreQuentel** [comment]
Sorry, I can't reproduce this bug, I get the correct result (2 then 1).

**Comment by darthglowball** [comment]
The bug happens on Chrome version 75.0.3770.100, 32-bit; Opera version 60.0.3255.170, 32-bit; and the latest version of Chromium Embedded Framework Python (cefpython). Tested on Windows 7 32-bit. I use a local brython.js and brython_stdlib.js on disk. As these browsers all use Chromium, that may be a potential suspect. 
However, I couldn't test it on Firefox because there is an error with Brython: "could not open indexedDB database". And Internet Explorer is full of other errors with Brython.

**Comment by darthglowball** [comment]
To be fair, before suspecting Chromium, I'll try the javascript equivalent of Python's del(). What javascript equivalent does Brython use for del()?

**Comment by PierreQuentel** [comment]
My mistake, sorry : when I tested your example I removed the parenthesis: 
```python
del hello["a"]
```
instead of 
```python
del(hello["a"])
```
and the bug happened _with_ the parenthesis.

Thanks for the report !
