### ISSUE TITLE
erreur open with brython_stdlib.js

### ISSUE THREAD

**Issue by johnlarfour** [brython-dev/brython#931]
I get `erreur open` in the console when I add this line `<script src="/brython_stdlib.js"></script>` in index.html. If I delete it, I don't get the erreur open I don't know where is the problem.

**Comment by PierreQuentel** [comment]
@johnlarfour 
Interesting ! The message (that I will make more explicit...) indicates that the indexedDB database couldn't be opened. Can you detail the configuration : computer or smatphone, OS, browser ?

**Comment by johnlarfour** [comment]
I use Ubuntu with Mozilla Firefox.

**Comment by PierreQuentel** [comment]
I don't know where the problem comes from. There must be a way to disable indexedDB in Firefox, maybe it's the case ?
Anyway, even if the database can't be opened, the Brython code will run ; it's just that the precompilation of standard library modules won't work, with a possible penalty on performance.
