### ISSUE TITLE
No Python RecursionError raised when call stack is too large

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#986]
```python
def f(): f()

f()
```

A JS RangeError is printed to the console when this code is run, but no Python exception is raised.

**Comment by PierreQuentel** [comment]
Very old issue, sorry...

The fix is not very clean, but Javascript implementations don't throw the same error. In the fix, the test is on the error type and error message as mentioned in the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Too_much_recursion). The correct Python error is now raised for Firefox, Edge and Chrome ; I can't test on Safari.

**Comment by schmave** [comment]
Wow, wonderful! Thanks, Pierre.
