### ISSUE TITLE
OrderedDict views regression

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#998]
Salut,
The ``keys()`` view for OrderedDict seems to ignore all but the first item in the dict.
````
from collections import OrderedDict
d = OrderedDict()
d['a'] = 2
d['b'] = 3
print(list(d.keys()))
````
Brython 3.6.2 correctly gave as output ``['a', 'b']`` but Brython 3.7.0rc2 gives ``['a']``. Also, the other views ``items()`` and ``values()`` have the same problem. Merci!

**Comment by steaward** [comment]
I've been able to replicate this, going to give fixing it a shot...

**Comment by PierreQuentel** [comment]
@tjnaughton Thanks for reporting the bug !
@steaward I really appreciate you proposing to fix it, but I had started investigating and found that the bug was in the pure-Python implementation I wrote of the `_weakref` module; I'm afraid it would have taken you much work to detect and to fix - sorry if I am wrong.

**Comment by steaward** [comment]
@PierreQuentel  You are not wrong, I've been investigating all day... Glad you found the fix!
